package com.imc.efs.automation.entities;

// Generated Mar 16, 2015 4:02:11 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * RequestTypeComments generated by hbm2java
 */
@Entity
@Table(name = "RequestTypeComments", schema = "dbo", catalog = "EfsAutomation")
public class RequestTypeComments implements java.io.Serializable {

	private int id;
	private Date timestamp;
	private RequestTypes requestTypes;
	private Serializable note;
	private Serializable user;

	public RequestTypeComments() {
	}

	public RequestTypeComments(int id, RequestTypes requestTypes) {
		this.id = id;
		this.requestTypes = requestTypes;
	}

	public RequestTypeComments(int id, RequestTypes requestTypes,
			Serializable note, Serializable user) {
		this.id = id;
		this.requestTypes = requestTypes;
		this.note = note;
		this.user = user;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Timestamp", nullable = false, length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RequestTypeId", nullable = false)
	public RequestTypes getRequestTypes() {
		return this.requestTypes;
	}

	public void setRequestTypes(RequestTypes requestTypes) {
		this.requestTypes = requestTypes;
	}

	@Column(name = "Note")
	public Serializable getNote() {
		return this.note;
	}

	public void setNote(Serializable note) {
		this.note = note;
	}

	@Column(name = "User")
	public Serializable getUser() {
		return this.user;
	}

	public void setUser(Serializable user) {
		this.user = user;
	}

}
