package com.imc.efs.automation.entities;

// Generated Mar 16, 2015 4:02:11 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * RequestTypes generated by hbm2java
 */
@Entity
@Table(name = "\"RequestTypes\"", schema = "dbo")
public class RequestTypes implements Serializable {

	private int requestTypeId;
	private boolean isOpsPortalType;
	private boolean isDriverPay;
	private boolean requiresManagementApproval;
	private boolean requiresAuthorizedVendor;
	private boolean requiresInvoice;
	private boolean preventDuplicates;
	private String name;
	private RequestTypeConfigs requestTypeConfigs;
	private Set<Requesters> requesterses = new HashSet<Requesters>(0);
	private Set<Requests> requestses = new HashSet<Requests>(0);
	private Set<RequestTypeComments> requestTypeCommentses = new HashSet<RequestTypeComments>(
			0);
	private int driverId;
	private int vendorId;
	private int serviceCharge;
	private int proNumber;
	private int poWoNumber;
	private int truckId;
	private int ChassisNumber;
	private int ContainerNumber;
	private int claimNumber;
	private int claimType;
	private int tagEquipment;
	private int tagPurchType;
	private boolean isChargedToCustomer;

	public RequestTypes() {
	}

	public RequestTypes(int requestTypeId, boolean isOpsPortalType,
			boolean isDriverPay, boolean requiresManagementApproval,
			boolean requiresAuthorizedVendor, boolean requiresInvoice,
			boolean preventDuplicates, String name) {
		this.requestTypeId = requestTypeId;
		this.isOpsPortalType = isOpsPortalType;
		this.isDriverPay = isDriverPay;
		this.requiresManagementApproval = requiresManagementApproval;
		this.requiresAuthorizedVendor = requiresAuthorizedVendor;
		this.requiresInvoice = requiresInvoice;
		this.preventDuplicates = preventDuplicates;
		this.name = name;
	}

	public RequestTypes(int requestTypeId, boolean isOpsPortalType,
			boolean isDriverPay, boolean requiresManagementApproval,
			boolean requiresAuthorizedVendor, boolean requiresInvoice,
			boolean preventDuplicates, String name,
			RequestTypeConfigs requestTypeConfigs,
			Set<Requesters> requesterses, Set<Requests> requestses,
			Set<RequestTypeComments> requestTypeCommentses) {
		this.requestTypeId = requestTypeId;
		this.isOpsPortalType = isOpsPortalType;
		this.isDriverPay = isDriverPay;
		this.requiresManagementApproval = requiresManagementApproval;
		this.requiresAuthorizedVendor = requiresAuthorizedVendor;
		this.requiresInvoice = requiresInvoice;
		this.preventDuplicates = preventDuplicates;
		this.name = name;
		this.requestTypeConfigs = requestTypeConfigs;
		this.requesterses = requesterses;
		this.requestses = requestses;
		this.requestTypeCommentses = requestTypeCommentses;
	}

	@Id
	@Column(name = "\"RequestTypeId\"", unique = true, nullable = false)
	public int getRequestTypeId() {
		return this.requestTypeId;
	}

	public void setRequestTypeId(int requestTypeId) {
		this.requestTypeId = requestTypeId;
	}

	@Column(name = "\"IsOpsPortalType\"", nullable = false)
	public boolean isIsOpsPortalType() {
		return this.isOpsPortalType;
	}

	public void setIsOpsPortalType(boolean isOpsPortalType) {
		this.isOpsPortalType = isOpsPortalType;
	}

	@Column(name = "\"IsDriverPay\"", nullable = false)
	public boolean isIsDriverPay() {
		return this.isDriverPay;
	}

	public void setIsDriverPay(boolean isDriverPay) {
		this.isDriverPay = isDriverPay;
	}

	@Column(name = "\"RequiresManagementApproval\"", nullable = false)
	public boolean isRequiresManagementApproval() {
		return this.requiresManagementApproval;
	}

	public void setRequiresManagementApproval(boolean requiresManagementApproval) {
		this.requiresManagementApproval = requiresManagementApproval;
	}

	@Column(name = "\"RequiresAuthorizedVendor\"", nullable = false)
	public boolean isRequiresAuthorizedVendor() {
		return this.requiresAuthorizedVendor;
	}

	public void setRequiresAuthorizedVendor(boolean requiresAuthorizedVendor) {
		this.requiresAuthorizedVendor = requiresAuthorizedVendor;
	}

	@Column(name = "\"RequiresInvoice\"", nullable = false)
	public boolean isRequiresInvoice() {
		return this.requiresInvoice;
	}

	public void setRequiresInvoice(boolean requiresInvoice) {
		this.requiresInvoice = requiresInvoice;
	}

	@Column(name = "\"PreventDuplicates\"", nullable = false)
	public boolean isPreventDuplicates() {
		return this.preventDuplicates;
	}

	public void setPreventDuplicates(boolean preventDuplicates) {
		this.preventDuplicates = preventDuplicates;
	}

	@Column(name = "\"Name\"", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "requestTypes")
	public RequestTypeConfigs getRequestTypeConfigs() {
		return this.requestTypeConfigs;
	}

	public void setRequestTypeConfigs(RequestTypeConfigs requestTypeConfigs) {
		this.requestTypeConfigs = requestTypeConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requestTypes")
	public Set<Requesters> getRequesterses() {
		return this.requesterses;
	}

	public void setRequesterses(Set<Requesters> requesterses) {
		this.requesterses = requesterses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requestTypes")
	public Set<Requests> getRequestses() {
		return this.requestses;
	}

	public void setRequestses(Set<Requests> requestses) {
		this.requestses = requestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requestTypes")
	public Set<RequestTypeComments> getRequestTypeCommentses() {
		return this.requestTypeCommentses;
	}

	public void setRequestTypeCommentses(
			Set<RequestTypeComments> requestTypeCommentses) {
		this.requestTypeCommentses = requestTypeCommentses;
	}

	@Column(name = "\"DriverId\"", nullable = false)
	public int getDriverId() {
		return driverId;
	}

	public void setDriverId(int driverId) {
		this.driverId = driverId;
	}

	@Column(name = "\"VendorId\"", nullable = false)
	public int getVendorId() {
		return vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "\"ServiceCharge\"", nullable = false)
	public int getServiceCharge() {
		return serviceCharge;
	}

	public void setServiceCharge(int serviceCharge) {
		this.serviceCharge = serviceCharge;
	}

	@Column(name = "\"ProNumber\"", nullable = false)
	public int getProNumber() {
		return proNumber;
	}

	public void setProNumber(int proNumber) {
		this.proNumber = proNumber;
	}

	@Column(name = "\"PoWoNumber\"", nullable = false)
	public int getPoWoNumber() {
		return poWoNumber;
	}

	public void setPoWoNumber(int poWoNumber) {
		this.poWoNumber = poWoNumber;
	}

	@Column(name = "\"TruckId\"", nullable = false)
	public int getTruckId() {
		return truckId;
	}

	public void setTruckId(int truckId) {
		this.truckId = truckId;
	}

	@Column(name = "\"ChassisNumber\"", nullable = false)
	public int getChassisNumber() {
		return ChassisNumber;
	}

	public void setChassisNumber(int chassisNumber) {
		ChassisNumber = chassisNumber;
	}

	@Column(name = "\"ContainerNumber\"", nullable = false)
	public int getContainerNumber() {
		return ContainerNumber;
	}

	public void setContainerNumber(int containerNumber) {
		ContainerNumber = containerNumber;
	}

	@Column(name = "\"ClaimNumber\"", nullable = false)
	public int getClaimNumber() {
		return claimNumber;
	}

	public void setClaimNumber(int claimNumber) {
		this.claimNumber = claimNumber;
	}

	@Column(name = "\"ClaimType\"", nullable = false)
	public int getClaimType() {
		return claimType;
	}

	public void setClaimType(int claimType) {
		this.claimType = claimType;
	}

	@Column(name = "\"TagEquipment\"", nullable = false)
	public int getTagEquipment() {
		return tagEquipment;
	}

	public void setTagEquipment(int tagEquipment) {
		this.tagEquipment = tagEquipment;
	}

	@Column(name = "\"TagPurchType\"", nullable = false)
	public int getTagPurchType() {
		return tagPurchType;
	}

	public void setTagPurchType(int tagPurchType) {
		this.tagPurchType = tagPurchType;
	}

	@Column(name = "\"IsChargedToCustomer\"", nullable = false)
	public boolean isChargedToCustomer() {
		return isChargedToCustomer;
	}

	public void setChargedToCustomer(boolean isChargedToCustomer) {
		this.isChargedToCustomer = isChargedToCustomer;
	}

}
