package com.imc.efs.automation.entities;

// Generated Mar 16, 2015 4:02:11 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "Status", schema = "dbo", catalog = "EfsAutomation")
public class Status implements java.io.Serializable {

	private int statusId;
	private Serializable description;
	private Set<Requests> requestses = new HashSet<Requests>(0);

	public Status() {
	}

	public Status(int statusId) {
		this.statusId = statusId;
	}

	public Status(int statusId, Serializable description,
			Set<Requests> requestses) {
		this.statusId = statusId;
		this.description = description;
		this.requestses = requestses;
	}

	@Id
	@Column(name = "StatusId", unique = true, nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "Description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Requests> getRequestses() {
		return this.requestses;
	}

	public void setRequestses(Set<Requests> requestses) {
		this.requestses = requestses;
	}

}
