
package com.imc.business.logic.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EfsAutomationBusinessLogicWS", targetNamespace = "http://impl.ws.logic.business.automation.efs.imc.com/", wsdlLocation = "file:/C:/Users/bshipman/AppData/Local/Temp/tempdir7186855711520002123.tmp/EfsAutomationBusinessLogicWS_1.wsdl")
public class EfsAutomationBusinessLogicWS
    extends Service
{

    private final static URL EFSAUTOMATIONBUSINESSLOGICWS_WSDL_LOCATION;
    private final static WebServiceException EFSAUTOMATIONBUSINESSLOGICWS_EXCEPTION;
    private final static QName EFSAUTOMATIONBUSINESSLOGICWS_QNAME = new QName("http://impl.ws.logic.business.automation.efs.imc.com/", "EfsAutomationBusinessLogicWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/bshipman/AppData/Local/Temp/tempdir7186855711520002123.tmp/EfsAutomationBusinessLogicWS_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EFSAUTOMATIONBUSINESSLOGICWS_WSDL_LOCATION = url;
        EFSAUTOMATIONBUSINESSLOGICWS_EXCEPTION = e;
    }

    public EfsAutomationBusinessLogicWS() {
        super(__getWsdlLocation(), EFSAUTOMATIONBUSINESSLOGICWS_QNAME);
    }

    public EfsAutomationBusinessLogicWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), EFSAUTOMATIONBUSINESSLOGICWS_QNAME, features);
    }

    public EfsAutomationBusinessLogicWS(URL wsdlLocation) {
        super(wsdlLocation, EFSAUTOMATIONBUSINESSLOGICWS_QNAME);
    }

    public EfsAutomationBusinessLogicWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EFSAUTOMATIONBUSINESSLOGICWS_QNAME, features);
    }

    public EfsAutomationBusinessLogicWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EfsAutomationBusinessLogicWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EfsAutomationBusinessLogicService
     */
    @WebEndpoint(name = "EfsAutomationBusinessLogicWS")
    public EfsAutomationBusinessLogicService getEfsAutomationBusinessLogicWS() {
        return super.getPort(new QName("http://impl.ws.logic.business.automation.efs.imc.com/", "EfsAutomationBusinessLogicWS"), EfsAutomationBusinessLogicService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EfsAutomationBusinessLogicService
     */
    @WebEndpoint(name = "EfsAutomationBusinessLogicWS")
    public EfsAutomationBusinessLogicService getEfsAutomationBusinessLogicWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.logic.business.automation.efs.imc.com/", "EfsAutomationBusinessLogicWS"), EfsAutomationBusinessLogicService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EFSAUTOMATIONBUSINESSLOGICWS_EXCEPTION!= null) {
            throw EFSAUTOMATIONBUSINESSLOGICWS_EXCEPTION;
        }
        return EFSAUTOMATIONBUSINESSLOGICWS_WSDL_LOCATION;
    }

}
