
package com.imc.business.logic.service;

import java.math.BigDecimal;
import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.imc.efs.automation.data.EfsCheckRequest;
import com.imc.efs.automation.data.EfsMoneyCode;
import com.imc.efs.automation.data.FileUpload;
import com.imc.efs.automation.dto.MoneyCodeDetailsDTO;
import com.imc.efs.automation.entities.Requests;
import com.imc.efs.automation.entities.Requesttypes;
import com.imc.efs.automation.entities.Status;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EfsAutomationBusinessLogicService", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EfsAutomationBusinessLogicService {


    /**
     * 
     * @return
     *     returns java.util.List<com.imc.business.logic.service.Requests>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIssuedRequests", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetIssuedRequests")
    @ResponseWrapper(localName = "getIssuedRequestsResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetIssuedRequestsResponse")
    public List<Requests> getIssuedRequests();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateCredentials", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ValidateCredentials")
    @ResponseWrapper(localName = "validateCredentialsResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ValidateCredentialsResponse")
    public boolean validateCredentials(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.imc.business.logic.service.EfsMoneyCode
     */
    @WebMethod(operationName = "IssueMoneyCode")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "IssueMoneyCode", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.IssueMoneyCode")
    @ResponseWrapper(localName = "IssueMoneyCodeResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.IssueMoneyCodeResponse")
    public EfsMoneyCode issueMoneyCode(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.business.logic.service.Status
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetStatusResponse")
    public Status getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "sendIssuanceEmail", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.SendIssuanceEmail")
    @ResponseWrapper(localName = "sendIssuanceEmailResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.SendIssuanceEmailResponse")
    public void sendIssuanceEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createIssueDoc", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.CreateIssueDoc")
    @ResponseWrapper(localName = "createIssueDocResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.CreateIssueDocResponse")
    public void createIssueDoc(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateRequest", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.UpdateRequest")
    @ResponseWrapper(localName = "updateRequestResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.UpdateRequestResponse")
    public int updateRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "validateRequestInputAgainstConfig", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ValidateRequestInputAgainstConfig")
    @ResponseWrapper(localName = "validateRequestInputAgainstConfigResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ValidateRequestInputAgainstConfigResponse")
    public void validateRequestInputAgainstConfig(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "releaseAPHold", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ReleaseAPHold")
    @ResponseWrapper(localName = "releaseAPHoldResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ReleaseAPHoldResponse")
    public int releaseAPHold(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "storeDocuments", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.StoreDocuments")
    @ResponseWrapper(localName = "storeDocumentsResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.StoreDocumentsResponse")
    public void storeDocuments(
        @WebParam(name = "arg0", targetNamespace = "")
        List<FileUpload> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveRequest", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.SaveRequest")
    @ResponseWrapper(localName = "saveRequestResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.SaveRequestResponse")
    public int saveRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.imc.business.logic.service.MoneyCodeDetailsDTO
     */
    @WebMethod(operationName = "GetMoneyCodeDetails")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetMoneyCodeDetails", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetMoneyCodeDetails")
    @ResponseWrapper(localName = "GetMoneyCodeDetailsResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetMoneyCodeDetailsResponse")
    public MoneyCodeDetailsDTO getMoneyCodeDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.business.logic.service.Requesttypes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRequestType", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetRequestType")
    @ResponseWrapper(localName = "getRequestTypeResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetRequestTypeResponse")
    public Requesttypes getRequestType(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.business.logic.service.Requests
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRequest", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetRequest")
    @ResponseWrapper(localName = "getRequestResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetRequestResponse")
    public Requests getRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "validateIsNotDuplicateRequest", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ValidateIsNotDuplicateRequest")
    @ResponseWrapper(localName = "validateIsNotDuplicateRequestResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ValidateIsNotDuplicateRequestResponse")
    public void validateIsNotDuplicateRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.business.logic.service.Requests
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toRequest", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ToRequest")
    @ResponseWrapper(localName = "toRequestResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ToRequestResponse")
    public Requests toRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        EfsCheckRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateHasInvoice", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ValidateHasInvoice")
    @ResponseWrapper(localName = "validateHasInvoiceResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.ValidateHasInvoiceResponse")
    public boolean validateHasInvoice(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsersEfsCheckLimit", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetUsersEfsCheckLimit")
    @ResponseWrapper(localName = "getUsersEfsCheckLimitResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.GetUsersEfsCheckLimitResponse")
    public BigDecimal getUsersEfsCheckLimit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendApprovalRequestEmail", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.SendApprovalRequestEmail")
    @ResponseWrapper(localName = "sendApprovalRequestEmailResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.SendApprovalRequestEmailResponse")
    public String sendApprovalRequestEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @param arg8
     */
    @WebMethod
    @RequestWrapper(localName = "createIssuanceTransaction", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.CreateIssuanceTransaction")
    @ResponseWrapper(localName = "createIssuanceTransactionResponse", targetNamespace = "http://ws.logic.business.automation.efs.imc.com/", className = "com.imc.business.logic.service.CreateIssuanceTransactionResponse")
    public void createIssuanceTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        BigDecimal arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

}
