
package com.imc.efs.automation.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EfsAutoService", targetNamespace = "http://webservice.automation.efs.imc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EfsAutoService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.efs.automation.service.EfsMoneyCode
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resumeEfsCheckIssuance", targetNamespace = "http://webservice.automation.efs.imc.com/", className = "com.imc.efs.automation.service.ResumeEfsCheckIssuance")
    @ResponseWrapper(localName = "resumeEfsCheckIssuanceResponse", targetNamespace = "http://webservice.automation.efs.imc.com/", className = "com.imc.efs.automation.service.ResumeEfsCheckIssuanceResponse")
    public EfsMoneyCode resumeEfsCheckIssuance(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.efs.automation.service.EfsMoneyCode
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestEfsCheck", targetNamespace = "http://webservice.automation.efs.imc.com/", className = "com.imc.efs.automation.service.RequestEfsCheck")
    @ResponseWrapper(localName = "requestEfsCheckResponse", targetNamespace = "http://webservice.automation.efs.imc.com/", className = "com.imc.efs.automation.service.RequestEfsCheckResponse")
    public EfsMoneyCode requestEfsCheck(
        @WebParam(name = "arg0", targetNamespace = "")
        EfsCheckRequest arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateCredentials", targetNamespace = "http://webservice.automation.efs.imc.com/", className = "com.imc.efs.automation.service.ValidateCredentials")
    @ResponseWrapper(localName = "validateCredentialsResponse", targetNamespace = "http://webservice.automation.efs.imc.com/", className = "com.imc.efs.automation.service.ValidateCredentialsResponse")
    public boolean validateCredentials(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
