
package com.imc.efs.automation.email.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmailServicePortType", targetNamespace = "http://email.service.imc.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmailServicePortType {


    /**
     * 
     * @param sendEmailRequest
     * @return
     *     returns com.imc.efs.automation.email.service.SendEmailResponse
     */
    @WebMethod(action = "http://impl.service.email.imc.com/sendEmail")
    @WebResult(name = "SendEmailResponse", targetNamespace = "http://service.imc.com/email/data", partName = "sendEmailResponse")
    public SendEmailResponse sendEmail(
        @WebParam(name = "SendEmailRequest", targetNamespace = "http://service.imc.com/email/data", partName = "sendEmailRequest")
        SendEmailRequest sendEmailRequest);

}
