
package service.cards.tch.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import service.cards.tch.com.types.WSCard;
import service.cards.tch.com.types.WSCardSummaryReq;
import service.cards.tch.com.types.WSCarrierInfo;
import service.cards.tch.com.types.WSCreditLimits;
import service.cards.tch.com.types.WSLastMileageSearch;
import service.cards.tch.com.types.WSLocationSearch;
import service.cards.tch.com.types.WSManagedFuel;
import service.cards.tch.com.types.WSManagedFuelDriver;
import service.cards.tch.com.types.WSMoneyCode;
import service.cards.tch.com.types.WSMoneyCodeHistRec;
import service.cards.tch.com.types.WSMoneyCodeSummary;
import service.cards.tch.com.types.WSPolicy;
import service.cards.tch.com.types.WSRegisterCheckAuthorization;
import service.cards.tch.com.types.WSRegisteredCheckAuthorizationResponse;
import service.cards.tch.com.types.WSSmartPayAchTransfer;
import service.cards.tch.com.types.WSSmartPayDriver;
import service.cards.tch.com.types.WSSmartPayScheduledTransferDefinition;
import service.cards.tch.com.types.WSSmartPayTransferAccount;
import service.cards.tch.com.types.WSSmartPayTransferDefinition;
import service.cards.tch.com.types.WSTranRejectSearch;
import service.cards.tch.com.types.WSTransSummary;
import service.cards.tch.com.types.WSVerifySmartPayTransfer;
import service.cards.tch.com.types.arrays.DoubleArray;
import service.cards.tch.com.types.arrays.IntArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSAllCashAvailArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSCardDescriptionArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSCardSummaryArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSCashRecordArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSContractArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSGeoPriceLocationArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSLastMileageArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSLocationArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSLocationGroupArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSMobileSecurityArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSMoneyCodeHistRecArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSMoneyCodeUseArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSPolicyDescriptionArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSProductArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSProductGroupArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSSmartPayScheduledTransferArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSSmartPayTransferAccountArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSSmartPayTransferHistoryArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSTranRejectArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransLocationArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransactionArray;
import service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransactionExtArray;
import service.cards.tch.com.types.arrays.java.lang.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CardManagementEP", targetNamespace = "http://com.tch.cards.service")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    service.cards.tch.com.types.ObjectFactory.class,
    service.cards.tch.com.types.arrays.ObjectFactory.class,
    service.cards.tch.com.types.arrays.com.tch.cards.model.ObjectFactory.class,
    service.cards.tch.com.types.arrays.java.lang.ObjectFactory.class
})
public interface CardManagementEP {


    /**
     * 
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.WSCarrierInfo
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCarrierInfo getCarrierInfo(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public int createNewPolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @param cardNumber
     */
    @WebMethod
    public void deleteOverride(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns service.cards.tch.com.types.WSCard
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCard getCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param driverId
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.WSCard
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCard getCardByDriverId(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "driverId", partName = "driverId")
        String driverId);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns service.cards.tch.com.types.WSSmartPayDriver
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSSmartPayDriver getSmartPayDriver(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param createdSince
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSCardDescriptionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCardDescriptionArray getCardDescriptions(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "createdSince", partName = "createdSince")
        XMLGregorianCalendar createdSince);

    /**
     * 
     * @param begDate
     * @param endDate
     * @param clientId
     * @param cardNumber
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSCashRecordArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCashRecordArray getCashHistory(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param begDate
     * @param endDate
     * @param clientId
     * @param cardNumber
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSCashRecordArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCashRecordArray getPayrollCashHistory(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSContractArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSContractArray getContracts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param cardNumbers
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.DoubleArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public DoubleArray getCurrentCashAmounts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumbers", partName = "cardNumbers")
        StringArray cardNumbers);

    /**
     * 
     * @param cardNumbers
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.DoubleArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public DoubleArray getCurrentPayrollCashAmounts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumbers", partName = "cardNumbers")
        StringArray cardNumbers);

    /**
     * 
     * @param alphaCode
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.WSMoneyCodeHistRec
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeHistRec getMoneyCode(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "alphaCode", partName = "alphaCode")
        String alphaCode);

    /**
     * 
     * @param begDate
     * @param masterContractId
     * @param issued
     * @param endDate
     * @param contractId
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSMoneyCodeUseArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeUseArray getMoneyCodeUse(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "contractId", partName = "contractId")
        int contractId,
        @WebParam(name = "masterContractId", partName = "masterContractId")
        int masterContractId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate,
        @WebParam(name = "issued", partName = "issued")
        boolean issued);

    /**
     * 
     * @param begDate
     * @param endDate
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSMoneyCodeHistRecArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeHistRecArray getMoneyCodes(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param policyNumber
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.WSPolicy
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSPolicy getPolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policyNumber", partName = "policyNumber")
        int policyNumber);

    /**
     * 
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSPolicyDescriptionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSPolicyDescriptionArray getPolicyDescriptions(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSProductGroupArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSProductGroupArray getProductGroups(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSProductArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSProductArray getProducts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param locationIds
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransLocationArray getTransLocations(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "locationIds", partName = "locationIds")
        IntArray locationIds);

    /**
     * 
     * @param policyNum
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransLocationArray getTransLocationsForPolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policyNum", partName = "policyNum")
        int policyNum);

    /**
     * 
     * @param clientId
     * @param cardNum
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransLocationArray getTransLocationsForCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNum", partName = "cardNum")
        String cardNum);

    /**
     * 
     * @param policyNum
     * @param clientId
     * @param cardNum
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSLocationGroupArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSLocationGroupArray getLocationGroups(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNum", partName = "cardNum")
        String cardNum,
        @WebParam(name = "policyNum", partName = "policyNum")
        int policyNum);

    /**
     * 
     * @param begDate
     * @param endDate
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransactionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionArray getTransactions(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param begDate
     * @param endDate
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransactionExtArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionExtArray getTransactionsExt(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param parentClientId
     * @param begDate
     * @param endDate
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransactionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionArray getChildTransactions(
        @WebParam(name = "parentClientId", partName = "parentClientId")
        String parentClientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param parentClientId
     * @param begDate
     * @param endDate
     * @param childCarrierId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSTransactionArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransactionArray getOneCarrierChildTransaction(
        @WebParam(name = "parentClientId", partName = "parentClientId")
        String parentClientId,
        @WebParam(name = "childCarrierId", partName = "childCarrierId")
        int childCarrierId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param amount
     * @param issuedTo
     * @param masterContractId
     * @param feeType
     * @param contractId
     * @param notes
     * @param clientId
     * @param currency
     * @return
     *     returns service.cards.tch.com.types.WSMoneyCode
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCode issueMoneyCode(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "contractId", partName = "contractId")
        int contractId,
        @WebParam(name = "masterContractId", partName = "masterContractId")
        int masterContractId,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "feeType", partName = "feeType")
        boolean feeType,
        @WebParam(name = "issuedTo", partName = "issuedTo")
        String issuedTo,
        @WebParam(name = "notes", partName = "notes")
        String notes,
        @WebParam(name = "currency", partName = "currency")
        String currency);

    /**
     * 
     * @param amount
     * @param payroll
     * @param refNumber
     * @param clientId
     * @param cardNumber
     */
    @WebMethod
    public void loadCash(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "refNumber", partName = "refNumber")
        String refNumber,
        @WebParam(name = "payroll", partName = "payroll")
        boolean payroll);

    /**
     * 
     * @param amount
     * @param payroll
     * @param driverId
     * @param refNumber
     * @param clientId
     */
    @WebMethod
    public void loadCashDriverId(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "driverId", partName = "driverId")
        String driverId,
        @WebParam(name = "amount", partName = "amount")
        double amount,
        @WebParam(name = "refNumber", partName = "refNumber")
        String refNumber,
        @WebParam(name = "payroll", partName = "payroll")
        boolean payroll);

    /**
     * 
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String login(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param clientId
     */
    @WebMethod
    public void logout(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param clientId
     * @param cardNumber
     */
    @WebMethod
    public void removeCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param card
     * @param clientId
     */
    @WebMethod
    public void setCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "card", partName = "card")
        WSCard card);

    /**
     * 
     * @param smartPayDriver
     * @param clientId
     */
    @WebMethod
    public void setSmartPayDriver(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "SmartPayDriver", partName = "SmartPayDriver")
        WSSmartPayDriver smartPayDriver);

    /**
     * 
     * @param policy
     * @param clientId
     */
    @WebMethod
    public void setPolicy(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "policy", partName = "policy")
        WSPolicy policy);

    /**
     * 
     * @param account
     * @param clientId
     */
    @WebMethod
    public void createSmartPayTransferAccount(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "account", partName = "account")
        WSSmartPayTransferDefinition account);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSSmartPayTransferAccountArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSSmartPayTransferAccountArray getSmartPayTransferAccounts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param accountId
     * @param clientId
     */
    @WebMethod
    public void deleteSmartPayTransferAccount(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "accountId", partName = "accountId")
        int accountId);

    /**
     * 
     * @param account
     * @param clientId
     */
    @WebMethod
    public void setSmartPayTransferAccount(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "account", partName = "account")
        WSSmartPayTransferAccount account);

    /**
     * 
     * @param toCard
     * @param fromCard
     * @param clientId
     */
    @WebMethod
    public void transferCard(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "fromCard", partName = "fromCard")
        String fromCard,
        @WebParam(name = "toCard", partName = "toCard")
        String toCard);

    /**
     * 
     * @param clientId
     * @param transferDefinition
     */
    @WebMethod
    public void createSmartPayScheduledTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "transferDefinition", partName = "transferDefinition")
        WSSmartPayScheduledTransferDefinition transferDefinition);

    /**
     * 
     * @param clientId
     * @param cardNumber
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSSmartPayScheduledTransferArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSSmartPayScheduledTransferArray getSmartPayScheduledTransfers(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber);

    /**
     * 
     * @param transferId
     * @param clientId
     */
    @WebMethod
    public void deleteSmartPayScheduledTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "transferId", partName = "transferId")
        int transferId);

    /**
     * 
     * @param moneyCode
     * @param clientId
     */
    @WebMethod
    public void voidMoneyCode(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "moneyCode", partName = "moneyCode")
        String moneyCode);

    /**
     * 
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.java.lang.StringArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public StringArray getPromptTypes(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param begDate
     * @param endDate
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.WSTransSummary
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTransSummary transSummary(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param begDate
     * @param endDate
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.WSMoneyCodeSummary
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMoneyCodeSummary moneyCodeSummary(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "begDate", partName = "begDate")
        XMLGregorianCalendar begDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param request
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSCardSummaryArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCardSummaryArray getCardSummaries(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "request", partName = "request")
        WSCardSummaryReq request);

    /**
     * 
     * @param contractId
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.WSCreditLimits
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSCreditLimits getCreditLimits(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "contractId", partName = "contractId")
        int contractId);

    /**
     * 
     * @param search
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSTranRejectArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSTranRejectArray getTranRejects(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "search", partName = "search")
        WSTranRejectSearch search);

    /**
     * 
     * @param search
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSLastMileageArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSLastMileageArray getLastMileage(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "search", partName = "search")
        WSLastMileageSearch search);

    /**
     * 
     * @param unit
     * @param mileage
     * @param code
     * @param clientId
     */
    @WebMethod
    public void overrideLastMileage(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "unit", partName = "unit")
        String unit,
        @WebParam(name = "code", partName = "code")
        String code,
        @WebParam(name = "mileage", partName = "mileage")
        int mileage);

    /**
     * 
     * @param search
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSLocationArray searchLocation(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "search", partName = "search")
        WSLocationSearch search);

    /**
     * 
     * @param interstates
     * @param states
     * @param clientId
     * @param taxFlag
     * @param cardNumber
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSGeoPriceLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSGeoPriceLocationArray getInterstatePriceLocations(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "interstates", partName = "interstates")
        String interstates,
        @WebParam(name = "states", partName = "states")
        String states,
        @WebParam(name = "taxFlag", partName = "taxFlag")
        boolean taxFlag);

    /**
     * 
     * @param searchRange
     * @param longitude
     * @param latitude
     * @param clientId
     * @param taxFlag
     * @param cardNumber
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSGeoPriceLocationArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSGeoPriceLocationArray getGeoPriceLocations(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "latitude", partName = "latitude")
        String latitude,
        @WebParam(name = "longitude", partName = "longitude")
        String longitude,
        @WebParam(name = "searchRange", partName = "searchRange")
        String searchRange,
        @WebParam(name = "taxFlag", partName = "taxFlag")
        boolean taxFlag);

    /**
     * 
     * @param code
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "valid", partName = "valid")
    public boolean verifyUser(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "code", partName = "code")
        String code);

    /**
     * 
     * @param transfer
     * @param clientId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "transferId", partName = "transferId")
    public int doSmartPayAchTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "transfer", partName = "transfer")
        WSSmartPayAchTransfer transfer);

    /**
     * 
     * @param amounts
     * @param clientId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "successful", partName = "successful")
    public boolean verifySmartPayTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "amounts", partName = "amounts")
        WSVerifySmartPayTransfer amounts);

    /**
     * 
     * @param count
     * @param clientId
     * @param cardNumber
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSSmartPayTransferHistoryArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSSmartPayTransferHistoryArray smartPayTransferHistory(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "count", partName = "count")
        int count);

    /**
     * 
     * @param ppdDetailId
     * @param clientId
     */
    @WebMethod
    public void cancelPendingTransfer(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "ppdDetailId", partName = "ppdDetailId")
        long ppdDetailId);

    /**
     * 
     * @param application
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSMobileSecurityArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSMobileSecurityArray getMobileRoles(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "application", partName = "application")
        String application);

    /**
     * 
     * @param passwd
     * @param carrierId
     * @param userId
     * @return
     *     returns service.cards.tch.com.types.arrays.java.lang.StringArray
     */
    @WebMethod
    @WebResult(name = "ivrRoles", partName = "ivrRoles")
    public StringArray ivrLogin(
        @WebParam(name = "carrierId", partName = "carrierId")
        String carrierId,
        @WebParam(name = "passwd", partName = "passwd")
        String passwd,
        @WebParam(name = "userId", partName = "userId")
        String userId);

    /**
     * 
     * @param managedFuel
     * @param clientId
     */
    @WebMethod
    public void managedFuelAction(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "managedFuel", partName = "managedFuel")
        WSManagedFuel managedFuel);

    /**
     * 
     * @param managedFuelDriver
     * @param clientId
     */
    @WebMethod
    public void managedFuelDriverAction(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "managedFuelDriver", partName = "managedFuelDriver")
        WSManagedFuelDriver managedFuelDriver);

    /**
     * 
     * @param cardNumbers
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.arrays.com.tch.cards.model.WSAllCashAvailArray
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public WSAllCashAvailArray getCurrentCashAllAmounts(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNumbers", partName = "cardNumbers")
        StringArray cardNumbers);

    /**
     * 
     * @param registerCheckAuthorizaiton
     * @param clientId
     * @return
     *     returns service.cards.tch.com.types.WSRegisteredCheckAuthorizationResponse
     */
    @WebMethod
    @WebResult(name = "response", partName = "response")
    public WSRegisteredCheckAuthorizationResponse registerCheck(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "registerCheckAuthorizaiton", partName = "registerCheckAuthorizaiton")
        WSRegisterCheckAuthorization registerCheckAuthorizaiton);

    /**
     * 
     * @param unitNum
     * @param source
     * @param longitude
     * @param latitude
     * @param clientId
     * @param cardNum
     */
    @WebMethod
    public void registerCardPosition(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId,
        @WebParam(name = "cardNum", partName = "cardNum")
        String cardNum,
        @WebParam(name = "latitude", partName = "latitude")
        String latitude,
        @WebParam(name = "longitude", partName = "longitude")
        String longitude,
        @WebParam(name = "unitNum", partName = "unitNum")
        String unitNum,
        @WebParam(name = "source", partName = "source")
        String source);

    /**
     * 
     * @param clientId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "doesCardPosition", partName = "doesCardPosition")
    public boolean doesCardPosition(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param result
     * @param pin
     * @param carrierId
     * @param driverId
     * @param cardNumber
     */
    @WebMethod
    public void validCard(
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "pin", partName = "pin")
        String pin,
        @WebParam(name = "driverId", partName = "driverId")
        String driverId,
        @WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result")
        Holder<String> result,
        @WebParam(name = "carrierId", mode = WebParam.Mode.OUT, partName = "carrierId")
        Holder<String> carrierId);

    /**
     * 
     * @param clientId
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "serverTime", partName = "serverTime")
    public XMLGregorianCalendar serverTime(
        @WebParam(name = "clientId", partName = "clientId")
        String clientId);

    /**
     * 
     * @param result
     * @param carrierId
     * @param driverId
     * @param cardNumber
     */
    @WebMethod
    public void signupScale(
        @WebParam(name = "cardNumber", partName = "cardNumber")
        String cardNumber,
        @WebParam(name = "driverId", partName = "driverId")
        String driverId,
        @WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result")
        Holder<String> result,
        @WebParam(name = "carrierId", mode = WebParam.Mode.OUT, partName = "carrierId")
        Holder<String> carrierId);

}
