package com.imc.driver.wait.service.entities;

// Generated May 21, 2015 5:06:04 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Billto generated by hbm2java
 */
@Entity
@Table(name = "billto", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "cmpy_no", "code" }),
		@UniqueConstraint(columnNames = "oid") })
public class Billto implements java.io.Serializable {

	private String id;
	private Company company;
	private String code;
	private String name;
	private String addr1;
	private String addr2;
	private String city;
	private String stCode;
	private String zip;
	private String contact;
	private String rem;
	private int ctyNo;
	private Date adate;
	private Date atime;
	private String alogin;
	private Date udate;
	private Date utime;
	private String ulogin;
	private String doccodes;
	private String prtinv;
	private String sumrefer;
	private String sumdate;
	private String verify;
	private String status;
	private String bttType;
	private BigDecimal fuelschg;
	private String fuelflag;
	private String divallow;
	private String accok;
	private String accbtCode;
	private String ediCode;
	private int invqtyeq;
	private String sgleqitem;
	private String sumdocs;
	private String sumsort;
	private String origbyreq;
	private String combfsc;
	private String fscbtCode;
	private String pracmiles;
	private String ediflag;
	private String liveonly;
	private String ldmty;
	private BigDecimal acrudpct;
	private BigDecimal paypct;
	private String reqpcswght;
	private String reqavaldt;
	private String altbtCode;
	private String refflag;
	private String norepo;
	private String pcmver14;
	private String mastinv;
	private String laneimc;
	private String fscloaded;
	private String altbtrate;
	private String rndmeth;
	private String docaudit;
	private String fscdelcalc;
	private String bolreq;
	private String req204;
	private String use210;
	private String lot2lot;
	private String custGroup;
	private String fscrpt;
	private String phone;
	private String altbtonly;
	private String accenotify;
	private String accefrom;
	private String accesubject;
	private String cotton;
	private String fscmeth;
	private String chzbillExcept;
	private String chzbillReason;

	public Billto() {
	}

	public Billto(String id, Company company, String code, String name,
			String addr1, String addr2, String city, String stCode, String zip,
			String contact, String rem, int ctyNo, String alogin,
			String ulogin, String doccodes, String prtinv, String sumrefer,
			String sumdate, String verify, String status, String bttType,
			BigDecimal fuelschg, String fuelflag, String divallow,
			String accok, String accbtCode, String ediCode, int invqtyeq,
			String sgleqitem, String sumdocs, String sumsort, String origbyreq,
			String combfsc, String fscbtCode, String pracmiles, String ediflag,
			String liveonly, String ldmty, BigDecimal acrudpct,
			BigDecimal paypct, String reqpcswght, String reqavaldt,
			String altbtCode, String refflag, String norepo, String pcmver14,
			String mastinv, String laneimc, String fscloaded, String altbtrate,
			String rndmeth, String docaudit, String fscdelcalc, String bolreq,
			String req204, String use210, String lot2lot, String custGroup,
			String fscrpt, String phone, String altbtonly, String accenotify,
			String accefrom, String accesubject, String cotton, String fscmeth,
			String chzbillExcept, String chzbillReason) {
		this.id = id;
		this.company = company;
		this.code = code;
		this.name = name;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.city = city;
		this.stCode = stCode;
		this.zip = zip;
		this.contact = contact;
		this.rem = rem;
		this.ctyNo = ctyNo;
		this.alogin = alogin;
		this.ulogin = ulogin;
		this.doccodes = doccodes;
		this.prtinv = prtinv;
		this.sumrefer = sumrefer;
		this.sumdate = sumdate;
		this.verify = verify;
		this.status = status;
		this.bttType = bttType;
		this.fuelschg = fuelschg;
		this.fuelflag = fuelflag;
		this.divallow = divallow;
		this.accok = accok;
		this.accbtCode = accbtCode;
		this.ediCode = ediCode;
		this.invqtyeq = invqtyeq;
		this.sgleqitem = sgleqitem;
		this.sumdocs = sumdocs;
		this.sumsort = sumsort;
		this.origbyreq = origbyreq;
		this.combfsc = combfsc;
		this.fscbtCode = fscbtCode;
		this.pracmiles = pracmiles;
		this.ediflag = ediflag;
		this.liveonly = liveonly;
		this.ldmty = ldmty;
		this.acrudpct = acrudpct;
		this.paypct = paypct;
		this.reqpcswght = reqpcswght;
		this.reqavaldt = reqavaldt;
		this.altbtCode = altbtCode;
		this.refflag = refflag;
		this.norepo = norepo;
		this.pcmver14 = pcmver14;
		this.mastinv = mastinv;
		this.laneimc = laneimc;
		this.fscloaded = fscloaded;
		this.altbtrate = altbtrate;
		this.rndmeth = rndmeth;
		this.docaudit = docaudit;
		this.fscdelcalc = fscdelcalc;
		this.bolreq = bolreq;
		this.req204 = req204;
		this.use210 = use210;
		this.lot2lot = lot2lot;
		this.custGroup = custGroup;
		this.fscrpt = fscrpt;
		this.phone = phone;
		this.altbtonly = altbtonly;
		this.accenotify = accenotify;
		this.accefrom = accefrom;
		this.accesubject = accesubject;
		this.cotton = cotton;
		this.fscmeth = fscmeth;
		this.chzbillExcept = chzbillExcept;
		this.chzbillReason = chzbillReason;
	}

	public Billto(String id, Company company, String code, String name,
			String addr1, String addr2, String city, String stCode, String zip,
			String contact, String rem, int ctyNo, Date adate, Date atime,
			String alogin, Date udate, Date utime, String ulogin,
			String doccodes, String prtinv, String sumrefer, String sumdate,
			String verify, String status, String bttType, BigDecimal fuelschg,
			String fuelflag, String divallow, String accok, String accbtCode,
			String ediCode, int invqtyeq, String sgleqitem, String sumdocs,
			String sumsort, String origbyreq, String combfsc, String fscbtCode,
			String pracmiles, String ediflag, String liveonly, String ldmty,
			BigDecimal acrudpct, BigDecimal paypct, String reqpcswght,
			String reqavaldt, String altbtCode, String refflag, String norepo,
			String pcmver14, String mastinv, String laneimc, String fscloaded,
			String altbtrate, String rndmeth, String docaudit,
			String fscdelcalc, String bolreq, String req204, String use210,
			String lot2lot, String custGroup, String fscrpt, String phone,
			String altbtonly, String accenotify, String accefrom,
			String accesubject, String cotton, String fscmeth,
			String chzbillExcept, String chzbillReason) {
		this.id = id;
		this.company = company;
		this.code = code;
		this.name = name;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.city = city;
		this.stCode = stCode;
		this.zip = zip;
		this.contact = contact;
		this.rem = rem;
		this.ctyNo = ctyNo;
		this.adate = adate;
		this.atime = atime;
		this.alogin = alogin;
		this.udate = udate;
		this.utime = utime;
		this.ulogin = ulogin;
		this.doccodes = doccodes;
		this.prtinv = prtinv;
		this.sumrefer = sumrefer;
		this.sumdate = sumdate;
		this.verify = verify;
		this.status = status;
		this.bttType = bttType;
		this.fuelschg = fuelschg;
		this.fuelflag = fuelflag;
		this.divallow = divallow;
		this.accok = accok;
		this.accbtCode = accbtCode;
		this.ediCode = ediCode;
		this.invqtyeq = invqtyeq;
		this.sgleqitem = sgleqitem;
		this.sumdocs = sumdocs;
		this.sumsort = sumsort;
		this.origbyreq = origbyreq;
		this.combfsc = combfsc;
		this.fscbtCode = fscbtCode;
		this.pracmiles = pracmiles;
		this.ediflag = ediflag;
		this.liveonly = liveonly;
		this.ldmty = ldmty;
		this.acrudpct = acrudpct;
		this.paypct = paypct;
		this.reqpcswght = reqpcswght;
		this.reqavaldt = reqavaldt;
		this.altbtCode = altbtCode;
		this.refflag = refflag;
		this.norepo = norepo;
		this.pcmver14 = pcmver14;
		this.mastinv = mastinv;
		this.laneimc = laneimc;
		this.fscloaded = fscloaded;
		this.altbtrate = altbtrate;
		this.rndmeth = rndmeth;
		this.docaudit = docaudit;
		this.fscdelcalc = fscdelcalc;
		this.bolreq = bolreq;
		this.req204 = req204;
		this.use210 = use210;
		this.lot2lot = lot2lot;
		this.custGroup = custGroup;
		this.fscrpt = fscrpt;
		this.phone = phone;
		this.altbtonly = altbtonly;
		this.accenotify = accenotify;
		this.accefrom = accefrom;
		this.accesubject = accesubject;
		this.cotton = cotton;
		this.fscmeth = fscmeth;
		this.chzbillExcept = chzbillExcept;
		this.chzbillReason = chzbillReason;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 16)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cmpy_no", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "code", nullable = false, length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "addr1", nullable = false, length = 30)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "addr2", nullable = false, length = 30)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "city", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "st_code", nullable = false, length = 2)
	public String getStCode() {
		return this.stCode;
	}

	public void setStCode(String stCode) {
		this.stCode = stCode;
	}

	@Column(name = "zip", nullable = false, length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "contact", nullable = false, length = 16)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "rem", nullable = false, length = 65)
	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

	@Column(name = "cty_no", nullable = false)
	public int getCtyNo() {
		return this.ctyNo;
	}

	public void setCtyNo(int ctyNo) {
		this.ctyNo = ctyNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adate", length = 13)
	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "atime", length = 15)
	public Date getAtime() {
		return this.atime;
	}

	public void setAtime(Date atime) {
		this.atime = atime;
	}

	@Column(name = "alogin", nullable = false, length = 8)
	public String getAlogin() {
		return this.alogin;
	}

	public void setAlogin(String alogin) {
		this.alogin = alogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "udate", length = 13)
	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "utime", length = 15)
	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	@Column(name = "ulogin", nullable = false, length = 8)
	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	@Column(name = "doccodes", nullable = false, length = 36)
	public String getDoccodes() {
		return this.doccodes;
	}

	public void setDoccodes(String doccodes) {
		this.doccodes = doccodes;
	}

	@Column(name = "prtinv", nullable = false, length = 1)
	public String getPrtinv() {
		return this.prtinv;
	}

	public void setPrtinv(String prtinv) {
		this.prtinv = prtinv;
	}

	@Column(name = "sumrefer", nullable = false, length = 1)
	public String getSumrefer() {
		return this.sumrefer;
	}

	public void setSumrefer(String sumrefer) {
		this.sumrefer = sumrefer;
	}

	@Column(name = "sumdate", nullable = false, length = 1)
	public String getSumdate() {
		return this.sumdate;
	}

	public void setSumdate(String sumdate) {
		this.sumdate = sumdate;
	}

	@Column(name = "verify", nullable = false, length = 1)
	public String getVerify() {
		return this.verify;
	}

	public void setVerify(String verify) {
		this.verify = verify;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "btt_type", nullable = false, length = 3)
	public String getBttType() {
		return this.bttType;
	}

	public void setBttType(String bttType) {
		this.bttType = bttType;
	}

	@Column(name = "fuelschg", nullable = false, precision = 16)
	public BigDecimal getFuelschg() {
		return this.fuelschg;
	}

	public void setFuelschg(BigDecimal fuelschg) {
		this.fuelschg = fuelschg;
	}

	@Column(name = "fuelflag", nullable = false, length = 1)
	public String getFuelflag() {
		return this.fuelflag;
	}

	public void setFuelflag(String fuelflag) {
		this.fuelflag = fuelflag;
	}

	@Column(name = "divallow", nullable = false, length = 40)
	public String getDivallow() {
		return this.divallow;
	}

	public void setDivallow(String divallow) {
		this.divallow = divallow;
	}

	@Column(name = "accok", nullable = false, length = 1)
	public String getAccok() {
		return this.accok;
	}

	public void setAccok(String accok) {
		this.accok = accok;
	}

	@Column(name = "accbt_code", nullable = false, length = 6)
	public String getAccbtCode() {
		return this.accbtCode;
	}

	public void setAccbtCode(String accbtCode) {
		this.accbtCode = accbtCode;
	}

	@Column(name = "edi_code", nullable = false, length = 6)
	public String getEdiCode() {
		return this.ediCode;
	}

	public void setEdiCode(String ediCode) {
		this.ediCode = ediCode;
	}

	@Column(name = "invqtyeq", nullable = false)
	public int getInvqtyeq() {
		return this.invqtyeq;
	}

	public void setInvqtyeq(int invqtyeq) {
		this.invqtyeq = invqtyeq;
	}

	@Column(name = "sgleqitem", nullable = false, length = 1)
	public String getSgleqitem() {
		return this.sgleqitem;
	}

	public void setSgleqitem(String sgleqitem) {
		this.sgleqitem = sgleqitem;
	}

	@Column(name = "sumdocs", nullable = false, length = 25)
	public String getSumdocs() {
		return this.sumdocs;
	}

	public void setSumdocs(String sumdocs) {
		this.sumdocs = sumdocs;
	}

	@Column(name = "sumsort", nullable = false, length = 1)
	public String getSumsort() {
		return this.sumsort;
	}

	public void setSumsort(String sumsort) {
		this.sumsort = sumsort;
	}

	@Column(name = "origbyreq", nullable = false, length = 1)
	public String getOrigbyreq() {
		return this.origbyreq;
	}

	public void setOrigbyreq(String origbyreq) {
		this.origbyreq = origbyreq;
	}

	@Column(name = "combfsc", nullable = false, length = 1)
	public String getCombfsc() {
		return this.combfsc;
	}

	public void setCombfsc(String combfsc) {
		this.combfsc = combfsc;
	}

	@Column(name = "fscbt_code", nullable = false, length = 6)
	public String getFscbtCode() {
		return this.fscbtCode;
	}

	public void setFscbtCode(String fscbtCode) {
		this.fscbtCode = fscbtCode;
	}

	@Column(name = "pracmiles", nullable = false, length = 1)
	public String getPracmiles() {
		return this.pracmiles;
	}

	public void setPracmiles(String pracmiles) {
		this.pracmiles = pracmiles;
	}

	@Column(name = "ediflag", nullable = false, length = 1)
	public String getEdiflag() {
		return this.ediflag;
	}

	public void setEdiflag(String ediflag) {
		this.ediflag = ediflag;
	}

	@Column(name = "liveonly", nullable = false, length = 1)
	public String getLiveonly() {
		return this.liveonly;
	}

	public void setLiveonly(String liveonly) {
		this.liveonly = liveonly;
	}

	@Column(name = "ldmty", nullable = false, length = 1)
	public String getLdmty() {
		return this.ldmty;
	}

	public void setLdmty(String ldmty) {
		this.ldmty = ldmty;
	}

	@Column(name = "acrudpct", nullable = false, precision = 16)
	public BigDecimal getAcrudpct() {
		return this.acrudpct;
	}

	public void setAcrudpct(BigDecimal acrudpct) {
		this.acrudpct = acrudpct;
	}

	@Column(name = "paypct", nullable = false, precision = 16)
	public BigDecimal getPaypct() {
		return this.paypct;
	}

	public void setPaypct(BigDecimal paypct) {
		this.paypct = paypct;
	}

	@Column(name = "reqpcswght", nullable = false, length = 1)
	public String getReqpcswght() {
		return this.reqpcswght;
	}

	public void setReqpcswght(String reqpcswght) {
		this.reqpcswght = reqpcswght;
	}

	@Column(name = "reqavaldt", nullable = false, length = 1)
	public String getReqavaldt() {
		return this.reqavaldt;
	}

	public void setReqavaldt(String reqavaldt) {
		this.reqavaldt = reqavaldt;
	}

	@Column(name = "altbt_code", nullable = false, length = 6)
	public String getAltbtCode() {
		return this.altbtCode;
	}

	public void setAltbtCode(String altbtCode) {
		this.altbtCode = altbtCode;
	}

	@Column(name = "refflag", nullable = false, length = 1)
	public String getRefflag() {
		return this.refflag;
	}

	public void setRefflag(String refflag) {
		this.refflag = refflag;
	}

	@Column(name = "norepo", nullable = false, length = 1)
	public String getNorepo() {
		return this.norepo;
	}

	public void setNorepo(String norepo) {
		this.norepo = norepo;
	}

	@Column(name = "pcmver14", nullable = false, length = 1)
	public String getPcmver14() {
		return this.pcmver14;
	}

	public void setPcmver14(String pcmver14) {
		this.pcmver14 = pcmver14;
	}

	@Column(name = "mastinv", nullable = false, length = 1)
	public String getMastinv() {
		return this.mastinv;
	}

	public void setMastinv(String mastinv) {
		this.mastinv = mastinv;
	}

	@Column(name = "laneimc", nullable = false, length = 1)
	public String getLaneimc() {
		return this.laneimc;
	}

	public void setLaneimc(String laneimc) {
		this.laneimc = laneimc;
	}

	@Column(name = "fscloaded", nullable = false, length = 1)
	public String getFscloaded() {
		return this.fscloaded;
	}

	public void setFscloaded(String fscloaded) {
		this.fscloaded = fscloaded;
	}

	@Column(name = "altbtrate", nullable = false, length = 1)
	public String getAltbtrate() {
		return this.altbtrate;
	}

	public void setAltbtrate(String altbtrate) {
		this.altbtrate = altbtrate;
	}

	@Column(name = "rndmeth", nullable = false, length = 1)
	public String getRndmeth() {
		return this.rndmeth;
	}

	public void setRndmeth(String rndmeth) {
		this.rndmeth = rndmeth;
	}

	@Column(name = "docaudit", nullable = false, length = 1)
	public String getDocaudit() {
		return this.docaudit;
	}

	public void setDocaudit(String docaudit) {
		this.docaudit = docaudit;
	}

	@Column(name = "fscdelcalc", nullable = false, length = 1)
	public String getFscdelcalc() {
		return this.fscdelcalc;
	}

	public void setFscdelcalc(String fscdelcalc) {
		this.fscdelcalc = fscdelcalc;
	}

	@Column(name = "bolreq", nullable = false, length = 1)
	public String getBolreq() {
		return this.bolreq;
	}

	public void setBolreq(String bolreq) {
		this.bolreq = bolreq;
	}

	@Column(name = "req204", nullable = false, length = 1)
	public String getReq204() {
		return this.req204;
	}

	public void setReq204(String req204) {
		this.req204 = req204;
	}

	@Column(name = "use210", nullable = false, length = 1)
	public String getUse210() {
		return this.use210;
	}

	public void setUse210(String use210) {
		this.use210 = use210;
	}

	@Column(name = "lot2lot", nullable = false, length = 1)
	public String getLot2lot() {
		return this.lot2lot;
	}

	public void setLot2lot(String lot2lot) {
		this.lot2lot = lot2lot;
	}

	@Column(name = "cust_group", nullable = false, length = 10)
	public String getCustGroup() {
		return this.custGroup;
	}

	public void setCustGroup(String custGroup) {
		this.custGroup = custGroup;
	}

	@Column(name = "fscrpt", nullable = false, length = 1)
	public String getFscrpt() {
		return this.fscrpt;
	}

	public void setFscrpt(String fscrpt) {
		this.fscrpt = fscrpt;
	}

	@Column(name = "phone", nullable = false, length = 14)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "altbtonly", nullable = false, length = 1)
	public String getAltbtonly() {
		return this.altbtonly;
	}

	public void setAltbtonly(String altbtonly) {
		this.altbtonly = altbtonly;
	}

	@Column(name = "accenotify", nullable = false, length = 1)
	public String getAccenotify() {
		return this.accenotify;
	}

	public void setAccenotify(String accenotify) {
		this.accenotify = accenotify;
	}

	@Column(name = "accefrom", nullable = false, length = 30)
	public String getAccefrom() {
		return this.accefrom;
	}

	public void setAccefrom(String accefrom) {
		this.accefrom = accefrom;
	}

	@Column(name = "accesubject", nullable = false, length = 30)
	public String getAccesubject() {
		return this.accesubject;
	}

	public void setAccesubject(String accesubject) {
		this.accesubject = accesubject;
	}

	@Column(name = "cotton", nullable = false, length = 1)
	public String getCotton() {
		return this.cotton;
	}

	public void setCotton(String cotton) {
		this.cotton = cotton;
	}

	@Column(name = "fscmeth", nullable = false, length = 1)
	public String getFscmeth() {
		return this.fscmeth;
	}

	public void setFscmeth(String fscmeth) {
		this.fscmeth = fscmeth;
	}

	@Column(name = "chzbill_except", nullable = false, length = 1)
	public String getChzbillExcept() {
		return this.chzbillExcept;
	}

	public void setChzbillExcept(String chzbillExcept) {
		this.chzbillExcept = chzbillExcept;
	}

	@Column(name = "chzbill_reason", nullable = false, length = 128)
	public String getChzbillReason() {
		return this.chzbillReason;
	}

	public void setChzbillReason(String chzbillReason) {
		this.chzbillReason = chzbillReason;
	}

}
