package com.imc.driver.wait.service.entities;

// Generated May 14, 2015 9:45:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Division generated by hbm2java
 */
@Entity
@Table(name = "division", uniqueConstraints = {
// @UniqueConstraint(columnNames = "oid"),
@UniqueConstraint(columnNames = { "cmpy_no", "code" }) })
public class Division implements java.io.Serializable {

	private String id;
	private String code;
	private String rgnCode;
	private String pro;
	private String name;
	private String addr1;
	private String addr2;
	private String city;
	private String stCode;
	private String zip;
	private String phone;
	private String fax;
	private String watts;
	private Date adate;
	private Date atime;
	private String alogin;
	private Date udate;
	private Date utime;
	private String ulogin;
	private int ctyNo;
	private String nextpro;
	private String freeday;
	private String booking;
	private String cutoff;
	private String pickup;
	private String deliver;
	private String rate;
	private String tldp;
	private String dsptype;
	private String dauddocs;
	private String daudemail;
	private String imghost;
	private String daudifreq;
	private String upramp;
	private int cmpyNo;
	private String status;
	private String payprt;
	private String ediemail;
	private String swsEmailContact;
	private String wwwEmailContact;
	private String accEmailContact;
	private String invholdortype;
	private String weight;

	public Division() {
	}

	public Division(String id, String code, String rgnCode, String pro,
			String name, String addr1, String addr2, String city,
			String stCode, String zip, String phone, String fax, String watts,
			String alogin, String ulogin, int ctyNo, String nextpro,
			String freeday, String booking, String cutoff, String pickup,
			String deliver, String rate, String tldp, String dsptype,
			String dauddocs, String daudemail, String imghost,
			String daudifreq, String upramp, int cmpyNo, String status,
			String payprt, String ediemail, String swsEmailContact,
			String wwwEmailContact, String accEmailContact,
			String invholdortype, String weight) {
		this.id = id;
		this.code = code;
		this.rgnCode = rgnCode;
		this.pro = pro;
		this.name = name;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.city = city;
		this.stCode = stCode;
		this.zip = zip;
		this.phone = phone;
		this.fax = fax;
		this.watts = watts;
		this.alogin = alogin;
		this.ulogin = ulogin;
		this.ctyNo = ctyNo;
		this.nextpro = nextpro;
		this.freeday = freeday;
		this.booking = booking;
		this.cutoff = cutoff;
		this.pickup = pickup;
		this.deliver = deliver;
		this.rate = rate;
		this.tldp = tldp;
		this.dsptype = dsptype;
		this.dauddocs = dauddocs;
		this.daudemail = daudemail;
		this.imghost = imghost;
		this.daudifreq = daudifreq;
		this.upramp = upramp;
		this.cmpyNo = cmpyNo;
		this.status = status;
		this.payprt = payprt;
		this.ediemail = ediemail;
		this.swsEmailContact = swsEmailContact;
		this.wwwEmailContact = wwwEmailContact;
		this.accEmailContact = accEmailContact;
		this.invholdortype = invholdortype;
		this.weight = weight;
	}

	public Division(String id, String code, String rgnCode, String pro,
			String name, String addr1, String addr2, String city,
			String stCode, String zip, String phone, String fax, String watts,
			Date adate, Date atime, String alogin, Date udate, Date utime,
			String ulogin, int ctyNo, String nextpro, String freeday,
			String booking, String cutoff, String pickup, String deliver,
			String rate, String tldp, String dsptype, String dauddocs,
			String daudemail, String imghost, String daudifreq, String upramp,
			int cmpyNo, String status, String payprt, String ediemail,
			String swsEmailContact, String wwwEmailContact,
			String accEmailContact, String invholdortype, String weight) {
		this.id = id;
		this.code = code;
		this.rgnCode = rgnCode;
		this.pro = pro;
		this.name = name;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.city = city;
		this.stCode = stCode;
		this.zip = zip;
		this.phone = phone;
		this.fax = fax;
		this.watts = watts;
		this.adate = adate;
		this.atime = atime;
		this.alogin = alogin;
		this.udate = udate;
		this.utime = utime;
		this.ulogin = ulogin;
		this.ctyNo = ctyNo;
		this.nextpro = nextpro;
		this.freeday = freeday;
		this.booking = booking;
		this.cutoff = cutoff;
		this.pickup = pickup;
		this.deliver = deliver;
		this.rate = rate;
		this.tldp = tldp;
		this.dsptype = dsptype;
		this.dauddocs = dauddocs;
		this.daudemail = daudemail;
		this.imghost = imghost;
		this.daudifreq = daudifreq;
		this.upramp = upramp;
		this.cmpyNo = cmpyNo;
		this.status = status;
		this.payprt = payprt;
		this.ediemail = ediemail;
		this.swsEmailContact = swsEmailContact;
		this.wwwEmailContact = wwwEmailContact;
		this.accEmailContact = accEmailContact;
		this.invholdortype = invholdortype;
		this.weight = weight;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 16)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "rgn_code", nullable = false, length = 3)
	public String getRgnCode() {
		return this.rgnCode;
	}

	public void setRgnCode(String rgnCode) {
		this.rgnCode = rgnCode;
	}

	@Column(name = "pro", nullable = false, length = 9)
	public String getPro() {
		return this.pro;
	}

	public void setPro(String pro) {
		this.pro = pro;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "addr1", nullable = false, length = 30)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "addr2", nullable = false, length = 30)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "city", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "st_code", nullable = false, length = 2)
	public String getStCode() {
		return this.stCode;
	}

	public void setStCode(String stCode) {
		this.stCode = stCode;
	}

	@Column(name = "zip", nullable = false, length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "fax", nullable = false, length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "watts", nullable = false, length = 20)
	public String getWatts() {
		return this.watts;
	}

	public void setWatts(String watts) {
		this.watts = watts;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adate", length = 13)
	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "atime", length = 15)
	public Date getAtime() {
		return this.atime;
	}

	public void setAtime(Date atime) {
		this.atime = atime;
	}

	@Column(name = "alogin", nullable = false, length = 8)
	public String getAlogin() {
		return this.alogin;
	}

	public void setAlogin(String alogin) {
		this.alogin = alogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "udate", length = 13)
	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "utime", length = 15)
	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	@Column(name = "ulogin", nullable = false, length = 8)
	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	@Column(name = "cty_no", nullable = false)
	public int getCtyNo() {
		return this.ctyNo;
	}

	public void setCtyNo(int ctyNo) {
		this.ctyNo = ctyNo;
	}

	@Column(name = "nextpro", nullable = false, length = 1)
	public String getNextpro() {
		return this.nextpro;
	}

	public void setNextpro(String nextpro) {
		this.nextpro = nextpro;
	}

	@Column(name = "freeday", nullable = false, length = 1)
	public String getFreeday() {
		return this.freeday;
	}

	public void setFreeday(String freeday) {
		this.freeday = freeday;
	}

	@Column(name = "booking", nullable = false, length = 1)
	public String getBooking() {
		return this.booking;
	}

	public void setBooking(String booking) {
		this.booking = booking;
	}

	@Column(name = "cutoff", nullable = false, length = 1)
	public String getCutoff() {
		return this.cutoff;
	}

	public void setCutoff(String cutoff) {
		this.cutoff = cutoff;
	}

	@Column(name = "pickup", nullable = false, length = 1)
	public String getPickup() {
		return this.pickup;
	}

	public void setPickup(String pickup) {
		this.pickup = pickup;
	}

	@Column(name = "deliver", nullable = false, length = 1)
	public String getDeliver() {
		return this.deliver;
	}

	public void setDeliver(String deliver) {
		this.deliver = deliver;
	}

	@Column(name = "rate", nullable = false, length = 1)
	public String getRate() {
		return this.rate;
	}

	public void setRate(String rate) {
		this.rate = rate;
	}

	@Column(name = "tldp", nullable = false, length = 1)
	public String getTldp() {
		return this.tldp;
	}

	public void setTldp(String tldp) {
		this.tldp = tldp;
	}

	@Column(name = "dsptype", nullable = false, length = 1)
	public String getDsptype() {
		return this.dsptype;
	}

	public void setDsptype(String dsptype) {
		this.dsptype = dsptype;
	}

	@Column(name = "dauddocs", nullable = false, length = 30)
	public String getDauddocs() {
		return this.dauddocs;
	}

	public void setDauddocs(String dauddocs) {
		this.dauddocs = dauddocs;
	}

	@Column(name = "daudemail", nullable = false, length = 127)
	public String getDaudemail() {
		return this.daudemail;
	}

	public void setDaudemail(String daudemail) {
		this.daudemail = daudemail;
	}

	@Column(name = "imghost", nullable = false, length = 5)
	public String getImghost() {
		return this.imghost;
	}

	public void setImghost(String imghost) {
		this.imghost = imghost;
	}

	@Column(name = "daudifreq", nullable = false, length = 30)
	public String getDaudifreq() {
		return this.daudifreq;
	}

	public void setDaudifreq(String daudifreq) {
		this.daudifreq = daudifreq;
	}

	@Column(name = "upramp", nullable = false, length = 5)
	public String getUpramp() {
		return this.upramp;
	}

	public void setUpramp(String upramp) {
		this.upramp = upramp;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "payprt", nullable = false, length = 30)
	public String getPayprt() {
		return this.payprt;
	}

	public void setPayprt(String payprt) {
		this.payprt = payprt;
	}

	@Column(name = "ediemail", nullable = false, length = 127)
	public String getEdiemail() {
		return this.ediemail;
	}

	public void setEdiemail(String ediemail) {
		this.ediemail = ediemail;
	}

	@Column(name = "sws_email_contact", nullable = false, length = 127)
	public String getSwsEmailContact() {
		return this.swsEmailContact;
	}

	public void setSwsEmailContact(String swsEmailContact) {
		this.swsEmailContact = swsEmailContact;
	}

	@Column(name = "www_email_contact", nullable = false, length = 127)
	public String getWwwEmailContact() {
		return this.wwwEmailContact;
	}

	public void setWwwEmailContact(String wwwEmailContact) {
		this.wwwEmailContact = wwwEmailContact;
	}

	@Column(name = "acc_email_contact", nullable = false, length = 127)
	public String getAccEmailContact() {
		return this.accEmailContact;
	}

	public void setAccEmailContact(String accEmailContact) {
		this.accEmailContact = accEmailContact;
	}

	@Column(name = "invholdortype", nullable = false, length = 10)
	public String getInvholdortype() {
		return this.invholdortype;
	}

	public void setInvholdortype(String invholdortype) {
		this.invholdortype = invholdortype;
	}

	@Column(name = "weight", nullable = false, length = 1)
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

}
