package com.imc.driver.wait.service.entities;

// Generated May 14, 2015 9:45:11 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Driver generated by hbm2java
 */
@Entity
@Table(name = "driver", uniqueConstraints = {
// @UniqueConstraint(columnNames = "oid"),
@UniqueConstraint(columnNames = { "cmpy_no", "code" }) })
public class Driver implements java.io.Serializable {

	private String id;
	private String code;
	private String divCode;
	private String type;
	private String subtype;
	private String ownCode;
	private String rehire;
	private Date reinstdt;
	private String name;
	private String addr1;
	private String addr2;
	private String city;
	private String stCode;
	private String zip;
	private String phone;
	private String pager;
	private String mobile;
	private String ssn;
	private String lic;
	private String licst;
	private Date licdt;
	private String endorse;
	private String insur;
	private Date birthdt;
	private Date hiredt;
	private Date termdt;
	private Date physdt;
	private String TCode;
	private String rem;
	private Date upgdt;
	private String tyear;
	private String tmake;
	private String tvin;
	private String tcolor;
	private String ttagst;
	private String ttype;
	private String ttag;
	private String status;
	private int depscore;
	private Date depdt;
	private int predepscr;
	private Date fhwadt;
	private String physdmgins;
	private String contexper;
	private Date leavstdt;
	private Date ttagdt;
	private String sex;
	private String race;
	private String termreason;
	private String efr;
	private Date safnotdt;
	private String termrem1;
	private String termrem2;
	private int ttexper;
	private String fid;
	private String dba;
	private String usrCode;
	private String prepass;
	private Date adate;
	private Date atime;
	private String alogin;
	private Date udate;
	private Date utime;
	private String ulogin;
	private int ctyNo;
	private String rgnCode;
	private BigDecimal pullamt;
	private BigDecimal pctpay;
	private int gemile;
	private BigDecimal rpmempty;
	private BigDecimal rpmloaded;
	private BigDecimal fltpullamt;
	private int fltgemile;
	private BigDecimal fltrpmempty;
	private BigDecimal fltrpmloaded;
	private String zip2zip;
	private String homepark;
	private String postcode;
	private String drpaytype;
	private String email;
	private String ppayCode;
	private String fltppayCode;
	private String pay08;
	private String mytruck;
	private int cmpyNo;
	private String empCode;
	private Date payhiredt;
	private Date waexpdt;
	private String occacc;
	private String uiiapin;
	private String cyanide;
	private Date mytruckdt;
	private Date ctduedt;
	private String twic;
	private Date twicduedt;
	private Date smsysdt;
	private String ttagpgm;
	private String audit;
	private String hex;
	private Date hextduedt;
	private Date ntuexpdt;
	private Date occaccexpdt;
	private String autotrans;
	private String divisionId;
	private Date newpaydt;
	private String acqco;
	private String tirerack;
	private Date tankvehdt;

	public Driver() {
	}

	public Driver(String id, String code, String divCode, String type,
			String subtype, String ownCode, String rehire, String name,
			String addr1, String addr2, String city, String stCode, String zip,
			String phone, String pager, String mobile, String ssn, String lic,
			String licst, String endorse, String insur, String TCode,
			String rem, String tyear, String tmake, String tvin, String tcolor,
			String ttagst, String ttype, String ttag, String status,
			int depscore, int predepscr, String physdmgins, String contexper,
			String sex, String race, String termreason, String efr,
			String termrem1, String termrem2, int ttexper, String fid,
			String dba, String usrCode, String prepass, String alogin,
			String ulogin, int ctyNo, String rgnCode, BigDecimal pullamt,
			BigDecimal pctpay, int gemile, BigDecimal rpmempty,
			BigDecimal rpmloaded, BigDecimal fltpullamt, int fltgemile,
			BigDecimal fltrpmempty, BigDecimal fltrpmloaded, String zip2zip,
			String homepark, String postcode, String drpaytype, String email,
			String ppayCode, String fltppayCode, String pay08, String mytruck,
			int cmpyNo, String empCode, String occacc, String uiiapin,
			String cyanide, String twic, String ttagpgm, String audit,
			String hex, String autotrans, String acqco, String tirerack) {
		this.id = id;
		this.code = code;
		this.divCode = divCode;
		this.type = type;
		this.subtype = subtype;
		this.ownCode = ownCode;
		this.rehire = rehire;
		this.name = name;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.city = city;
		this.stCode = stCode;
		this.zip = zip;
		this.phone = phone;
		this.pager = pager;
		this.mobile = mobile;
		this.ssn = ssn;
		this.lic = lic;
		this.licst = licst;
		this.endorse = endorse;
		this.insur = insur;
		this.TCode = TCode;
		this.rem = rem;
		this.tyear = tyear;
		this.tmake = tmake;
		this.tvin = tvin;
		this.tcolor = tcolor;
		this.ttagst = ttagst;
		this.ttype = ttype;
		this.ttag = ttag;
		this.status = status;
		this.depscore = depscore;
		this.predepscr = predepscr;
		this.physdmgins = physdmgins;
		this.contexper = contexper;
		this.sex = sex;
		this.race = race;
		this.termreason = termreason;
		this.efr = efr;
		this.termrem1 = termrem1;
		this.termrem2 = termrem2;
		this.ttexper = ttexper;
		this.fid = fid;
		this.dba = dba;
		this.usrCode = usrCode;
		this.prepass = prepass;
		this.alogin = alogin;
		this.ulogin = ulogin;
		this.ctyNo = ctyNo;
		this.rgnCode = rgnCode;
		this.pullamt = pullamt;
		this.pctpay = pctpay;
		this.gemile = gemile;
		this.rpmempty = rpmempty;
		this.rpmloaded = rpmloaded;
		this.fltpullamt = fltpullamt;
		this.fltgemile = fltgemile;
		this.fltrpmempty = fltrpmempty;
		this.fltrpmloaded = fltrpmloaded;
		this.zip2zip = zip2zip;
		this.homepark = homepark;
		this.postcode = postcode;
		this.drpaytype = drpaytype;
		this.email = email;
		this.ppayCode = ppayCode;
		this.fltppayCode = fltppayCode;
		this.pay08 = pay08;
		this.mytruck = mytruck;
		this.cmpyNo = cmpyNo;
		this.empCode = empCode;
		this.occacc = occacc;
		this.uiiapin = uiiapin;
		this.cyanide = cyanide;
		this.twic = twic;
		this.ttagpgm = ttagpgm;
		this.audit = audit;
		this.hex = hex;
		this.autotrans = autotrans;
		this.acqco = acqco;
		this.tirerack = tirerack;
	}

	public Driver(String id, String code, String divCode, String type,
			String subtype, String ownCode, String rehire, Date reinstdt,
			String name, String addr1, String addr2, String city,
			String stCode, String zip, String phone, String pager,
			String mobile, String ssn, String lic, String licst, Date licdt,
			String endorse, String insur, Date birthdt, Date hiredt,
			Date termdt, Date physdt, String TCode, String rem, Date upgdt,
			String tyear, String tmake, String tvin, String tcolor,
			String ttagst, String ttype, String ttag, String status,
			int depscore, Date depdt, int predepscr, Date fhwadt,
			String physdmgins, String contexper, Date leavstdt, Date ttagdt,
			String sex, String race, String termreason, String efr,
			Date safnotdt, String termrem1, String termrem2, int ttexper,
			String fid, String dba, String usrCode, String prepass, Date adate,
			Date atime, String alogin, Date udate, Date utime, String ulogin,
			int ctyNo, String rgnCode, BigDecimal pullamt, BigDecimal pctpay,
			int gemile, BigDecimal rpmempty, BigDecimal rpmloaded,
			BigDecimal fltpullamt, int fltgemile, BigDecimal fltrpmempty,
			BigDecimal fltrpmloaded, String zip2zip, String homepark,
			String postcode, String drpaytype, String email, String ppayCode,
			String fltppayCode, String pay08, String mytruck, int cmpyNo,
			String empCode, Date payhiredt, Date waexpdt, String occacc,
			String uiiapin, String cyanide, Date mytruckdt, Date ctduedt,
			String twic, Date twicduedt, Date smsysdt, String ttagpgm,
			String audit, String hex, Date hextduedt, Date ntuexpdt,
			Date occaccexpdt, String autotrans, String divisionId,
			Date newpaydt, String acqco, String tirerack, Date tankvehdt) {
		this.id = id;
		this.code = code;
		this.divCode = divCode;
		this.type = type;
		this.subtype = subtype;
		this.ownCode = ownCode;
		this.rehire = rehire;
		this.reinstdt = reinstdt;
		this.name = name;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.city = city;
		this.stCode = stCode;
		this.zip = zip;
		this.phone = phone;
		this.pager = pager;
		this.mobile = mobile;
		this.ssn = ssn;
		this.lic = lic;
		this.licst = licst;
		this.licdt = licdt;
		this.endorse = endorse;
		this.insur = insur;
		this.birthdt = birthdt;
		this.hiredt = hiredt;
		this.termdt = termdt;
		this.physdt = physdt;
		this.TCode = TCode;
		this.rem = rem;
		this.upgdt = upgdt;
		this.tyear = tyear;
		this.tmake = tmake;
		this.tvin = tvin;
		this.tcolor = tcolor;
		this.ttagst = ttagst;
		this.ttype = ttype;
		this.ttag = ttag;
		this.status = status;
		this.depscore = depscore;
		this.depdt = depdt;
		this.predepscr = predepscr;
		this.fhwadt = fhwadt;
		this.physdmgins = physdmgins;
		this.contexper = contexper;
		this.leavstdt = leavstdt;
		this.ttagdt = ttagdt;
		this.sex = sex;
		this.race = race;
		this.termreason = termreason;
		this.efr = efr;
		this.safnotdt = safnotdt;
		this.termrem1 = termrem1;
		this.termrem2 = termrem2;
		this.ttexper = ttexper;
		this.fid = fid;
		this.dba = dba;
		this.usrCode = usrCode;
		this.prepass = prepass;
		this.adate = adate;
		this.atime = atime;
		this.alogin = alogin;
		this.udate = udate;
		this.utime = utime;
		this.ulogin = ulogin;
		this.ctyNo = ctyNo;
		this.rgnCode = rgnCode;
		this.pullamt = pullamt;
		this.pctpay = pctpay;
		this.gemile = gemile;
		this.rpmempty = rpmempty;
		this.rpmloaded = rpmloaded;
		this.fltpullamt = fltpullamt;
		this.fltgemile = fltgemile;
		this.fltrpmempty = fltrpmempty;
		this.fltrpmloaded = fltrpmloaded;
		this.zip2zip = zip2zip;
		this.homepark = homepark;
		this.postcode = postcode;
		this.drpaytype = drpaytype;
		this.email = email;
		this.ppayCode = ppayCode;
		this.fltppayCode = fltppayCode;
		this.pay08 = pay08;
		this.mytruck = mytruck;
		this.cmpyNo = cmpyNo;
		this.empCode = empCode;
		this.payhiredt = payhiredt;
		this.waexpdt = waexpdt;
		this.occacc = occacc;
		this.uiiapin = uiiapin;
		this.cyanide = cyanide;
		this.mytruckdt = mytruckdt;
		this.ctduedt = ctduedt;
		this.twic = twic;
		this.twicduedt = twicduedt;
		this.smsysdt = smsysdt;
		this.ttagpgm = ttagpgm;
		this.audit = audit;
		this.hex = hex;
		this.hextduedt = hextduedt;
		this.ntuexpdt = ntuexpdt;
		this.occaccexpdt = occaccexpdt;
		this.autotrans = autotrans;
		this.divisionId = divisionId;
		this.newpaydt = newpaydt;
		this.acqco = acqco;
		this.tirerack = tirerack;
		this.tankvehdt = tankvehdt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 16)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "div_code", nullable = false, length = 2)
	public String getDivCode() {
		return this.divCode;
	}

	public void setDivCode(String divCode) {
		this.divCode = divCode;
	}

	@Column(name = "type", nullable = false, length = 1)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "subtype", nullable = false, length = 1)
	public String getSubtype() {
		return this.subtype;
	}

	public void setSubtype(String subtype) {
		this.subtype = subtype;
	}

	@Column(name = "own_code", nullable = false, length = 6)
	public String getOwnCode() {
		return this.ownCode;
	}

	public void setOwnCode(String ownCode) {
		this.ownCode = ownCode;
	}

	@Column(name = "rehire", nullable = false, length = 1)
	public String getRehire() {
		return this.rehire;
	}

	public void setRehire(String rehire) {
		this.rehire = rehire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reinstdt", length = 13)
	public Date getReinstdt() {
		return this.reinstdt;
	}

	public void setReinstdt(Date reinstdt) {
		this.reinstdt = reinstdt;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "addr1", nullable = false, length = 30)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "addr2", nullable = false, length = 30)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "city", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "st_code", nullable = false, length = 2)
	public String getStCode() {
		return this.stCode;
	}

	public void setStCode(String stCode) {
		this.stCode = stCode;
	}

	@Column(name = "zip", nullable = false, length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "pager", nullable = false, length = 20)
	public String getPager() {
		return this.pager;
	}

	public void setPager(String pager) {
		this.pager = pager;
	}

	@Column(name = "mobile", nullable = false, length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "ssn", nullable = false, length = 9)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Column(name = "lic", nullable = false, length = 25)
	public String getLic() {
		return this.lic;
	}

	public void setLic(String lic) {
		this.lic = lic;
	}

	@Column(name = "licst", nullable = false, length = 2)
	public String getLicst() {
		return this.licst;
	}

	public void setLicst(String licst) {
		this.licst = licst;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "licdt", length = 13)
	public Date getLicdt() {
		return this.licdt;
	}

	public void setLicdt(Date licdt) {
		this.licdt = licdt;
	}

	@Column(name = "endorse", nullable = false, length = 2)
	public String getEndorse() {
		return this.endorse;
	}

	public void setEndorse(String endorse) {
		this.endorse = endorse;
	}

	@Column(name = "insur", nullable = false, length = 30)
	public String getInsur() {
		return this.insur;
	}

	public void setInsur(String insur) {
		this.insur = insur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdt", length = 13)
	public Date getBirthdt() {
		return this.birthdt;
	}

	public void setBirthdt(Date birthdt) {
		this.birthdt = birthdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hiredt", length = 13)
	public Date getHiredt() {
		return this.hiredt;
	}

	public void setHiredt(Date hiredt) {
		this.hiredt = hiredt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "termdt", length = 13)
	public Date getTermdt() {
		return this.termdt;
	}

	public void setTermdt(Date termdt) {
		this.termdt = termdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "physdt", length = 13)
	public Date getPhysdt() {
		return this.physdt;
	}

	public void setPhysdt(Date physdt) {
		this.physdt = physdt;
	}

	@Column(name = "t_code", nullable = false, length = 6)
	public String getTCode() {
		return this.TCode;
	}

	public void setTCode(String TCode) {
		this.TCode = TCode;
	}

	@Column(name = "rem", nullable = false, length = 65)
	public String getRem() {
		return this.rem;
	}

	public void setRem(String rem) {
		this.rem = rem;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "upgdt", length = 13)
	public Date getUpgdt() {
		return this.upgdt;
	}

	public void setUpgdt(Date upgdt) {
		this.upgdt = upgdt;
	}

	@Column(name = "tyear", nullable = false, length = 2)
	public String getTyear() {
		return this.tyear;
	}

	public void setTyear(String tyear) {
		this.tyear = tyear;
	}

	@Column(name = "tmake", nullable = false, length = 5)
	public String getTmake() {
		return this.tmake;
	}

	public void setTmake(String tmake) {
		this.tmake = tmake;
	}

	@Column(name = "tvin", nullable = false, length = 25)
	public String getTvin() {
		return this.tvin;
	}

	public void setTvin(String tvin) {
		this.tvin = tvin;
	}

	@Column(name = "tcolor", nullable = false, length = 10)
	public String getTcolor() {
		return this.tcolor;
	}

	public void setTcolor(String tcolor) {
		this.tcolor = tcolor;
	}

	@Column(name = "ttagst", nullable = false, length = 2)
	public String getTtagst() {
		return this.ttagst;
	}

	public void setTtagst(String ttagst) {
		this.ttagst = ttagst;
	}

	@Column(name = "ttype", nullable = false, length = 1)
	public String getTtype() {
		return this.ttype;
	}

	public void setTtype(String ttype) {
		this.ttype = ttype;
	}

	@Column(name = "ttag", nullable = false, length = 15)
	public String getTtag() {
		return this.ttag;
	}

	public void setTtag(String ttag) {
		this.ttag = ttag;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "depscore", nullable = false)
	public int getDepscore() {
		return this.depscore;
	}

	public void setDepscore(int depscore) {
		this.depscore = depscore;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "depdt", length = 13)
	public Date getDepdt() {
		return this.depdt;
	}

	public void setDepdt(Date depdt) {
		this.depdt = depdt;
	}

	@Column(name = "predepscr", nullable = false)
	public int getPredepscr() {
		return this.predepscr;
	}

	public void setPredepscr(int predepscr) {
		this.predepscr = predepscr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fhwadt", length = 13)
	public Date getFhwadt() {
		return this.fhwadt;
	}

	public void setFhwadt(Date fhwadt) {
		this.fhwadt = fhwadt;
	}

	@Column(name = "physdmgins", nullable = false, length = 1)
	public String getPhysdmgins() {
		return this.physdmgins;
	}

	public void setPhysdmgins(String physdmgins) {
		this.physdmgins = physdmgins;
	}

	@Column(name = "contexper", nullable = false, length = 1)
	public String getContexper() {
		return this.contexper;
	}

	public void setContexper(String contexper) {
		this.contexper = contexper;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "leavstdt", length = 13)
	public Date getLeavstdt() {
		return this.leavstdt;
	}

	public void setLeavstdt(Date leavstdt) {
		this.leavstdt = leavstdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ttagdt", length = 13)
	public Date getTtagdt() {
		return this.ttagdt;
	}

	public void setTtagdt(Date ttagdt) {
		this.ttagdt = ttagdt;
	}

	@Column(name = "sex", nullable = false, length = 1)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "race", nullable = false, length = 1)
	public String getRace() {
		return this.race;
	}

	public void setRace(String race) {
		this.race = race;
	}

	@Column(name = "termreason", nullable = false, length = 1)
	public String getTermreason() {
		return this.termreason;
	}

	public void setTermreason(String termreason) {
		this.termreason = termreason;
	}

	@Column(name = "efr", nullable = false, length = 1)
	public String getEfr() {
		return this.efr;
	}

	public void setEfr(String efr) {
		this.efr = efr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "safnotdt", length = 13)
	public Date getSafnotdt() {
		return this.safnotdt;
	}

	public void setSafnotdt(Date safnotdt) {
		this.safnotdt = safnotdt;
	}

	@Column(name = "termrem1", nullable = false, length = 65)
	public String getTermrem1() {
		return this.termrem1;
	}

	public void setTermrem1(String termrem1) {
		this.termrem1 = termrem1;
	}

	@Column(name = "termrem2", nullable = false, length = 65)
	public String getTermrem2() {
		return this.termrem2;
	}

	public void setTermrem2(String termrem2) {
		this.termrem2 = termrem2;
	}

	@Column(name = "ttexper", nullable = false)
	public int getTtexper() {
		return this.ttexper;
	}

	public void setTtexper(int ttexper) {
		this.ttexper = ttexper;
	}

	@Column(name = "fid", nullable = false, length = 11)
	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	@Column(name = "dba", nullable = false, length = 30)
	public String getDba() {
		return this.dba;
	}

	public void setDba(String dba) {
		this.dba = dba;
	}

	@Column(name = "usr_code", nullable = false, length = 8)
	public String getUsrCode() {
		return this.usrCode;
	}

	public void setUsrCode(String usrCode) {
		this.usrCode = usrCode;
	}

	@Column(name = "prepass", nullable = false, length = 1)
	public String getPrepass() {
		return this.prepass;
	}

	public void setPrepass(String prepass) {
		this.prepass = prepass;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adate", length = 13)
	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "atime", length = 15)
	public Date getAtime() {
		return this.atime;
	}

	public void setAtime(Date atime) {
		this.atime = atime;
	}

	@Column(name = "alogin", nullable = false, length = 8)
	public String getAlogin() {
		return this.alogin;
	}

	public void setAlogin(String alogin) {
		this.alogin = alogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "udate", length = 13)
	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "utime", length = 15)
	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	@Column(name = "ulogin", nullable = false, length = 8)
	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	@Column(name = "cty_no", nullable = false)
	public int getCtyNo() {
		return this.ctyNo;
	}

	public void setCtyNo(int ctyNo) {
		this.ctyNo = ctyNo;
	}

	@Column(name = "rgn_code", nullable = false, length = 3)
	public String getRgnCode() {
		return this.rgnCode;
	}

	public void setRgnCode(String rgnCode) {
		this.rgnCode = rgnCode;
	}

	@Column(name = "pullamt", nullable = false, precision = 16)
	public BigDecimal getPullamt() {
		return this.pullamt;
	}

	public void setPullamt(BigDecimal pullamt) {
		this.pullamt = pullamt;
	}

	@Column(name = "pctpay", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPctpay() {
		return this.pctpay;
	}

	public void setPctpay(BigDecimal pctpay) {
		this.pctpay = pctpay;
	}

	@Column(name = "gemile", nullable = false)
	public int getGemile() {
		return this.gemile;
	}

	public void setGemile(int gemile) {
		this.gemile = gemile;
	}

	@Column(name = "rpmempty", nullable = false, precision = 16)
	public BigDecimal getRpmempty() {
		return this.rpmempty;
	}

	public void setRpmempty(BigDecimal rpmempty) {
		this.rpmempty = rpmempty;
	}

	@Column(name = "rpmloaded", nullable = false, precision = 16)
	public BigDecimal getRpmloaded() {
		return this.rpmloaded;
	}

	public void setRpmloaded(BigDecimal rpmloaded) {
		this.rpmloaded = rpmloaded;
	}

	@Column(name = "fltpullamt", nullable = false, precision = 16)
	public BigDecimal getFltpullamt() {
		return this.fltpullamt;
	}

	public void setFltpullamt(BigDecimal fltpullamt) {
		this.fltpullamt = fltpullamt;
	}

	@Column(name = "fltgemile", nullable = false)
	public int getFltgemile() {
		return this.fltgemile;
	}

	public void setFltgemile(int fltgemile) {
		this.fltgemile = fltgemile;
	}

	@Column(name = "fltrpmempty", nullable = false, precision = 16)
	public BigDecimal getFltrpmempty() {
		return this.fltrpmempty;
	}

	public void setFltrpmempty(BigDecimal fltrpmempty) {
		this.fltrpmempty = fltrpmempty;
	}

	@Column(name = "fltrpmloaded", nullable = false, precision = 16)
	public BigDecimal getFltrpmloaded() {
		return this.fltrpmloaded;
	}

	public void setFltrpmloaded(BigDecimal fltrpmloaded) {
		this.fltrpmloaded = fltrpmloaded;
	}

	@Column(name = "zip2zip", nullable = false, length = 1)
	public String getZip2zip() {
		return this.zip2zip;
	}

	public void setZip2zip(String zip2zip) {
		this.zip2zip = zip2zip;
	}

	@Column(name = "homepark", nullable = false, length = 1)
	public String getHomepark() {
		return this.homepark;
	}

	public void setHomepark(String homepark) {
		this.homepark = homepark;
	}

	@Column(name = "postcode", nullable = false, length = 6)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "drpaytype", nullable = false, length = 1)
	public String getDrpaytype() {
		return this.drpaytype;
	}

	public void setDrpaytype(String drpaytype) {
		this.drpaytype = drpaytype;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ppay_code", nullable = false, length = 3)
	public String getPpayCode() {
		return this.ppayCode;
	}

	public void setPpayCode(String ppayCode) {
		this.ppayCode = ppayCode;
	}

	@Column(name = "fltppay_code", nullable = false, length = 3)
	public String getFltppayCode() {
		return this.fltppayCode;
	}

	public void setFltppayCode(String fltppayCode) {
		this.fltppayCode = fltppayCode;
	}

	@Column(name = "pay08", nullable = false, length = 1)
	public String getPay08() {
		return this.pay08;
	}

	public void setPay08(String pay08) {
		this.pay08 = pay08;
	}

	@Column(name = "mytruck", nullable = false, length = 1)
	public String getMytruck() {
		return this.mytruck;
	}

	public void setMytruck(String mytruck) {
		this.mytruck = mytruck;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "emp_code", nullable = false, length = 6)
	public String getEmpCode() {
		return this.empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payhiredt", length = 13)
	public Date getPayhiredt() {
		return this.payhiredt;
	}

	public void setPayhiredt(Date payhiredt) {
		this.payhiredt = payhiredt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "waexpdt", length = 13)
	public Date getWaexpdt() {
		return this.waexpdt;
	}

	public void setWaexpdt(Date waexpdt) {
		this.waexpdt = waexpdt;
	}

	@Column(name = "occacc", nullable = false, length = 1)
	public String getOccacc() {
		return this.occacc;
	}

	public void setOccacc(String occacc) {
		this.occacc = occacc;
	}

	@Column(name = "uiiapin", nullable = false, length = 10)
	public String getUiiapin() {
		return this.uiiapin;
	}

	public void setUiiapin(String uiiapin) {
		this.uiiapin = uiiapin;
	}

	@Column(name = "cyanide", nullable = false, length = 1)
	public String getCyanide() {
		return this.cyanide;
	}

	public void setCyanide(String cyanide) {
		this.cyanide = cyanide;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "mytruckdt", length = 13)
	public Date getMytruckdt() {
		return this.mytruckdt;
	}

	public void setMytruckdt(Date mytruckdt) {
		this.mytruckdt = mytruckdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ctduedt", length = 13)
	public Date getCtduedt() {
		return this.ctduedt;
	}

	public void setCtduedt(Date ctduedt) {
		this.ctduedt = ctduedt;
	}

	@Column(name = "twic", nullable = false, length = 1)
	public String getTwic() {
		return this.twic;
	}

	public void setTwic(String twic) {
		this.twic = twic;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "twicduedt", length = 13)
	public Date getTwicduedt() {
		return this.twicduedt;
	}

	public void setTwicduedt(Date twicduedt) {
		this.twicduedt = twicduedt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "smsysdt", length = 13)
	public Date getSmsysdt() {
		return this.smsysdt;
	}

	public void setSmsysdt(Date smsysdt) {
		this.smsysdt = smsysdt;
	}

	@Column(name = "ttagpgm", nullable = false, length = 1)
	public String getTtagpgm() {
		return this.ttagpgm;
	}

	public void setTtagpgm(String ttagpgm) {
		this.ttagpgm = ttagpgm;
	}

	@Column(name = "audit", nullable = false, length = 1)
	public String getAudit() {
		return this.audit;
	}

	public void setAudit(String audit) {
		this.audit = audit;
	}

	@Column(name = "hex", nullable = false, length = 1)
	public String getHex() {
		return this.hex;
	}

	public void setHex(String hex) {
		this.hex = hex;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hextduedt", length = 13)
	public Date getHextduedt() {
		return this.hextduedt;
	}

	public void setHextduedt(Date hextduedt) {
		this.hextduedt = hextduedt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ntuexpdt", length = 13)
	public Date getNtuexpdt() {
		return this.ntuexpdt;
	}

	public void setNtuexpdt(Date ntuexpdt) {
		this.ntuexpdt = ntuexpdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "occaccexpdt", length = 13)
	public Date getOccaccexpdt() {
		return this.occaccexpdt;
	}

	public void setOccaccexpdt(Date occaccexpdt) {
		this.occaccexpdt = occaccexpdt;
	}

	@Column(name = "autotrans", nullable = false, length = 1)
	public String getAutotrans() {
		return this.autotrans;
	}

	public void setAutotrans(String autotrans) {
		this.autotrans = autotrans;
	}

	@Column(name = "division_id", length = 16)
	public String getDivisionId() {
		return this.divisionId;
	}

	public void setDivisionId(String divisionId) {
		this.divisionId = divisionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "newpaydt", length = 13)
	public Date getNewpaydt() {
		return this.newpaydt;
	}

	public void setNewpaydt(Date newpaydt) {
		this.newpaydt = newpaydt;
	}

	@Column(name = "acqco", nullable = false, length = 2)
	public String getAcqco() {
		return this.acqco;
	}

	public void setAcqco(String acqco) {
		this.acqco = acqco;
	}

	@Column(name = "tirerack", nullable = false, length = 1)
	public String getTirerack() {
		return this.tirerack;
	}

	public void setTirerack(String tirerack) {
		this.tirerack = tirerack;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tankvehdt", length = 13)
	public Date getTankvehdt() {
		return this.tankvehdt;
	}

	public void setTankvehdt(Date tankvehdt) {
		this.tankvehdt = tankvehdt;
	}

}
