package com.imc.driver.wait.service.entities;

// Generated May 26, 2015 10:51:56 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import com.imc.driver.wait.service.hibernate.postgres.StringJsonUserType;

/**
 * Drwait generated by hbm2java
 */
@TypeDefs({ @TypeDef(name = "StringJsonObject", typeClass = StringJsonUserType.class) })
@Entity
@Table(name = "drwait")
public class Drwait implements java.io.Serializable {

	private int id;
	private String lpCode;
	private String drCode;
	private String divCode;
	private String usrCode;
	private int cmpyNo;
	private short status;
	private String approver;
	private Integer exportOrderNo;
	private Integer exportMoveNo;
	private String exportPro;
	private Date exportArrival;
	private Date exportDeparture;
	private Integer importOrderNo;
	private Integer importMoveNo;
	private String importPro;
	private Date importArrival;
	private Date importDeparture;
	private Date confirmedArrival;
	private Date confirmedDeparture;
	private Integer freeMinutes;
	private BigDecimal hourlyRate;
	private String breadcrumbs;
	private String explanation;

	public Drwait() {
	}

	public Drwait(int id, String lpCode, String drCode, String divCode,
			String usrCode, int cmpyNo, short status) {
		this.id = id;
		this.lpCode = lpCode;
		this.drCode = drCode;
		this.divCode = divCode;
		this.usrCode = usrCode;
		this.cmpyNo = cmpyNo;
		this.status = status;
	}

	public Drwait(int id, String lpCode, String drCode, String divCode,
			String usrCode, int cmpyNo, short status, String approver,
			Integer exportOrderNo, Integer exportMoveNo, String exportPro,
			Date exportArrival, Date exportDeparture, Integer importOrderNo,
			Integer importMoveNo, String importPro, Date importArrival,
			Date importDeparture, Date confirmedArrival,
			Date confirmedDeparture, Integer freeMinutes,
			BigDecimal hourlyRate, String breadcrumbs, String explanation) {
		this.id = id;
		this.lpCode = lpCode;
		this.drCode = drCode;
		this.divCode = divCode;
		this.usrCode = usrCode;
		this.cmpyNo = cmpyNo;
		this.status = status;
		this.approver = approver;
		this.exportOrderNo = exportOrderNo;
		this.exportMoveNo = exportMoveNo;
		this.exportPro = exportPro;
		this.exportArrival = exportArrival;
		this.exportDeparture = exportDeparture;
		this.importOrderNo = importOrderNo;
		this.importMoveNo = importMoveNo;
		this.importPro = importPro;
		this.importArrival = importArrival;
		this.importDeparture = importDeparture;
		this.confirmedArrival = confirmedArrival;
		this.confirmedDeparture = confirmedDeparture;
		this.freeMinutes = freeMinutes;
		this.hourlyRate = hourlyRate;
		this.breadcrumbs = breadcrumbs;
		this.explanation = explanation;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "lp_code", nullable = false, length = 6)
	public String getLpCode() {
		return this.lpCode;
	}

	public void setLpCode(String lpCode) {
		this.lpCode = lpCode;
	}

	@Column(name = "dr_code", nullable = false, length = 6)
	public String getDrCode() {
		return this.drCode;
	}

	public void setDrCode(String drCode) {
		this.drCode = drCode;
	}

	@Column(name = "div_code", nullable = false, length = 2)
	public String getDivCode() {
		return this.divCode;
	}

	public void setDivCode(String divCode) {
		this.divCode = divCode;
	}

	@Column(name = "usr_code", nullable = false, length = 8)
	public String getUsrCode() {
		return this.usrCode;
	}

	public void setUsrCode(String usrCode) {
		this.usrCode = usrCode;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "status", nullable = false)
	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@Column(name = "approver", length = 50)
	public String getApprover() {
		return this.approver;
	}

	public void setApprover(String approver) {
		this.approver = approver;
	}

	@Column(name = "export_order_no")
	public Integer getExportOrderNo() {
		return this.exportOrderNo;
	}

	public void setExportOrderNo(Integer exportOrderNo) {
		this.exportOrderNo = exportOrderNo;
	}

	@Column(name = "export_move_no")
	public Integer getExportMoveNo() {
		return this.exportMoveNo;
	}

	public void setExportMoveNo(Integer exportMoveNo) {
		this.exportMoveNo = exportMoveNo;
	}

	@Column(name = "export_pro", length = 11)
	public String getExportPro() {
		return this.exportPro;
	}

	public void setExportPro(String exportPro) {
		this.exportPro = exportPro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "export_arrival", length = 29)
	public Date getExportArrival() {
		return this.exportArrival;
	}

	public void setExportArrival(Date exportArrival) {
		this.exportArrival = exportArrival;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "export_departure", length = 29)
	public Date getExportDeparture() {
		return this.exportDeparture;
	}

	public void setExportDeparture(Date exportDeparture) {
		this.exportDeparture = exportDeparture;
	}

	@Column(name = "import_order_no")
	public Integer getImportOrderNo() {
		return this.importOrderNo;
	}

	public void setImportOrderNo(Integer importOrderNo) {
		this.importOrderNo = importOrderNo;
	}

	@Column(name = "import_move_no")
	public Integer getImportMoveNo() {
		return this.importMoveNo;
	}

	public void setImportMoveNo(Integer importMoveNo) {
		this.importMoveNo = importMoveNo;
	}

	@Column(name = "import_pro", length = 11)
	public String getImportPro() {
		return this.importPro;
	}

	public void setImportPro(String importPro) {
		this.importPro = importPro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "import_arrival", length = 29)
	public Date getImportArrival() {
		return this.importArrival;
	}

	public void setImportArrival(Date importArrival) {
		this.importArrival = importArrival;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "import_departure", length = 29)
	public Date getImportDeparture() {
		return this.importDeparture;
	}

	public void setImportDeparture(Date importDeparture) {
		this.importDeparture = importDeparture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "confirmed_arrival", length = 29)
	public Date getConfirmedArrival() {
		return this.confirmedArrival;
	}

	public void setConfirmedArrival(Date confirmedArrival) {
		this.confirmedArrival = confirmedArrival;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "confirmed_departure", length = 29)
	public Date getConfirmedDeparture() {
		return this.confirmedDeparture;
	}

	public void setConfirmedDeparture(Date confirmedDeparture) {
		this.confirmedDeparture = confirmedDeparture;
	}

	@Column(name = "free_minutes")
	public Integer getFreeMinutes() {
		return this.freeMinutes;
	}

	public void setFreeMinutes(Integer freeMinutes) {
		this.freeMinutes = freeMinutes;
	}

	@Column(name = "hourly_rate", precision = 5)
	public BigDecimal getHourlyRate() {
		return this.hourlyRate;
	}

	public void setHourlyRate(BigDecimal hourlyRate) {
		this.hourlyRate = hourlyRate;
	}

	@Type(type = "StringJsonObject")
	@Column(name = "breadcrumbs")
	public String getBreadcrumbs() {
		return this.breadcrumbs;
	}

	public void setBreadcrumbs(String breadcrumbs) {
		this.breadcrumbs = breadcrumbs;
	}

	@Column(name = "explanation")
	public String getExplanation() {
		return this.explanation;
	}

	public void setExplanation(String explanation) {
		this.explanation = explanation;
	}

}
