package com.imc.driver.wait.service.entities;

// Generated May 26, 2015 10:51:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DrwaitEventQueue generated by hbm2java
 */
@Entity
@Table(name = "drwait_event_queue")
public class DrwaitEventQueue implements java.io.Serializable {

	private int id;
	private int moveNo;
	private String drCode;
	private String usrCode;
	private int cmpyNo;
	private int orNo;
	private String divCode;
	private String pro;
	private short processed;
	private String lpCode;
	private Date wdate;
	private Date wtime;
	private Date warvdate;
	private Date warvtime;
	private Date wdptdate;
	private Date wdpttime;
	private String origOrDest;
	

	public DrwaitEventQueue() {
	}

	public DrwaitEventQueue(int id, int moveNo, String drCode, String usrCode,
			int cmpyNo, int orNo, String divCode, String pro, short processed,
			String lpCode, String origOrDest) {
		this.id = id;
		this.moveNo = moveNo;
		this.drCode = drCode;
		this.usrCode = usrCode;
		this.cmpyNo = cmpyNo;
		this.orNo = orNo;
		this.divCode = divCode;
		this.pro = pro;
		this.processed = processed;
		this.lpCode = lpCode;
		this.origOrDest = origOrDest;
	}

	public DrwaitEventQueue(int id, int moveNo, String drCode, String usrCode,
			int cmpyNo, int orNo, String divCode, String pro, short processed,
			String lpCode, Date wdate, Date wtime, String origOrDest) {
		this.id = id;
		this.moveNo = moveNo;
		this.drCode = drCode;
		this.usrCode = usrCode;
		this.cmpyNo = cmpyNo;
		this.orNo = orNo;
		this.divCode = divCode;
		this.pro = pro;
		this.processed = processed;
		this.lpCode = lpCode;
		this.wdate = wdate;
		this.wtime = wtime;
		this.origOrDest = origOrDest;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "move_no", nullable = false)
	public int getMoveNo() {
		return this.moveNo;
	}

	public void setMoveNo(int moveNo) {
		this.moveNo = moveNo;
	}

	@Column(name = "dr_code", nullable = false, length = 6)
	public String getDrCode() {
		return this.drCode;
	}

	public void setDrCode(String drCode) {
		this.drCode = drCode;
	}

	@Column(name = "usr_code", nullable = false, length = 8)
	public String getUsrCode() {
		return this.usrCode;
	}

	public void setUsrCode(String usrCode) {
		this.usrCode = usrCode;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "or_no", nullable = false)
	public int getOrNo() {
		return this.orNo;
	}

	public void setOrNo(int orNo) {
		this.orNo = orNo;
	}

	@Column(name = "div_code", nullable = false, length = 2)
	public String getDivCode() {
		return this.divCode;
	}

	public void setDivCode(String divCode) {
		this.divCode = divCode;
	}

	@Column(name = "pro", nullable = false, length = 9)
	public String getPro() {
		return this.pro;
	}

	public void setPro(String pro) {
		this.pro = pro;
	}

	@Column(name = "processed", nullable = false)
	public short getProcessed() {
		return this.processed;
	}

	public void setProcessed(short processed) {
		this.processed = processed;
	}

	@Column(name = "lp_code", nullable = false, length = 6)
	public String getLpCode() {
		return this.lpCode;
	}

	public void setLpCode(String lpCode) {
		this.lpCode = lpCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "wdate", length = 13)
	public Date getWdate() {
		return this.wdate;
	}

	public void setWdate(Date wdate) {
		this.wdate = wdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "wtime", length = 15)
	public Date getWtime() {
		return this.wtime;
	}

	public void setWtime(Date wtime) {
		this.wtime = wtime;
	}

	@Column(name = "orig_or_dest", nullable = false, length = 1)
	public String getOrigOrDest() {
		return this.origOrDest;
	}

	public void setOrigOrDest(String origOrDest) {
		this.origOrDest = origOrDest;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "warvdate", length = 13)
	public Date getWarvdate() {
		return warvdate;
	}

	public void setWarvdate(Date warvdate) {
		this.warvdate = warvdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "warvtime", length = 15)
	public Date getWarvtime() {
		return warvtime;
	}

	public void setWarvtime(Date warvtime) {
		this.warvtime = warvtime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "wdptdate", length = 13)
	public Date getWdptdate() {
		return wdptdate;
	}

	public void setWdptdate(Date wdptdate) {
		this.wdptdate = wdptdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "wdpttime", length = 15)
	public Date getWdpttime() {
		return wdpttime;
	}

	public void setWdpttime(Date wdpttime) {
		this.wdpttime = wdpttime;
	}

}
