package com.imc.driver.wait.service.entities;

// Generated May 14, 2015 9:45:11 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.annotations.TypeDefs;

import com.imc.driver.wait.service.hibernate.postgres.StringJsonUserType;

/**
 * Locprof generated by hbm2java
 */
@TypeDefs({ @TypeDef(name = "StringJsonObject", typeClass = StringJsonUserType.class) })
@Entity
@Table(name = "locprof", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"cmpy_no", "code" })
// ,
// @UniqueConstraint(columnNames = "oid")
})
public class Locprof implements java.io.Serializable {

	private String id;
	private int cmpyNo;
	private String code;
	private String name;
	private String addr1;
	private String addr2;
	private String city;
	private String stCode;
	private String zip;
	private String phone;
	private String ext;
	private String contact;
	private String fax;
	private String phone2;
	private String contact2;
	private String type;
	private Date adate;
	private Date atime;
	private String alogin;
	private Date udate;
	private Date utime;
	private String ulogin;
	private int ctyNo;
	private String nrp;
	private String rem1;
	private String rem2;
	private String rem3;
	private String rem4;
	private String rem5;
	private String rem6;
	private String rem7;
	private String rem8;
	private String rem9;
	private String status;
	private String com1;
	private String com2;
	private String bol;
	private String dsp1;
	private String dsp2;
	private String reqeirin;
	private String reqeirout;
	private String scac;
	private String county;
	private String tzone;
	private String dst;
	private Date verifydt;
	private BigDecimal gpslong;
	private BigDecimal gpslat;
	private Date gpsverifydt;
	private String pcmaddr1;
	private String pcmcity;
	private String pcmstCode;
	private String pcmzip;
	private String geodst;
	private String geotzone;
	private Date perdverifydt;
	private String altbtCode;
	private String excludeFromPoolReport;
	private String zoneCode;
	private String trCode;
	private String geofence;

	public Locprof() {
	}

	public Locprof(String id, int cmpyNo, String code, String name,
			String addr1, String addr2, String city, String stCode, String zip,
			String phone, String ext, String contact, String fax,
			String phone2, String contact2, String type, String alogin,
			String ulogin, int ctyNo, String nrp, String rem1, String rem2,
			String rem3, String rem4, String rem5, String rem6, String rem7,
			String rem8, String rem9, String status, String com1, String com2,
			String bol, String dsp1, String dsp2, String reqeirin,
			String reqeirout, String scac, String county, String tzone,
			String dst, BigDecimal gpslong, BigDecimal gpslat, String pcmaddr1,
			String pcmcity, String pcmstCode, String pcmzip, String geodst,
			String geotzone, String altbtCode, String zoneCode, String trCode) {
		this.id = id;
		this.cmpyNo = cmpyNo;
		this.code = code;
		this.name = name;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.city = city;
		this.stCode = stCode;
		this.zip = zip;
		this.phone = phone;
		this.ext = ext;
		this.contact = contact;
		this.fax = fax;
		this.phone2 = phone2;
		this.contact2 = contact2;
		this.type = type;
		this.alogin = alogin;
		this.ulogin = ulogin;
		this.ctyNo = ctyNo;
		this.nrp = nrp;
		this.rem1 = rem1;
		this.rem2 = rem2;
		this.rem3 = rem3;
		this.rem4 = rem4;
		this.rem5 = rem5;
		this.rem6 = rem6;
		this.rem7 = rem7;
		this.rem8 = rem8;
		this.rem9 = rem9;
		this.status = status;
		this.com1 = com1;
		this.com2 = com2;
		this.bol = bol;
		this.dsp1 = dsp1;
		this.dsp2 = dsp2;
		this.reqeirin = reqeirin;
		this.reqeirout = reqeirout;
		this.scac = scac;
		this.county = county;
		this.tzone = tzone;
		this.dst = dst;
		this.gpslong = gpslong;
		this.gpslat = gpslat;
		this.pcmaddr1 = pcmaddr1;
		this.pcmcity = pcmcity;
		this.pcmstCode = pcmstCode;
		this.pcmzip = pcmzip;
		this.geodst = geodst;
		this.geotzone = geotzone;
		this.altbtCode = altbtCode;
		this.zoneCode = zoneCode;
		this.trCode = trCode;
	}

	public Locprof(String id, int cmpyNo, String code, String name,
			String addr1, String addr2, String city, String stCode, String zip,
			String phone, String ext, String contact, String fax,
			String phone2, String contact2, String type, Date adate,
			Date atime, String alogin, Date udate, Date utime, String ulogin,
			int ctyNo, String nrp, String rem1, String rem2, String rem3,
			String rem4, String rem5, String rem6, String rem7, String rem8,
			String rem9, String status, String com1, String com2, String bol,
			String dsp1, String dsp2, String reqeirin, String reqeirout,
			String scac, String county, String tzone, String dst,
			Date verifydt, BigDecimal gpslong, BigDecimal gpslat,
			Date gpsverifydt, String pcmaddr1, String pcmcity,
			String pcmstCode, String pcmzip, String geodst, String geotzone,
			Date perdverifydt, String altbtCode, String excludeFromPoolReport,
			String zoneCode, String trCode, String geofence) {
		this.id = id;
		this.cmpyNo = cmpyNo;
		this.code = code;
		this.name = name;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.city = city;
		this.stCode = stCode;
		this.zip = zip;
		this.phone = phone;
		this.ext = ext;
		this.contact = contact;
		this.fax = fax;
		this.phone2 = phone2;
		this.contact2 = contact2;
		this.type = type;
		this.adate = adate;
		this.atime = atime;
		this.alogin = alogin;
		this.udate = udate;
		this.utime = utime;
		this.ulogin = ulogin;
		this.ctyNo = ctyNo;
		this.nrp = nrp;
		this.rem1 = rem1;
		this.rem2 = rem2;
		this.rem3 = rem3;
		this.rem4 = rem4;
		this.rem5 = rem5;
		this.rem6 = rem6;
		this.rem7 = rem7;
		this.rem8 = rem8;
		this.rem9 = rem9;
		this.status = status;
		this.com1 = com1;
		this.com2 = com2;
		this.bol = bol;
		this.dsp1 = dsp1;
		this.dsp2 = dsp2;
		this.reqeirin = reqeirin;
		this.reqeirout = reqeirout;
		this.scac = scac;
		this.county = county;
		this.tzone = tzone;
		this.dst = dst;
		this.verifydt = verifydt;
		this.gpslong = gpslong;
		this.gpslat = gpslat;
		this.gpsverifydt = gpsverifydt;
		this.pcmaddr1 = pcmaddr1;
		this.pcmcity = pcmcity;
		this.pcmstCode = pcmstCode;
		this.pcmzip = pcmzip;
		this.geodst = geodst;
		this.geotzone = geotzone;
		this.perdverifydt = perdverifydt;
		this.altbtCode = altbtCode;
		this.excludeFromPoolReport = excludeFromPoolReport;
		this.zoneCode = zoneCode;
		this.trCode = trCode;
		this.geofence = geofence;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 16)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "code", nullable = false, length = 6)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "addr1", nullable = false, length = 30)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "addr2", nullable = false, length = 30)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "city", nullable = false, length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "st_code", nullable = false, length = 2)
	public String getStCode() {
		return this.stCode;
	}

	public void setStCode(String stCode) {
		this.stCode = stCode;
	}

	@Column(name = "zip", nullable = false, length = 10)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "phone", nullable = false, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "ext", nullable = false, length = 5)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "contact", nullable = false, length = 20)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "fax", nullable = false, length = 10)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "phone2", nullable = false, length = 10)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "contact2", nullable = false, length = 20)
	public String getContact2() {
		return this.contact2;
	}

	public void setContact2(String contact2) {
		this.contact2 = contact2;
	}

	@Column(name = "type", nullable = false, length = 1)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adate", length = 13)
	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "atime", length = 15)
	public Date getAtime() {
		return this.atime;
	}

	public void setAtime(Date atime) {
		this.atime = atime;
	}

	@Column(name = "alogin", nullable = false, length = 8)
	public String getAlogin() {
		return this.alogin;
	}

	public void setAlogin(String alogin) {
		this.alogin = alogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "udate", length = 13)
	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "utime", length = 15)
	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	@Column(name = "ulogin", nullable = false, length = 8)
	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	@Column(name = "cty_no", nullable = false)
	public int getCtyNo() {
		return this.ctyNo;
	}

	public void setCtyNo(int ctyNo) {
		this.ctyNo = ctyNo;
	}

	@Column(name = "nrp", nullable = false, length = 1)
	public String getNrp() {
		return this.nrp;
	}

	public void setNrp(String nrp) {
		this.nrp = nrp;
	}

	@Column(name = "rem1", nullable = false, length = 78)
	public String getRem1() {
		return this.rem1;
	}

	public void setRem1(String rem1) {
		this.rem1 = rem1;
	}

	@Column(name = "rem2", nullable = false, length = 78)
	public String getRem2() {
		return this.rem2;
	}

	public void setRem2(String rem2) {
		this.rem2 = rem2;
	}

	@Column(name = "rem3", nullable = false, length = 78)
	public String getRem3() {
		return this.rem3;
	}

	public void setRem3(String rem3) {
		this.rem3 = rem3;
	}

	@Column(name = "rem4", nullable = false, length = 78)
	public String getRem4() {
		return this.rem4;
	}

	public void setRem4(String rem4) {
		this.rem4 = rem4;
	}

	@Column(name = "rem5", nullable = false, length = 78)
	public String getRem5() {
		return this.rem5;
	}

	public void setRem5(String rem5) {
		this.rem5 = rem5;
	}

	@Column(name = "rem6", nullable = false, length = 78)
	public String getRem6() {
		return this.rem6;
	}

	public void setRem6(String rem6) {
		this.rem6 = rem6;
	}

	@Column(name = "rem7", nullable = false, length = 78)
	public String getRem7() {
		return this.rem7;
	}

	public void setRem7(String rem7) {
		this.rem7 = rem7;
	}

	@Column(name = "rem8", nullable = false, length = 78)
	public String getRem8() {
		return this.rem8;
	}

	public void setRem8(String rem8) {
		this.rem8 = rem8;
	}

	@Column(name = "rem9", nullable = false, length = 78)
	public String getRem9() {
		return this.rem9;
	}

	public void setRem9(String rem9) {
		this.rem9 = rem9;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "com1", nullable = false, length = 65)
	public String getCom1() {
		return this.com1;
	}

	public void setCom1(String com1) {
		this.com1 = com1;
	}

	@Column(name = "com2", nullable = false, length = 65)
	public String getCom2() {
		return this.com2;
	}

	public void setCom2(String com2) {
		this.com2 = com2;
	}

	@Column(name = "bol", nullable = false, length = 1)
	public String getBol() {
		return this.bol;
	}

	public void setBol(String bol) {
		this.bol = bol;
	}

	@Column(name = "dsp1", nullable = false, length = 78)
	public String getDsp1() {
		return this.dsp1;
	}

	public void setDsp1(String dsp1) {
		this.dsp1 = dsp1;
	}

	@Column(name = "dsp2", nullable = false, length = 78)
	public String getDsp2() {
		return this.dsp2;
	}

	public void setDsp2(String dsp2) {
		this.dsp2 = dsp2;
	}

	@Column(name = "reqeirin", nullable = false, length = 1)
	public String getReqeirin() {
		return this.reqeirin;
	}

	public void setReqeirin(String reqeirin) {
		this.reqeirin = reqeirin;
	}

	@Column(name = "reqeirout", nullable = false, length = 1)
	public String getReqeirout() {
		return this.reqeirout;
	}

	public void setReqeirout(String reqeirout) {
		this.reqeirout = reqeirout;
	}

	@Column(name = "scac", nullable = false, length = 4)
	public String getScac() {
		return this.scac;
	}

	public void setScac(String scac) {
		this.scac = scac;
	}

	@Column(name = "county", nullable = false, length = 30)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "tzone", nullable = false, length = 2)
	public String getTzone() {
		return this.tzone;
	}

	public void setTzone(String tzone) {
		this.tzone = tzone;
	}

	@Column(name = "dst", nullable = false, length = 1)
	public String getDst() {
		return this.dst;
	}

	public void setDst(String dst) {
		this.dst = dst;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "verifydt", length = 13)
	public Date getVerifydt() {
		return this.verifydt;
	}

	public void setVerifydt(Date verifydt) {
		this.verifydt = verifydt;
	}

	@Column(name = "gpslong", nullable = false, precision = 7, scale = 4)
	public BigDecimal getGpslong() {
		return this.gpslong;
	}

	public void setGpslong(BigDecimal gpslong) {
		this.gpslong = gpslong;
	}

	@Column(name = "gpslat", nullable = false, precision = 6, scale = 4)
	public BigDecimal getGpslat() {
		return this.gpslat;
	}

	public void setGpslat(BigDecimal gpslat) {
		this.gpslat = gpslat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "gpsverifydt", length = 13)
	public Date getGpsverifydt() {
		return this.gpsverifydt;
	}

	public void setGpsverifydt(Date gpsverifydt) {
		this.gpsverifydt = gpsverifydt;
	}

	@Column(name = "pcmaddr1", nullable = false, length = 60)
	public String getPcmaddr1() {
		return this.pcmaddr1;
	}

	public void setPcmaddr1(String pcmaddr1) {
		this.pcmaddr1 = pcmaddr1;
	}

	@Column(name = "pcmcity", nullable = false, length = 20)
	public String getPcmcity() {
		return this.pcmcity;
	}

	public void setPcmcity(String pcmcity) {
		this.pcmcity = pcmcity;
	}

	@Column(name = "pcmst_code", nullable = false, length = 2)
	public String getPcmstCode() {
		return this.pcmstCode;
	}

	public void setPcmstCode(String pcmstCode) {
		this.pcmstCode = pcmstCode;
	}

	@Column(name = "pcmzip", nullable = false, length = 10)
	public String getPcmzip() {
		return this.pcmzip;
	}

	public void setPcmzip(String pcmzip) {
		this.pcmzip = pcmzip;
	}

	@Column(name = "geodst", nullable = false, length = 1)
	public String getGeodst() {
		return this.geodst;
	}

	public void setGeodst(String geodst) {
		this.geodst = geodst;
	}

	@Column(name = "geotzone", nullable = false, length = 2)
	public String getGeotzone() {
		return this.geotzone;
	}

	public void setGeotzone(String geotzone) {
		this.geotzone = geotzone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "perdverifydt", length = 13)
	public Date getPerdverifydt() {
		return this.perdverifydt;
	}

	public void setPerdverifydt(Date perdverifydt) {
		this.perdverifydt = perdverifydt;
	}

	@Column(name = "altbt_code", nullable = false, length = 6)
	public String getAltbtCode() {
		return this.altbtCode;
	}

	public void setAltbtCode(String altbtCode) {
		this.altbtCode = altbtCode;
	}

	@Column(name = "exclude_from_pool_report", length = 1)
	public String getExcludeFromPoolReport() {
		return this.excludeFromPoolReport;
	}

	public void setExcludeFromPoolReport(String excludeFromPoolReport) {
		this.excludeFromPoolReport = excludeFromPoolReport;
	}

	@Column(name = "zone_code", nullable = false, length = 6)
	public String getZoneCode() {
		return this.zoneCode;
	}

	public void setZoneCode(String zoneCode) {
		this.zoneCode = zoneCode;
	}

	@Column(name = "tr_code", nullable = false, length = 20)
	public String getTrCode() {
		return this.trCode;
	}

	public void setTrCode(String trCode) {
		this.trCode = trCode;
	}

	@Type(type = "StringJsonObject")
	@Column(name = "geofence")
	public String getGeofence() {
		return this.geofence;
	}

	public void setGeofence(String geofence) {
		this.geofence = geofence;
	}

}
