package com.imc.driver.wait.service.entities;

// Generated May 14, 2015 9:45:11 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mcgps generated by hbm2java
 */
@Entity
@Table(name = "mcgps"
// , uniqueConstraints = @UniqueConstraint(columnNames = "oid")
)
public class Mcgps implements java.io.Serializable {

	private McgpsId id;
	private String mvehCode;
	private Date eventdt;
	private Date eventtmSecs;
	private String mdrvCode;
	private int speed;
	private int heading;
	private int signal;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private String description;
	private String fixtype;
	private String ign;
	private Date adate;
	private Date atime;
	private String alogin;
	private int eventSecs;

	public Mcgps() {
	}

	public Mcgps(McgpsId id, String mvehCode, String mdrvCode, int speed,
			int heading, int signal, BigDecimal latitude, BigDecimal longitude,
			String description, String fixtype, String ign, String alogin,
			int eventSecs) {
		this.id = id;
		this.mvehCode = mvehCode;
		this.mdrvCode = mdrvCode;
		this.speed = speed;
		this.heading = heading;
		this.signal = signal;
		this.latitude = latitude;
		this.longitude = longitude;
		this.description = description;
		this.fixtype = fixtype;
		this.ign = ign;
		this.alogin = alogin;
		this.eventSecs = eventSecs;
	}

	public Mcgps(McgpsId id, String mvehCode, Date eventdt, Date eventtmSecs,
			String mdrvCode, int speed, int heading, int signal,
			BigDecimal latitude, BigDecimal longitude, String description,
			String fixtype, String ign, Date adate, Date atime, String alogin,
			int eventSecs) {
		this.id = id;
		this.mvehCode = mvehCode;
		this.eventdt = eventdt;
		this.eventtmSecs = eventtmSecs;
		this.mdrvCode = mdrvCode;
		this.speed = speed;
		this.heading = heading;
		this.signal = signal;
		this.latitude = latitude;
		this.longitude = longitude;
		this.description = description;
		this.fixtype = fixtype;
		this.ign = ign;
		this.adate = adate;
		this.atime = atime;
		this.alogin = alogin;
		this.eventSecs = eventSecs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cmpyNo", column = @Column(name = "cmpy_no", nullable = false)),
			@AttributeOverride(name = "no", column = @Column(name = "no", nullable = false)) })
	public McgpsId getId() {
		return this.id;
	}

	public void setId(McgpsId id) {
		this.id = id;
	}

	@Column(name = "mveh_code", nullable = false, length = 20)
	public String getMvehCode() {
		return this.mvehCode;
	}

	public void setMvehCode(String mvehCode) {
		this.mvehCode = mvehCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "eventdt", length = 13)
	public Date getEventdt() {
		return this.eventdt;
	}

	public void setEventdt(Date eventdt) {
		this.eventdt = eventdt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "eventtm_secs", length = 15)
	public Date getEventtmSecs() {
		return this.eventtmSecs;
	}

	public void setEventtmSecs(Date eventtmSecs) {
		this.eventtmSecs = eventtmSecs;
	}

	@Column(name = "mdrv_code", nullable = false, length = 10)
	public String getMdrvCode() {
		return this.mdrvCode;
	}

	public void setMdrvCode(String mdrvCode) {
		this.mdrvCode = mdrvCode;
	}

	@Column(name = "speed", nullable = false)
	public int getSpeed() {
		return this.speed;
	}

	public void setSpeed(int speed) {
		this.speed = speed;
	}

	@Column(name = "heading", nullable = false)
	public int getHeading() {
		return this.heading;
	}

	public void setHeading(int heading) {
		this.heading = heading;
	}

	@Column(name = "signal", nullable = false)
	public int getSignal() {
		return this.signal;
	}

	public void setSignal(int signal) {
		this.signal = signal;
	}

	@Column(name = "latitude", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "fixtype", nullable = false, length = 1)
	public String getFixtype() {
		return this.fixtype;
	}

	public void setFixtype(String fixtype) {
		this.fixtype = fixtype;
	}

	@Column(name = "ign", nullable = false, length = 1)
	public String getIgn() {
		return this.ign;
	}

	public void setIgn(String ign) {
		this.ign = ign;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adate", length = 13)
	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "atime", length = 15)
	public Date getAtime() {
		return this.atime;
	}

	public void setAtime(Date atime) {
		this.atime = atime;
	}

	@Column(name = "alogin", nullable = false, length = 8)
	public String getAlogin() {
		return this.alogin;
	}

	public void setAlogin(String alogin) {
		this.alogin = alogin;
	}

	@Column(name = "event_secs", nullable = false)
	public int getEventSecs() {
		return this.eventSecs;
	}

	public void setEventSecs(int eventSecs) {
		this.eventSecs = eventSecs;
	}

}
