package com.imc.driver.wait.service.entities;

// Generated May 14, 2015 9:45:11 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * McgpsId generated by hbm2java
 */
@Embeddable
public class McgpsId implements java.io.Serializable {

	private int cmpyNo;
	private int no;

	public McgpsId() {
	}

	public McgpsId(int cmpyNo, int no) {
		this.cmpyNo = cmpyNo;
		this.no = no;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "no", nullable = false)
	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof McgpsId))
			return false;
		McgpsId castOther = (McgpsId) other;

		return (this.getCmpyNo() == castOther.getCmpyNo())
				&& (this.getNo() == castOther.getNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCmpyNo();
		result = 37 * result + this.getNo();
		return result;
	}

}
