package com.imc.driver.wait.service.entities;

// Generated May 12, 2015 9:29:50 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Move generated by hbm2java
 */
@Entity
@Table(name = "move", uniqueConstraints = {
// @UniqueConstraint(columnNames = "oid"),
@UniqueConstraint(columnNames = { "cmpy_no", "no" }) })
public class Move implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9089533247885171082L;
	private long id;
	private Order order;
	private int cmpyNo;
	private int no;
	private String divCode;
	private String pro;
	private int seq;
	private String type;
	private String status;
	private String drCode;
	private String tlCode;
	private String chCode;
	private String olpCode;
	private String oname;
	private String ocity;
	private String ostCode;
	private String ozip;
	private int octyNo;
	private Date odate;
	private Date otime;
	private String dlpCode;
	private String dname;
	private String dcity;
	private String dstCode;
	private String dzip;
	private int dctyNo;
	private Date ddate;
	private Date dtime;
	private int mapmiles;
	private int paymiles;
	private Date adate;
	private Date atime;
	private String alogin;
	private Date udate;
	private Date utime;
	private String ulogin;
	private String tlchkdig;
	private String chchkdig;
	private BigDecimal payamt;
	private String paytype;
	private String paybonus;
	private BigDecimal acrudamt;
	private String drtype;
	private Date ftaxdate;
	private BigDecimal fscamt;
	private BigDecimal moveamt;
	private Date pdate;
	private Date ptime;
	private BigDecimal fcramt;
	private BigDecimal fcrpct;
	private String TCode;
	private String ok2pay;
	private String imgnmin;
	private String imgnmout;
	private Date paiddate;
	private Date paidtime;
	private Date oappdate;
	private Date oapptime;
	private Date dappdate;
	private Date dapptime;
	private Date odptdate;
	private Date odpttime;
	private Date ddptdate;
	private Date ddpttime;
	private String paymove;
	private Date oarvdate;
	private Date oarvtime;
	private Date darvdate;
	private Date darvtime;
	private int oarvflag;
	private int odptflag;
	private int darvflag;
	private int ddptflag;
	private int tlflag;
	private int chflag;
	private String gpsver;
	private String gpsguide;
	private int gpsshortmiles;
	private int gpspractmiles;
	private BigDecimal ogpslat;
	private BigDecimal ogpslong;
	private BigDecimal dgpslat;
	private BigDecimal dgpslong;
	private String acrudpaytype;
	private String mvstatus;
	private String xmitdrCode;
	private Date xmitdt;
	private Date xmittm;
	private String otzone;
	private String dtzone;
	private BigDecimal newpayamt;
	private BigDecimal newacrudamt;
	private String newfcrmeth;
	private BigDecimal newfcramt;
	private BigDecimal newfcrpct;
	private BigDecimal newfcrrpm;
	private Date perdlfd;
	private Date sturndt;
	private Date sturntm;
	private Date notifydt;
	private Date notifytm;
	private String notifyldmty;
	private String notifysource;
	private String perdlfdsource;
	private String perdlfdflag;
	private String chassisEqmastId;
	private String destLocprofId;
	private String driverId;
	private String origLocprofId;
	private String trailerEqmastId;

	public Move() {
	}

	public Move(long id, Order order, int cmpyNo, int no, String divCode,
			String pro, int seq, String type, String status, String drCode,
			String tlCode, String chCode, String olpCode, String oname,
			String ocity, String ostCode, String ozip, int octyNo,
			String dlpCode, String dname, String dcity, String dstCode,
			String dzip, int dctyNo, int mapmiles, int paymiles, String alogin,
			String ulogin, String tlchkdig, String chchkdig, BigDecimal payamt,
			String paytype, String paybonus, BigDecimal acrudamt,
			String drtype, BigDecimal fscamt, BigDecimal moveamt,
			BigDecimal fcramt, BigDecimal fcrpct, String TCode, String ok2pay,
			String imgnmin, String imgnmout, String paymove, int oarvflag,
			int odptflag, int darvflag, int ddptflag, int tlflag, int chflag,
			String gpsver, String gpsguide, int gpsshortmiles,
			int gpspractmiles, BigDecimal ogpslat, BigDecimal ogpslong,
			BigDecimal dgpslat, BigDecimal dgpslong, String acrudpaytype,
			String mvstatus, String xmitdrCode, String otzone, String dtzone,
			BigDecimal newpayamt, BigDecimal newacrudamt, String newfcrmeth,
			BigDecimal newfcramt, BigDecimal newfcrpct, BigDecimal newfcrrpm,
			String notifyldmty, String notifysource, String perdlfdsource,
			String perdlfdflag) {
		this.id = id;
		this.order = order;
		this.cmpyNo = cmpyNo;
		this.no = no;
		this.divCode = divCode;
		this.pro = pro;
		this.seq = seq;
		this.type = type;
		this.status = status;
		this.drCode = drCode;
		this.tlCode = tlCode;
		this.chCode = chCode;
		this.olpCode = olpCode;
		this.oname = oname;
		this.ocity = ocity;
		this.ostCode = ostCode;
		this.ozip = ozip;
		this.octyNo = octyNo;
		this.dlpCode = dlpCode;
		this.dname = dname;
		this.dcity = dcity;
		this.dstCode = dstCode;
		this.dzip = dzip;
		this.dctyNo = dctyNo;
		this.mapmiles = mapmiles;
		this.paymiles = paymiles;
		this.alogin = alogin;
		this.ulogin = ulogin;
		this.tlchkdig = tlchkdig;
		this.chchkdig = chchkdig;
		this.payamt = payamt;
		this.paytype = paytype;
		this.paybonus = paybonus;
		this.acrudamt = acrudamt;
		this.drtype = drtype;
		this.fscamt = fscamt;
		this.moveamt = moveamt;
		this.fcramt = fcramt;
		this.fcrpct = fcrpct;
		this.TCode = TCode;
		this.ok2pay = ok2pay;
		this.imgnmin = imgnmin;
		this.imgnmout = imgnmout;
		this.paymove = paymove;
		this.oarvflag = oarvflag;
		this.odptflag = odptflag;
		this.darvflag = darvflag;
		this.ddptflag = ddptflag;
		this.tlflag = tlflag;
		this.chflag = chflag;
		this.gpsver = gpsver;
//		this.gpsguide = gpsguide;
		this.gpsshortmiles = gpsshortmiles;
		this.gpspractmiles = gpspractmiles;
		this.ogpslat = ogpslat;
		this.ogpslong = ogpslong;
		this.dgpslat = dgpslat;
		this.dgpslong = dgpslong;
		this.acrudpaytype = acrudpaytype;
		this.mvstatus = mvstatus;
		this.xmitdrCode = xmitdrCode;
		this.otzone = otzone;
		this.dtzone = dtzone;
		this.newpayamt = newpayamt;
		this.newacrudamt = newacrudamt;
		this.newfcrmeth = newfcrmeth;
		this.newfcramt = newfcramt;
		this.newfcrpct = newfcrpct;
		this.newfcrrpm = newfcrrpm;
		this.notifyldmty = notifyldmty;
		this.notifysource = notifysource;
		this.perdlfdsource = perdlfdsource;
		this.perdlfdflag = perdlfdflag;
	}

	public Move(long id, Order order, int cmpyNo, int no, String divCode,
			String pro, int seq, String type, String status, String drCode,
			String tlCode, String chCode, String olpCode, String oname,
			String ocity, String ostCode, String ozip, int octyNo, Date odate,
			Date otime, String dlpCode, String dname, String dcity,
			String dstCode, String dzip, int dctyNo, Date ddate, Date dtime,
			int mapmiles, int paymiles, Date adate, Date atime, String alogin,
			Date udate, Date utime, String ulogin, String tlchkdig,
			String chchkdig, BigDecimal payamt, String paytype,
			String paybonus, BigDecimal acrudamt, String drtype, Date ftaxdate,
			BigDecimal fscamt, BigDecimal moveamt, Date pdate, Date ptime,
			BigDecimal fcramt, BigDecimal fcrpct, String TCode, String ok2pay,
			String imgnmin, String imgnmout, Date paiddate, Date paidtime,
			Date oappdate, Date oapptime, Date dappdate, Date dapptime,
			Date odptdate, Date odpttime, Date ddptdate, Date ddpttime,
			String paymove, Date oarvdate, Date oarvtime, Date darvdate,
			Date darvtime, int oarvflag, int odptflag, int darvflag,
			int ddptflag, int tlflag, int chflag, String gpsver,
			String gpsguide, int gpsshortmiles, int gpspractmiles,
			BigDecimal ogpslat, BigDecimal ogpslong, BigDecimal dgpslat,
			BigDecimal dgpslong, String acrudpaytype, String mvstatus,
			String xmitdrCode, Date xmitdt, Date xmittm, String otzone,
			String dtzone, BigDecimal newpayamt, BigDecimal newacrudamt,
			String newfcrmeth, BigDecimal newfcramt, BigDecimal newfcrpct,
			BigDecimal newfcrrpm, Date perdlfd, Date sturndt, Date sturntm,
			Date notifydt, Date notifytm, String notifyldmty,
			String notifysource, String perdlfdsource, String perdlfdflag,
			String chassisEqmastId, String destLocprofId, String driverId,
			String origLocprofId, String trailerEqmastId) {
		this.id = id;
		this.order = order;
		this.cmpyNo = cmpyNo;
		this.no = no;
		this.divCode = divCode;
		this.pro = pro;
		this.seq = seq;
		this.type = type;
		this.status = status;
		this.drCode = drCode;
		this.tlCode = tlCode;
		this.chCode = chCode;
		this.olpCode = olpCode;
		this.oname = oname;
		this.ocity = ocity;
		this.ostCode = ostCode;
		this.ozip = ozip;
		this.octyNo = octyNo;
		this.odate = odate;
		this.otime = otime;
		this.dlpCode = dlpCode;
		this.dname = dname;
		this.dcity = dcity;
		this.dstCode = dstCode;
		this.dzip = dzip;
		this.dctyNo = dctyNo;
		this.ddate = ddate;
		this.dtime = dtime;
		this.mapmiles = mapmiles;
		this.paymiles = paymiles;
		this.adate = adate;
		this.atime = atime;
		this.alogin = alogin;
		this.udate = udate;
		this.utime = utime;
		this.ulogin = ulogin;
		this.tlchkdig = tlchkdig;
		this.chchkdig = chchkdig;
		this.payamt = payamt;
		this.paytype = paytype;
		this.paybonus = paybonus;
		this.acrudamt = acrudamt;
		this.drtype = drtype;
		this.ftaxdate = ftaxdate;
		this.fscamt = fscamt;
		this.moveamt = moveamt;
		this.pdate = pdate;
		this.ptime = ptime;
		this.fcramt = fcramt;
		this.fcrpct = fcrpct;
		this.TCode = TCode;
		this.ok2pay = ok2pay;
		this.imgnmin = imgnmin;
		this.imgnmout = imgnmout;
		this.paiddate = paiddate;
		this.paidtime = paidtime;
		this.oappdate = oappdate;
		this.oapptime = oapptime;
		this.dappdate = dappdate;
		this.dapptime = dapptime;
		this.odptdate = odptdate;
		this.odpttime = odpttime;
		this.ddptdate = ddptdate;
		this.ddpttime = ddpttime;
		this.paymove = paymove;
		this.oarvdate = oarvdate;
		this.oarvtime = oarvtime;
		this.darvdate = darvdate;
		this.darvtime = darvtime;
		this.oarvflag = oarvflag;
		this.odptflag = odptflag;
		this.darvflag = darvflag;
		this.ddptflag = ddptflag;
		this.tlflag = tlflag;
		this.chflag = chflag;
		this.gpsver = gpsver;
//		this.gpsguide = gpsguide;
		this.gpsshortmiles = gpsshortmiles;
		this.gpspractmiles = gpspractmiles;
		this.ogpslat = ogpslat;
		this.ogpslong = ogpslong;
		this.dgpslat = dgpslat;
		this.dgpslong = dgpslong;
		this.acrudpaytype = acrudpaytype;
		this.mvstatus = mvstatus;
		this.xmitdrCode = xmitdrCode;
		this.xmitdt = xmitdt;
		this.xmittm = xmittm;
		this.otzone = otzone;
		this.dtzone = dtzone;
		this.newpayamt = newpayamt;
		this.newacrudamt = newacrudamt;
		this.newfcrmeth = newfcrmeth;
		this.newfcramt = newfcramt;
		this.newfcrpct = newfcrpct;
		this.newfcrrpm = newfcrrpm;
		this.perdlfd = perdlfd;
		this.sturndt = sturndt;
		this.sturntm = sturntm;
		this.notifydt = notifydt;
		this.notifytm = notifytm;
		this.notifyldmty = notifyldmty;
		this.notifysource = notifysource;
		this.perdlfdsource = perdlfdsource;
		this.perdlfdflag = perdlfdflag;
		this.chassisEqmastId = chassisEqmastId;
		this.destLocprofId = destLocprofId;
		this.driverId = driverId;
		this.origLocprofId = origLocprofId;
		this.trailerEqmastId = trailerEqmastId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "or_no", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "no", nullable = false)
	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	@Column(name = "div_code", nullable = false, length = 2)
	public String getDivCode() {
		return this.divCode;
	}

	public void setDivCode(String divCode) {
		this.divCode = divCode;
	}

	@Column(name = "pro", nullable = false, length = 9)
	public String getPro() {
		return this.pro;
	}

	public void setPro(String pro) {
		this.pro = pro;
	}

	@Column(name = "seq", nullable = false)
	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	@Column(name = "type", nullable = false, length = 1)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "dr_code", nullable = false, length = 6)
	public String getDrCode() {
		return this.drCode;
	}

	public void setDrCode(String drCode) {
		this.drCode = drCode;
	}

	@Column(name = "tl_code", nullable = false, length = 10)
	public String getTlCode() {
		return this.tlCode;
	}

	public void setTlCode(String tlCode) {
		this.tlCode = tlCode;
	}

	@Column(name = "ch_code", nullable = false, length = 10)
	public String getChCode() {
		return this.chCode;
	}

	public void setChCode(String chCode) {
		this.chCode = chCode;
	}

	@Column(name = "olp_code", nullable = false, length = 6)
	public String getOlpCode() {
		return this.olpCode;
	}

	public void setOlpCode(String olpCode) {
		this.olpCode = olpCode;
	}

	@Column(name = "oname", nullable = false, length = 30)
	public String getOname() {
		return this.oname;
	}

	public void setOname(String oname) {
		this.oname = oname;
	}

	@Column(name = "ocity", nullable = false, length = 20)
	public String getOcity() {
		return this.ocity;
	}

	public void setOcity(String ocity) {
		this.ocity = ocity;
	}

	@Column(name = "ost_code", nullable = false, length = 2)
	public String getOstCode() {
		return this.ostCode;
	}

	public void setOstCode(String ostCode) {
		this.ostCode = ostCode;
	}

	@Column(name = "ozip", nullable = false, length = 10)
	public String getOzip() {
		return this.ozip;
	}

	public void setOzip(String ozip) {
		this.ozip = ozip;
	}

	@Column(name = "octy_no", nullable = false)
	public int getOctyNo() {
		return this.octyNo;
	}

	public void setOctyNo(int octyNo) {
		this.octyNo = octyNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "odate", length = 13)
	public Date getOdate() {
		return this.odate;
	}

	public void setOdate(Date odate) {
		this.odate = odate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "otime", length = 15)
	public Date getOtime() {
		return this.otime;
	}

	public void setOtime(Date otime) {
		this.otime = otime;
	}

	@Column(name = "dlp_code", nullable = false, length = 6)
	public String getDlpCode() {
		return this.dlpCode;
	}

	public void setDlpCode(String dlpCode) {
		this.dlpCode = dlpCode;
	}

	@Column(name = "dname", nullable = false, length = 30)
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	@Column(name = "dcity", nullable = false, length = 20)
	public String getDcity() {
		return this.dcity;
	}

	public void setDcity(String dcity) {
		this.dcity = dcity;
	}

	@Column(name = "dst_code", nullable = false, length = 2)
	public String getDstCode() {
		return this.dstCode;
	}

	public void setDstCode(String dstCode) {
		this.dstCode = dstCode;
	}

	@Column(name = "dzip", nullable = false, length = 10)
	public String getDzip() {
		return this.dzip;
	}

	public void setDzip(String dzip) {
		this.dzip = dzip;
	}

	@Column(name = "dcty_no", nullable = false)
	public int getDctyNo() {
		return this.dctyNo;
	}

	public void setDctyNo(int dctyNo) {
		this.dctyNo = dctyNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ddate", length = 13)
	public Date getDdate() {
		return this.ddate;
	}

	public void setDdate(Date ddate) {
		this.ddate = ddate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "dtime", length = 15)
	public Date getDtime() {
		return this.dtime;
	}

	public void setDtime(Date dtime) {
		this.dtime = dtime;
	}

	@Column(name = "mapmiles", nullable = false)
	public int getMapmiles() {
		return this.mapmiles;
	}

	public void setMapmiles(int mapmiles) {
		this.mapmiles = mapmiles;
	}

	@Column(name = "paymiles", nullable = false)
	public int getPaymiles() {
		return this.paymiles;
	}

	public void setPaymiles(int paymiles) {
		this.paymiles = paymiles;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adate", length = 13)
	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "atime", length = 15)
	public Date getAtime() {
		return this.atime;
	}

	public void setAtime(Date atime) {
		this.atime = atime;
	}

	@Column(name = "alogin", nullable = false, length = 8)
	public String getAlogin() {
		return this.alogin;
	}

	public void setAlogin(String alogin) {
		this.alogin = alogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "udate", length = 13)
	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "utime", length = 15)
	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	@Column(name = "ulogin", nullable = false, length = 8)
	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	@Column(name = "tlchkdig", nullable = false, length = 1)
	public String getTlchkdig() {
		return this.tlchkdig;
	}

	public void setTlchkdig(String tlchkdig) {
		this.tlchkdig = tlchkdig;
	}

	@Column(name = "chchkdig", nullable = false, length = 1)
	public String getChchkdig() {
		return this.chchkdig;
	}

	public void setChchkdig(String chchkdig) {
		this.chchkdig = chchkdig;
	}

	@Column(name = "payamt", nullable = false, precision = 16)
	public BigDecimal getPayamt() {
		return this.payamt;
	}

	public void setPayamt(BigDecimal payamt) {
		this.payamt = payamt;
	}

	@Column(name = "paytype", nullable = false, length = 1)
	public String getPaytype() {
		return this.paytype;
	}

	public void setPaytype(String paytype) {
		this.paytype = paytype;
	}

	@Column(name = "paybonus", nullable = false, length = 1)
	public String getPaybonus() {
		return this.paybonus;
	}

	public void setPaybonus(String paybonus) {
		this.paybonus = paybonus;
	}

	@Column(name = "acrudamt", nullable = false, precision = 16)
	public BigDecimal getAcrudamt() {
		return this.acrudamt;
	}

	public void setAcrudamt(BigDecimal acrudamt) {
		this.acrudamt = acrudamt;
	}

	@Column(name = "drtype", nullable = false, length = 1)
	public String getDrtype() {
		return this.drtype;
	}

	public void setDrtype(String drtype) {
		this.drtype = drtype;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ftaxdate", length = 13)
	public Date getFtaxdate() {
		return this.ftaxdate;
	}

	public void setFtaxdate(Date ftaxdate) {
		this.ftaxdate = ftaxdate;
	}

	@Column(name = "fscamt", nullable = false, precision = 16)
	public BigDecimal getFscamt() {
		return this.fscamt;
	}

	public void setFscamt(BigDecimal fscamt) {
		this.fscamt = fscamt;
	}

	@Column(name = "moveamt", nullable = false, precision = 16)
	public BigDecimal getMoveamt() {
		return this.moveamt;
	}

	public void setMoveamt(BigDecimal moveamt) {
		this.moveamt = moveamt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pdate", length = 13)
	public Date getPdate() {
		return this.pdate;
	}

	public void setPdate(Date pdate) {
		this.pdate = pdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ptime", length = 15)
	public Date getPtime() {
		return this.ptime;
	}

	public void setPtime(Date ptime) {
		this.ptime = ptime;
	}

	@Column(name = "fcramt", nullable = false, precision = 16)
	public BigDecimal getFcramt() {
		return this.fcramt;
	}

	public void setFcramt(BigDecimal fcramt) {
		this.fcramt = fcramt;
	}

	@Column(name = "fcrpct", nullable = false, precision = 16)
	public BigDecimal getFcrpct() {
		return this.fcrpct;
	}

	public void setFcrpct(BigDecimal fcrpct) {
		this.fcrpct = fcrpct;
	}

	@Column(name = "t_code", nullable = false, length = 6)
	public String getTCode() {
		return this.TCode;
	}

	public void setTCode(String TCode) {
		this.TCode = TCode;
	}

	@Column(name = "ok2pay", nullable = false, length = 1)
	public String getOk2pay() {
		return this.ok2pay;
	}

	public void setOk2pay(String ok2pay) {
		this.ok2pay = ok2pay;
	}

	@Column(name = "imgnmin", nullable = false, length = 9)
	public String getImgnmin() {
		return this.imgnmin;
	}

	public void setImgnmin(String imgnmin) {
		this.imgnmin = imgnmin;
	}

	@Column(name = "imgnmout", nullable = false, length = 9)
	public String getImgnmout() {
		return this.imgnmout;
	}

	public void setImgnmout(String imgnmout) {
		this.imgnmout = imgnmout;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "paiddate", length = 13)
	public Date getPaiddate() {
		return this.paiddate;
	}

	public void setPaiddate(Date paiddate) {
		this.paiddate = paiddate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "paidtime", length = 15)
	public Date getPaidtime() {
		return this.paidtime;
	}

	public void setPaidtime(Date paidtime) {
		this.paidtime = paidtime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "oappdate", length = 13)
	public Date getOappdate() {
		return this.oappdate;
	}

	public void setOappdate(Date oappdate) {
		this.oappdate = oappdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "oapptime", length = 15)
	public Date getOapptime() {
		return this.oapptime;
	}

	public void setOapptime(Date oapptime) {
		this.oapptime = oapptime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dappdate", length = 13)
	public Date getDappdate() {
		return this.dappdate;
	}

	public void setDappdate(Date dappdate) {
		this.dappdate = dappdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "dapptime", length = 15)
	public Date getDapptime() {
		return this.dapptime;
	}

	public void setDapptime(Date dapptime) {
		this.dapptime = dapptime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "odptdate", length = 13)
	public Date getOdptdate() {
		return this.odptdate;
	}

	public void setOdptdate(Date odptdate) {
		this.odptdate = odptdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "odpttime", length = 15)
	public Date getOdpttime() {
		return this.odpttime;
	}

	public void setOdpttime(Date odpttime) {
		this.odpttime = odpttime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ddptdate", length = 13)
	public Date getDdptdate() {
		return this.ddptdate;
	}

	public void setDdptdate(Date ddptdate) {
		this.ddptdate = ddptdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ddpttime", length = 15)
	public Date getDdpttime() {
		return this.ddpttime;
	}

	public void setDdpttime(Date ddpttime) {
		this.ddpttime = ddpttime;
	}

	@Column(name = "paymove", nullable = false, length = 1)
	public String getPaymove() {
		return this.paymove;
	}

	public void setPaymove(String paymove) {
		this.paymove = paymove;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "oarvdate", length = 13)
	public Date getOarvdate() {
		return this.oarvdate;
	}

	public void setOarvdate(Date oarvdate) {
		this.oarvdate = oarvdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "oarvtime", length = 15)
	public Date getOarvtime() {
		return this.oarvtime;
	}

	public void setOarvtime(Date oarvtime) {
		this.oarvtime = oarvtime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "darvdate", length = 13)
	public Date getDarvdate() {
		return this.darvdate;
	}

	public void setDarvdate(Date darvdate) {
		this.darvdate = darvdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "darvtime", length = 15)
	public Date getDarvtime() {
		return this.darvtime;
	}

	public void setDarvtime(Date darvtime) {
		this.darvtime = darvtime;
	}

	@Column(name = "oarvflag", nullable = false)
	public int getOarvflag() {
		return this.oarvflag;
	}

	public void setOarvflag(int oarvflag) {
		this.oarvflag = oarvflag;
	}

	@Column(name = "odptflag", nullable = false)
	public int getOdptflag() {
		return this.odptflag;
	}

	public void setOdptflag(int odptflag) {
		this.odptflag = odptflag;
	}

	@Column(name = "darvflag", nullable = false)
	public int getDarvflag() {
		return this.darvflag;
	}

	public void setDarvflag(int darvflag) {
		this.darvflag = darvflag;
	}

	@Column(name = "ddptflag", nullable = false)
	public int getDdptflag() {
		return this.ddptflag;
	}

	public void setDdptflag(int ddptflag) {
		this.ddptflag = ddptflag;
	}

	@Column(name = "tlflag", nullable = false)
	public int getTlflag() {
		return this.tlflag;
	}

	public void setTlflag(int tlflag) {
		this.tlflag = tlflag;
	}

	@Column(name = "chflag", nullable = false)
	public int getChflag() {
		return this.chflag;
	}

	public void setChflag(int chflag) {
		this.chflag = chflag;
	}

	@Column(name = "gpsver", nullable = false, length = 5)
	public String getGpsver() {
		return this.gpsver;
	}

	public void setGpsver(String gpsver) {
		this.gpsver = gpsver;
	}

	@Column(name = "gpsguide", nullable = false, length = 7)
	public String getGpsguide() {
		return this.gpsguide;
	}

	public void setGpsguide(String gpsguide) {
		this.gpsguide = gpsguide;
	}

	@Column(name = "gpsshortmiles", nullable = false)
	public int getGpsshortmiles() {
		return this.gpsshortmiles;
	}

	public void setGpsshortmiles(int gpsshortmiles) {
		this.gpsshortmiles = gpsshortmiles;
	}

	@Column(name = "gpspractmiles", nullable = false)
	public int getGpspractmiles() {
		return this.gpspractmiles;
	}

	public void setGpspractmiles(int gpspractmiles) {
		this.gpspractmiles = gpspractmiles;
	}

	@Column(name = "ogpslat", nullable = false, precision = 6, scale = 4)
	public BigDecimal getOgpslat() {
		return this.ogpslat;
	}

	public void setOgpslat(BigDecimal ogpslat) {
		this.ogpslat = ogpslat;
	}

	@Column(name = "ogpslong", nullable = false, precision = 7, scale = 4)
	public BigDecimal getOgpslong() {
		return this.ogpslong;
	}

	public void setOgpslong(BigDecimal ogpslong) {
		this.ogpslong = ogpslong;
	}

	@Column(name = "dgpslat", nullable = false, precision = 6, scale = 4)
	public BigDecimal getDgpslat() {
		return this.dgpslat;
	}

	public void setDgpslat(BigDecimal dgpslat) {
		this.dgpslat = dgpslat;
	}

	@Column(name = "dgpslong", nullable = false, precision = 7, scale = 4)
	public BigDecimal getDgpslong() {
		return this.dgpslong;
	}

	public void setDgpslong(BigDecimal dgpslong) {
		this.dgpslong = dgpslong;
	}

	@Column(name = "acrudpaytype", nullable = false, length = 1)
	public String getAcrudpaytype() {
		return this.acrudpaytype;
	}

	public void setAcrudpaytype(String acrudpaytype) {
		this.acrudpaytype = acrudpaytype;
	}

	@Column(name = "mvstatus", nullable = false, length = 1)
	public String getMvstatus() {
		return this.mvstatus;
	}

	public void setMvstatus(String mvstatus) {
		this.mvstatus = mvstatus;
	}

	@Column(name = "xmitdr_code", nullable = false, length = 6)
	public String getXmitdrCode() {
		return this.xmitdrCode;
	}

	public void setXmitdrCode(String xmitdrCode) {
		this.xmitdrCode = xmitdrCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "xmitdt", length = 13)
	public Date getXmitdt() {
		return this.xmitdt;
	}

	public void setXmitdt(Date xmitdt) {
		this.xmitdt = xmitdt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "xmittm", length = 15)
	public Date getXmittm() {
		return this.xmittm;
	}

	public void setXmittm(Date xmittm) {
		this.xmittm = xmittm;
	}

	@Column(name = "otzone", nullable = false, length = 2)
	public String getOtzone() {
		return this.otzone;
	}

	public void setOtzone(String otzone) {
		this.otzone = otzone;
	}

	@Column(name = "dtzone", nullable = false, length = 2)
	public String getDtzone() {
		return this.dtzone;
	}

	public void setDtzone(String dtzone) {
		this.dtzone = dtzone;
	}

	@Column(name = "newpayamt", nullable = false, precision = 16)
	public BigDecimal getNewpayamt() {
		return this.newpayamt;
	}

	public void setNewpayamt(BigDecimal newpayamt) {
		this.newpayamt = newpayamt;
	}

	@Column(name = "newacrudamt", nullable = false, precision = 16)
	public BigDecimal getNewacrudamt() {
		return this.newacrudamt;
	}

	public void setNewacrudamt(BigDecimal newacrudamt) {
		this.newacrudamt = newacrudamt;
	}

	@Column(name = "newfcrmeth", nullable = false, length = 1)
	public String getNewfcrmeth() {
		return this.newfcrmeth;
	}

	public void setNewfcrmeth(String newfcrmeth) {
		this.newfcrmeth = newfcrmeth;
	}

	@Column(name = "newfcramt", nullable = false, precision = 16)
	public BigDecimal getNewfcramt() {
		return this.newfcramt;
	}

	public void setNewfcramt(BigDecimal newfcramt) {
		this.newfcramt = newfcramt;
	}

	@Column(name = "newfcrpct", nullable = false, precision = 5)
	public BigDecimal getNewfcrpct() {
		return this.newfcrpct;
	}

	public void setNewfcrpct(BigDecimal newfcrpct) {
		this.newfcrpct = newfcrpct;
	}

	@Column(name = "newfcrrpm", nullable = false, precision = 6, scale = 3)
	public BigDecimal getNewfcrrpm() {
		return this.newfcrrpm;
	}

	public void setNewfcrrpm(BigDecimal newfcrrpm) {
		this.newfcrrpm = newfcrrpm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "perdlfd", length = 13)
	public Date getPerdlfd() {
		return this.perdlfd;
	}

	public void setPerdlfd(Date perdlfd) {
		this.perdlfd = perdlfd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sturndt", length = 13)
	public Date getSturndt() {
		return this.sturndt;
	}

	public void setSturndt(Date sturndt) {
		this.sturndt = sturndt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sturntm", length = 13)
	public Date getSturntm() {
		return this.sturntm;
	}

	public void setSturntm(Date sturntm) {
		this.sturntm = sturntm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "notifydt", length = 13)
	public Date getNotifydt() {
		return this.notifydt;
	}

	public void setNotifydt(Date notifydt) {
		this.notifydt = notifydt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "notifytm", length = 13)
	public Date getNotifytm() {
		return this.notifytm;
	}

	public void setNotifytm(Date notifytm) {
		this.notifytm = notifytm;
	}

	@Column(name = "notifyldmty", nullable = false, length = 1)
	public String getNotifyldmty() {
		return this.notifyldmty;
	}

	public void setNotifyldmty(String notifyldmty) {
		this.notifyldmty = notifyldmty;
	}

	@Column(name = "notifysource", nullable = false, length = 1)
	public String getNotifysource() {
		return this.notifysource;
	}

	public void setNotifysource(String notifysource) {
		this.notifysource = notifysource;
	}

	@Column(name = "perdlfdsource", nullable = false, length = 1)
	public String getPerdlfdsource() {
		return this.perdlfdsource;
	}

	public void setPerdlfdsource(String perdlfdsource) {
		this.perdlfdsource = perdlfdsource;
	}

	@Column(name = "perdlfdflag", nullable = false, length = 1)
	public String getPerdlfdflag() {
		return this.perdlfdflag;
	}

	public void setPerdlfdflag(String perdlfdflag) {
		this.perdlfdflag = perdlfdflag;
	}

	@Column(name = "chassis_eqmast_id", length = 16)
	public String getChassisEqmastId() {
		return this.chassisEqmastId;
	}

	public void setChassisEqmastId(String chassisEqmastId) {
		this.chassisEqmastId = chassisEqmastId;
	}

	@Column(name = "dest_locprof_id", length = 16)
	public String getDestLocprofId() {
		return this.destLocprofId;
	}

	public void setDestLocprofId(String destLocprofId) {
		this.destLocprofId = destLocprofId;
	}

	@Column(name = "driver_id", length = 16)
	public String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	@Column(name = "orig_locprof_id", length = 16)
	public String getOrigLocprofId() {
		return this.origLocprofId;
	}

	public void setOrigLocprofId(String origLocprofId) {
		this.origLocprofId = origLocprofId;
	}

	@Column(name = "trailer_eqmast_id", length = 16)
	public String getTrailerEqmastId() {
		return this.trailerEqmastId;
	}

	public void setTrailerEqmastId(String trailerEqmastId) {
		this.trailerEqmastId = trailerEqmastId;
	}

}
