package com.imc.driver.wait.service.entities;

// Generated May 12, 2015 9:29:50 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orchrg generated by hbm2java
 */
@Entity
@Table(name = "orchrg"
// , uniqueConstraints = @UniqueConstraint(columnNames = "oid")
)
public class Orchrg implements java.io.Serializable {

	private int no;
	private int cmpyNo;
	private String divCode;
	private String pro;
	private int seq;
	private Date adate;
	private Date atime;
	private String alogin;
	private Date udate;
	private Date utime;
	private String ulogin;
	private String t300Code;
	private String description;
	private BigDecimal amount;
	private BigDecimal percent;
	private BigDecimal qty;
	private String btCode;
	private String auth;
	private BigDecimal total;
	private String drCode;
	private BigDecimal drtotal;
	private String blob;
	private BigDecimal drqty;
	private BigDecimal dramount;
	private BigDecimal drpercent;
	private Date pdate;
	private Date ptime;
	private BigDecimal trktotal;
	private BigDecimal trkamount;
	private String ok2pay;
	private int orNo;
	private String prosuffix;

	public Orchrg() {
	}

	public Orchrg(int no, int cmpyNo, String divCode, String pro, int seq,
			String alogin, String ulogin, String t300Code, String description,
			BigDecimal amount, BigDecimal percent, BigDecimal qty,
			String btCode, String auth, BigDecimal total, String drCode,
			BigDecimal drtotal, String blob, BigDecimal drqty,
			BigDecimal dramount, BigDecimal drpercent, BigDecimal trktotal,
			BigDecimal trkamount, String ok2pay, int orNo, String prosuffix) {
		this.no = no;
		this.cmpyNo = cmpyNo;
		this.divCode = divCode;
		this.pro = pro;
		this.seq = seq;
		this.alogin = alogin;
		this.ulogin = ulogin;
		this.t300Code = t300Code;
		this.description = description;
		this.amount = amount;
		this.percent = percent;
		this.qty = qty;
		this.btCode = btCode;
		this.auth = auth;
		this.total = total;
		this.drCode = drCode;
		this.drtotal = drtotal;
		this.blob = blob;
		this.drqty = drqty;
		this.dramount = dramount;
		this.drpercent = drpercent;
		this.trktotal = trktotal;
		this.trkamount = trkamount;
		this.ok2pay = ok2pay;
		this.orNo = orNo;
		this.prosuffix = prosuffix;
	}

	public Orchrg(int no, int cmpyNo, String divCode, String pro, int seq,
			Date adate, Date atime, String alogin, Date udate, Date utime,
			String ulogin, String t300Code, String description,
			BigDecimal amount, BigDecimal percent, BigDecimal qty,
			String btCode, String auth, BigDecimal total, String drCode,
			BigDecimal drtotal, String blob, BigDecimal drqty,
			BigDecimal dramount, BigDecimal drpercent, Date pdate, Date ptime,
			BigDecimal trktotal, BigDecimal trkamount, String ok2pay, int orNo,
			String prosuffix) {
		this.no = no;
		this.cmpyNo = cmpyNo;
		this.divCode = divCode;
		this.pro = pro;
		this.seq = seq;
		this.adate = adate;
		this.atime = atime;
		this.alogin = alogin;
		this.udate = udate;
		this.utime = utime;
		this.ulogin = ulogin;
		this.t300Code = t300Code;
		this.description = description;
		this.amount = amount;
		this.percent = percent;
		this.qty = qty;
		this.btCode = btCode;
		this.auth = auth;
		this.total = total;
		this.drCode = drCode;
		this.drtotal = drtotal;
		this.blob = blob;
		this.drqty = drqty;
		this.dramount = dramount;
		this.drpercent = drpercent;
		this.pdate = pdate;
		this.ptime = ptime;
		this.trktotal = trktotal;
		this.trkamount = trkamount;
		this.ok2pay = ok2pay;
		this.orNo = orNo;
		this.prosuffix = prosuffix;
	}

	@Id
	@Column(name = "no", unique = true, nullable = false)
	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "div_code", nullable = false, length = 2)
	public String getDivCode() {
		return this.divCode;
	}

	public void setDivCode(String divCode) {
		this.divCode = divCode;
	}

	@Column(name = "pro", nullable = false, length = 9)
	public String getPro() {
		return this.pro;
	}

	public void setPro(String pro) {
		this.pro = pro;
	}

	@Column(name = "seq", nullable = false)
	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adate", length = 13)
	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "atime", length = 15)
	public Date getAtime() {
		return this.atime;
	}

	public void setAtime(Date atime) {
		this.atime = atime;
	}

	@Column(name = "alogin", nullable = false, length = 8)
	public String getAlogin() {
		return this.alogin;
	}

	public void setAlogin(String alogin) {
		this.alogin = alogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "udate", length = 13)
	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "utime", length = 15)
	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	@Column(name = "ulogin", nullable = false, length = 8)
	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	@Column(name = "t300_code", nullable = false, length = 3)
	public String getT300Code() {
		return this.t300Code;
	}

	public void setT300Code(String t300Code) {
		this.t300Code = t300Code;
	}

	@Column(name = "description", nullable = false, length = 40)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "amount", nullable = false, precision = 16)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "percent", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getPercent() {
		return this.percent;
	}

	public void setPercent(BigDecimal percent) {
		this.percent = percent;
	}

	@Column(name = "qty", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "bt_code", nullable = false, length = 6)
	public String getBtCode() {
		return this.btCode;
	}

	public void setBtCode(String btCode) {
		this.btCode = btCode;
	}

	@Column(name = "auth", nullable = false, length = 15)
	public String getAuth() {
		return this.auth;
	}

	public void setAuth(String auth) {
		this.auth = auth;
	}

	@Column(name = "total", nullable = false, precision = 16)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "dr_code", nullable = false, length = 6)
	public String getDrCode() {
		return this.drCode;
	}

	public void setDrCode(String drCode) {
		this.drCode = drCode;
	}

	@Column(name = "drtotal", nullable = false, precision = 16)
	public BigDecimal getDrtotal() {
		return this.drtotal;
	}

	public void setDrtotal(BigDecimal drtotal) {
		this.drtotal = drtotal;
	}

	@Column(name = "blob", nullable = false, length = 40)
	public String getBlob() {
		return this.blob;
	}

	public void setBlob(String blob) {
		this.blob = blob;
	}

	@Column(name = "drqty", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getDrqty() {
		return this.drqty;
	}

	public void setDrqty(BigDecimal drqty) {
		this.drqty = drqty;
	}

	@Column(name = "dramount", nullable = false, precision = 16)
	public BigDecimal getDramount() {
		return this.dramount;
	}

	public void setDramount(BigDecimal dramount) {
		this.dramount = dramount;
	}

	@Column(name = "drpercent", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getDrpercent() {
		return this.drpercent;
	}

	public void setDrpercent(BigDecimal drpercent) {
		this.drpercent = drpercent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pdate", length = 13)
	public Date getPdate() {
		return this.pdate;
	}

	public void setPdate(Date pdate) {
		this.pdate = pdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ptime", length = 15)
	public Date getPtime() {
		return this.ptime;
	}

	public void setPtime(Date ptime) {
		this.ptime = ptime;
	}

	@Column(name = "trktotal", nullable = false, precision = 16)
	public BigDecimal getTrktotal() {
		return this.trktotal;
	}

	public void setTrktotal(BigDecimal trktotal) {
		this.trktotal = trktotal;
	}

	@Column(name = "trkamount", nullable = false, precision = 16)
	public BigDecimal getTrkamount() {
		return this.trkamount;
	}

	public void setTrkamount(BigDecimal trkamount) {
		this.trkamount = trkamount;
	}

	@Column(name = "ok2pay", nullable = false, length = 1)
	public String getOk2pay() {
		return this.ok2pay;
	}

	public void setOk2pay(String ok2pay) {
		this.ok2pay = ok2pay;
	}

	@Column(name = "or_no", nullable = false)
	public int getOrNo() {
		return this.orNo;
	}

	public void setOrNo(int orNo) {
		this.orNo = orNo;
	}

	@Column(name = "prosuffix", nullable = false, length = 1)
	public String getProsuffix() {
		return this.prosuffix;
	}

	public void setProsuffix(String prosuffix) {
		this.prosuffix = prosuffix;
	}

}
