package com.imc.driver.wait.service.entities;

// Generated May 12, 2015 9:29:50 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"cmpy_no", "div_code", "pro" })
// ,
// @UniqueConstraint(columnNames = "oid")
})
public class Order implements java.io.Serializable {

	private int no;
	private String version;
	private String divCode;
	private String pro;
	private String type;
	private String status;
	private String droppick;
	private String dsptype;
	private String shlpCode;
	private String shname;
	private String shaddr1;
	private String shcity;
	private String shstCode;
	private String shzip;
	private int shctyNo;
	private String shphone;
	private String shext;
	private String shref;
	private Date shdate;
	private Date shtime1;
	private Date shtime2;
	private String cnlpCode;
	private String cnname;
	private String cnaddr1;
	private String cncity;
	private String cnstCode;
	private String cnzip;
	private int cnctyNo;
	private String cnphone;
	private String cnext;
	private String cnref;
	private Date cndate;
	private Date cntime1;
	private Date cntime2;
	private String btCode;
	private String cref;
	private String altbtCode;
	private String ratetbl;
	private String spq;
	private int units;
	private BigDecimal frtchg;
	private BigDecimal accchg;
	private BigDecimal totchg;
	private String origby;
	private Date origdt;
	private Date origtm;
	private Date fwupdt;
	private Date portdt;
	private Date avaldt;
	private Date freedt;
	private Date reldt;
	private Date reltm;
	private String rellogin;
	private Date defdt;
	private Date deftm;
	private String deflogin;
	private String noa;
	private String cmdyCode;
	private int pieces;
	private int weight;
	private String seal;
	private String booking;
	private String vessel;
	private String oversea;
	private Date codt;
	private Date cotm;
	private String broker;
	private String brokerref;
	private String oceanbol;
	private String tlolpCode;
	private String tloname;
	private String tlocity;
	private String tlostCode;
	private int tloctyNo;
	private String tltlpCode;
	private String tltname;
	private String tltcity;
	private String tltstCode;
	private int tltctyNo;
	private String ldmty;
	private String ok2inv;
	private String rgnCode;
	private Date adate;
	private Date atime;
	private String alogin;
	private Date udate;
	private Date utime;
	private String ulogin;
	private String cmdyhaz;
	private String cmdydesc;
	private String done;
	private Date donedt;
	private Date donetm;
	private String donelogin;
	private String defprev;
	private String tltype;
	private String tl2type;
	private String chtype;
	private String ch2type;
	private String csr;
	private String oneway;
	private Date invdt;
	private String ok2pay;
	private Date paydt;
	private String vnCode1;
	private String vnCode2;
	private String vnCode3;
	private BigDecimal vnamt1;
	private BigDecimal vnamt2;
	private BigDecimal vnamt3;
	private BigDecimal tarfamt;
	private BigDecimal fscpercent;
	private BigDecimal fscamt;
	private BigDecimal totvn;
	private BigDecimal totdr;
	private BigDecimal totacrud;
	private BigDecimal profit;
	private BigDecimal margin;
	private int qty;
	private Date pdate;
	private Date ptime;
	private String vnflag1;
	private String vnflag2;
	private String vnflag3;
	private int e204No;
	private Date deldt;
	private BigDecimal fcramt;
	private Date deltm;
	private Date pudt;
	private Date putm;
	private String hazCode;
	private int cmpyNo;
	private BigDecimal esoamt;
	private String esodivCode;
	private String esopro;
	private String brkdivCode;
	private String brkpro;
	private String altref;
	private String mbdivCode;
	private String mbpro;
	private BigDecimal cost;
	private BigDecimal rebate;
	private BigDecimal actcost;
	private Date avaltm;
	private String cmdyref;
	private String altediCode;
	private Date porttm;
	private String lotloc;
	private String tpolpCode;
	private String tponame;
	private String tpocity;
	private String tpostCode;
	private int tpoctyNo;
	private String tptlpCode;
	private String tptname;
	private String tptcity;
	private String tptstCode;
	private int tptctyNo;
	private int shdays;
	private int cndays;
	private String portflag;
	private String avalflag;
	private String lfdflag;
	private Date perdlfd;
	private String perdflag;
	private String ratequide;
	private String ratever;
	private Date rbrdydt;
	private Date rbrdytm;
	private String rbrdyflag;
	private String rbsend;
	private Date rbsenddt;
	private Date rbsendtm;
	private String hotflag;
	private String reftemp;
	private int custfscmiles;
	private String origcountryCode;
	private String perdbtCode;
	private String perdbtref;
	private String divisionId;
	private String customerBilltoId;
	private String altShipperBilltoId;
	private String chassisDpEqmastId;
	private String chassisEqmastId;
	private String trailerDpEqmastId;
	private String trailerEqmastId;
	private String chassisDpOrigLocprofId;
	private String chassisDpTermLocprofId;
	private String chassisOrigLocprofId;
	private String chassisTermLocprofId;
	private String consigneeLocprofId;
	private String shipperLocprofId;
	private String trailerOrigLocprofId;
	private String trailerTermLocprofId;
	private String tripOrigLocprofId;
	private String tripTermLocprofId;
	private String billtlCode;
	private String billtlChkdig;
	private String billtlRelnum;
	private String billtlSize;
	private String billtlEqocode;
	private String billchCode;
	private String billchChkdig;
	private String billchRelnum;
	private String billchSize;
	private String billchEqocode;
	private String chorigLpCode;
	private String chorigName;
	private String chorigCity;
	private String chorigStCode;
	private int chorigCtyNo;
	private BigDecimal chorigGpslong;
	private BigDecimal chorigGpslat;
	private String chtermLpCode;
	private String chtermName;
	private String chtermCity;
	private String chtermStCode;
	private int chtermCtyNo;
	private BigDecimal chtermGpslong;
	private BigDecimal chtermGpslat;
	private String dptlCode;
	private String dptlChkdig;
	private String dptlRelnum;
	private String dptlSize;
	private String dptlEqocode;
	private String dpchCode;
	private String dpchChkdig;
	private String dpchRelnum;
	private String dpchSize;
	private String dpchEqocode;
	private BigDecimal tpoggpslong;
	private BigDecimal tpoggpslat;
	private BigDecimal tptgpslong;
	private BigDecimal tptgpslat;
	private String chorigRef;
	private String tlorigRef;
	private String tltermRef;
	private String chtermRef;
	private String tporef;
	private String tptref;
	private String dmtype;
	private String chzsupply;
	private String chzchoice;
	private String chzdefeqocode;
	private String chzdefupceqocode;
	private String billchUpceqocode;
	private int ratetblno;
	private BigDecimal t100fscamt;
	private BigDecimal t100fscpercent;
	private BigDecimal t100accchg;
	private BigDecimal t100totchg;
	private BigDecimal chzamt;
	private BigDecimal t100chzamt;
	private BigDecimal chztotvn;
	private String routeGuide;
	private String routeVer;
	private String routeMethod;
	private String routeMiletype;
	private String t100routeGuide;
	private String t100routeVer;
	private String t100routeMethod;
	private String t100routeMiletype;
	private String hazCodeMty;
	private Date chzstartdt;
	private Date chzstopdt;
	private int chzusagedays;
	private BigDecimal chzprofit;
	private BigDecimal profitchz;
	private BigDecimal marginchz;
	private Date chzvnstartdt;
	private Date chzvnstopdt;
	private int chzvnusagedays;
	private String chzflags;
	private BigDecimal chzvnamt;
	private String custprodCode;
	private String isbrokerage;
	private String billtlType;
	private String billtlIsvalid;
	private String billchType;
	private String billchIsvalid;
	private String dptlType;
	private String dptlIsvalid;
	private String dpchType;
	private String dpchIsvalid;
	private int chzpassdays;
	private String revtype;
	private Set<Move> moves = new HashSet<Move>(0);

	public Order() {
	}

	public Order(int no, String divCode, String pro, String type,
			String status, String droppick, String dsptype, String shlpCode,
			String shname, String shaddr1, String shcity, String shstCode,
			String shzip, int shctyNo, String shphone, String shext,
			String shref, String cnlpCode, String cnname, String cnaddr1,
			String cncity, String cnstCode, String cnzip, int cnctyNo,
			String cnphone, String cnext, String cnref, String btCode,
			String cref, String altbtCode, String ratetbl, String spq,
			int units, BigDecimal frtchg, BigDecimal accchg, BigDecimal totchg,
			String origby, String rellogin, String deflogin, String noa,
			String cmdyCode, int pieces, int weight, String seal,
			String booking, String vessel, String oversea, String broker,
			String brokerref, String oceanbol, String tlolpCode,
			String tloname, String tlocity, String tlostCode, int tloctyNo,
			String tltlpCode, String tltname, String tltcity, String tltstCode,
			int tltctyNo, String ldmty, String ok2inv, String rgnCode,
			String alogin, String ulogin, String cmdyhaz, String cmdydesc,
			String done, String donelogin, String defprev, String tltype,
			String tl2type, String chtype, String ch2type, String csr,
			String oneway, String ok2pay, String vnCode1, String vnCode2,
			String vnCode3, BigDecimal vnamt1, BigDecimal vnamt2,
			BigDecimal vnamt3, BigDecimal tarfamt, BigDecimal fscpercent,
			BigDecimal fscamt, BigDecimal totvn, BigDecimal totdr,
			BigDecimal totacrud, BigDecimal profit, BigDecimal margin, int qty,
			String vnflag1, String vnflag2, String vnflag3, int e204No,
			BigDecimal fcramt, String hazCode, int cmpyNo, BigDecimal esoamt,
			String esodivCode, String esopro, String brkdivCode, String brkpro,
			String altref, String mbdivCode, String mbpro, BigDecimal cost,
			BigDecimal rebate, BigDecimal actcost, String cmdyref,
			String altediCode, String lotloc, String tpolpCode, String tponame,
			String tpocity, String tpostCode, int tpoctyNo, String tptlpCode,
			String tptname, String tptcity, String tptstCode, int tptctyNo,
			int shdays, int cndays, String portflag, String avalflag,
			String lfdflag, String perdflag, String ratequide, String ratever,
			String rbrdyflag, String rbsend, String hotflag, String reftemp,
			int custfscmiles, String origcountryCode, String perdbtCode,
			String perdbtref, String billtlCode, String billtlChkdig,
			String billtlRelnum, String billtlSize, String billtlEqocode,
			String billchCode, String billchChkdig, String billchRelnum,
			String billchSize, String billchEqocode, String chorigLpCode,
			String chorigName, String chorigCity, String chorigStCode,
			int chorigCtyNo, BigDecimal chorigGpslong, BigDecimal chorigGpslat,
			String chtermLpCode, String chtermName, String chtermCity,
			String chtermStCode, int chtermCtyNo, BigDecimal chtermGpslong,
			BigDecimal chtermGpslat, String dptlCode, String dptlChkdig,
			String dptlRelnum, String dptlSize, String dptlEqocode,
			String dpchCode, String dpchChkdig, String dpchRelnum,
			String dpchSize, String dpchEqocode, BigDecimal tpoggpslong,
			BigDecimal tpoggpslat, BigDecimal tptgpslong, BigDecimal tptgpslat,
			String chorigRef, String tlorigRef, String tltermRef,
			String chtermRef, String tporef, String tptref, String dmtype,
			String chzsupply, String chzchoice, String chzdefeqocode,
			String chzdefupceqocode, String billchUpceqocode, int ratetblno,
			BigDecimal t100fscamt, BigDecimal t100fscpercent,
			BigDecimal t100accchg, BigDecimal t100totchg, BigDecimal chzamt,
			BigDecimal t100chzamt, BigDecimal chztotvn, String routeGuide,
			String routeVer, String routeMethod, String routeMiletype,
			String t100routeGuide, String t100routeVer, String t100routeMethod,
			String t100routeMiletype, int chzusagedays, BigDecimal chzprofit,
			BigDecimal profitchz, BigDecimal marginchz, int chzvnusagedays,
			String chzflags, BigDecimal chzvnamt, String isbrokerage,
			String billtlType, String billtlIsvalid, String billchType,
			String billchIsvalid, String dptlType, String dptlIsvalid,
			String dpchType, String dpchIsvalid, int chzpassdays, String revtype) {
		this.no = no;
		this.divCode = divCode;
		this.pro = pro;
		this.type = type;
		this.status = status;
		this.droppick = droppick;
		this.dsptype = dsptype;
		this.shlpCode = shlpCode;
		this.shname = shname;
		this.shaddr1 = shaddr1;
		this.shcity = shcity;
		this.shstCode = shstCode;
		this.shzip = shzip;
		this.shctyNo = shctyNo;
		this.shphone = shphone;
		this.shext = shext;
		this.shref = shref;
		this.cnlpCode = cnlpCode;
		this.cnname = cnname;
		this.cnaddr1 = cnaddr1;
		this.cncity = cncity;
		this.cnstCode = cnstCode;
		this.cnzip = cnzip;
		this.cnctyNo = cnctyNo;
		this.cnphone = cnphone;
		this.cnext = cnext;
		this.cnref = cnref;
		this.btCode = btCode;
		this.cref = cref;
		this.altbtCode = altbtCode;
		this.ratetbl = ratetbl;
		this.spq = spq;
		this.units = units;
		this.frtchg = frtchg;
		this.accchg = accchg;
		this.totchg = totchg;
		this.origby = origby;
		this.rellogin = rellogin;
		this.deflogin = deflogin;
		this.noa = noa;
		this.cmdyCode = cmdyCode;
		this.pieces = pieces;
		this.weight = weight;
		this.seal = seal;
		this.booking = booking;
		this.vessel = vessel;
		this.oversea = oversea;
		this.broker = broker;
		this.brokerref = brokerref;
		this.oceanbol = oceanbol;
		this.tlolpCode = tlolpCode;
		this.tloname = tloname;
		this.tlocity = tlocity;
		this.tlostCode = tlostCode;
		this.tloctyNo = tloctyNo;
		this.tltlpCode = tltlpCode;
		this.tltname = tltname;
		this.tltcity = tltcity;
		this.tltstCode = tltstCode;
		this.tltctyNo = tltctyNo;
		this.ldmty = ldmty;
		this.ok2inv = ok2inv;
		this.rgnCode = rgnCode;
		this.alogin = alogin;
		this.ulogin = ulogin;
		this.cmdyhaz = cmdyhaz;
		this.cmdydesc = cmdydesc;
		this.done = done;
		this.donelogin = donelogin;
		this.defprev = defprev;
		this.tltype = tltype;
		this.tl2type = tl2type;
		this.chtype = chtype;
		this.ch2type = ch2type;
		this.csr = csr;
		this.oneway = oneway;
		this.ok2pay = ok2pay;
		this.vnCode1 = vnCode1;
		this.vnCode2 = vnCode2;
		this.vnCode3 = vnCode3;
		this.vnamt1 = vnamt1;
		this.vnamt2 = vnamt2;
		this.vnamt3 = vnamt3;
		this.tarfamt = tarfamt;
		this.fscpercent = fscpercent;
		this.fscamt = fscamt;
		this.totvn = totvn;
		this.totdr = totdr;
		this.totacrud = totacrud;
		this.profit = profit;
		this.margin = margin;
		this.qty = qty;
		this.vnflag1 = vnflag1;
		this.vnflag2 = vnflag2;
		this.vnflag3 = vnflag3;
		this.e204No = e204No;
		this.fcramt = fcramt;
		this.hazCode = hazCode;
		this.cmpyNo = cmpyNo;
		this.esoamt = esoamt;
		this.esodivCode = esodivCode;
		this.esopro = esopro;
		this.brkdivCode = brkdivCode;
		this.brkpro = brkpro;
		this.altref = altref;
		this.mbdivCode = mbdivCode;
		this.mbpro = mbpro;
		this.cost = cost;
		this.rebate = rebate;
		this.actcost = actcost;
		this.cmdyref = cmdyref;
		this.altediCode = altediCode;
		this.lotloc = lotloc;
		this.tpolpCode = tpolpCode;
		this.tponame = tponame;
		this.tpocity = tpocity;
		this.tpostCode = tpostCode;
		this.tpoctyNo = tpoctyNo;
		this.tptlpCode = tptlpCode;
		this.tptname = tptname;
		this.tptcity = tptcity;
		this.tptstCode = tptstCode;
		this.tptctyNo = tptctyNo;
		this.shdays = shdays;
		this.cndays = cndays;
		this.portflag = portflag;
		this.avalflag = avalflag;
		this.lfdflag = lfdflag;
		this.perdflag = perdflag;
		this.ratequide = ratequide;
		this.ratever = ratever;
		this.rbrdyflag = rbrdyflag;
		this.rbsend = rbsend;
		this.hotflag = hotflag;
		this.reftemp = reftemp;
		this.custfscmiles = custfscmiles;
		this.origcountryCode = origcountryCode;
		this.perdbtCode = perdbtCode;
		this.perdbtref = perdbtref;
		this.billtlCode = billtlCode;
		this.billtlChkdig = billtlChkdig;
		this.billtlRelnum = billtlRelnum;
		this.billtlSize = billtlSize;
		this.billtlEqocode = billtlEqocode;
		this.billchCode = billchCode;
		this.billchChkdig = billchChkdig;
		this.billchRelnum = billchRelnum;
		this.billchSize = billchSize;
		this.billchEqocode = billchEqocode;
		this.chorigLpCode = chorigLpCode;
		this.chorigName = chorigName;
		this.chorigCity = chorigCity;
		this.chorigStCode = chorigStCode;
		this.chorigCtyNo = chorigCtyNo;
		this.chorigGpslong = chorigGpslong;
		this.chorigGpslat = chorigGpslat;
		this.chtermLpCode = chtermLpCode;
		this.chtermName = chtermName;
		this.chtermCity = chtermCity;
		this.chtermStCode = chtermStCode;
		this.chtermCtyNo = chtermCtyNo;
		this.chtermGpslong = chtermGpslong;
		this.chtermGpslat = chtermGpslat;
		this.dptlCode = dptlCode;
		this.dptlChkdig = dptlChkdig;
		this.dptlRelnum = dptlRelnum;
		this.dptlSize = dptlSize;
		this.dptlEqocode = dptlEqocode;
		this.dpchCode = dpchCode;
		this.dpchChkdig = dpchChkdig;
		this.dpchRelnum = dpchRelnum;
		this.dpchSize = dpchSize;
		this.dpchEqocode = dpchEqocode;
		this.tpoggpslong = tpoggpslong;
		this.tpoggpslat = tpoggpslat;
		this.tptgpslong = tptgpslong;
		this.tptgpslat = tptgpslat;
		this.chorigRef = chorigRef;
		this.tlorigRef = tlorigRef;
		this.tltermRef = tltermRef;
		this.chtermRef = chtermRef;
		this.tporef = tporef;
		this.tptref = tptref;
		this.dmtype = dmtype;
		this.chzsupply = chzsupply;
		this.chzchoice = chzchoice;
		this.chzdefeqocode = chzdefeqocode;
		this.chzdefupceqocode = chzdefupceqocode;
		this.billchUpceqocode = billchUpceqocode;
		this.ratetblno = ratetblno;
		this.t100fscamt = t100fscamt;
		this.t100fscpercent = t100fscpercent;
		this.t100accchg = t100accchg;
		this.t100totchg = t100totchg;
		this.chzamt = chzamt;
		this.t100chzamt = t100chzamt;
		this.chztotvn = chztotvn;
		this.routeGuide = routeGuide;
		this.routeVer = routeVer;
		this.routeMethod = routeMethod;
		this.routeMiletype = routeMiletype;
		this.t100routeGuide = t100routeGuide;
		this.t100routeVer = t100routeVer;
		this.t100routeMethod = t100routeMethod;
		this.t100routeMiletype = t100routeMiletype;
		this.chzusagedays = chzusagedays;
		this.chzprofit = chzprofit;
		this.profitchz = profitchz;
		this.marginchz = marginchz;
		this.chzvnusagedays = chzvnusagedays;
		this.chzflags = chzflags;
		this.chzvnamt = chzvnamt;
		this.isbrokerage = isbrokerage;
		this.billtlType = billtlType;
		this.billtlIsvalid = billtlIsvalid;
		this.billchType = billchType;
		this.billchIsvalid = billchIsvalid;
		this.dptlType = dptlType;
		this.dptlIsvalid = dptlIsvalid;
		this.dpchType = dpchType;
		this.dpchIsvalid = dpchIsvalid;
		this.chzpassdays = chzpassdays;
		this.revtype = revtype;
	}

	// public Order(int no, String divCode, String pro, String type,
	// String status, String droppick, String dsptype, String shlpCode,
	// String shname, String shaddr1, String shcity, String shstCode,
	// String shzip, int shctyNo, String shphone, String shext,
	// String shref, Date shdate, Date shtime1, Date shtime2,
	// String cnlpCode, String cnname, String cnaddr1, String cncity,
	// String cnstCode, String cnzip, int cnctyNo, String cnphone,
	// String cnext, String cnref, Date cndate, Date cntime1,
	// Date cntime2, String btCode, String cref, String altbtCode,
	// String ratetbl, String spq, int units, BigDecimal frtchg,
	// BigDecimal accchg, BigDecimal totchg, String origby, Date origdt,
	// Date origtm, Date fwupdt, Date portdt, Date avaldt, Date freedt,
	// Date reldt, Date reltm, String rellogin, Date defdt, Date deftm,
	// String deflogin, String noa, String cmdyCode, int pieces,
	// int weight, String seal, String booking, String vessel,
	// String oversea, Date codt, Date cotm, String broker,
	// String brokerref, String oceanbol, String tlolpCode,
	// String tloname, String tlocity, String tlostCode, int tloctyNo,
	// String tltlpCode, String tltname, String tltcity, String tltstCode,
	// int tltctyNo, String ldmty, String ok2inv, String rgnCode,
	// Date adate, Date atime, String alogin, Date udate, Date utime,
	// String ulogin, String cmdyhaz, String cmdydesc, String done,
	// Date donedt, Date donetm, String donelogin, String defprev,
	// String tltype, String tl2type, String chtype, String ch2type,
	// String csr, String oneway, Date invdt, String ok2pay, Date paydt,
	// String vnCode1, String vnCode2, String vnCode3, BigDecimal vnamt1,
	// BigDecimal vnamt2, BigDecimal vnamt3, BigDecimal tarfamt,
	// BigDecimal fscpercent, BigDecimal fscamt, BigDecimal totvn,
	// BigDecimal totdr, BigDecimal totacrud, BigDecimal profit,
	// BigDecimal margin, int qty, Date pdate, Date ptime, String vnflag1,
	// String vnflag2, String vnflag3, int e204No, Date deldt,
	// BigDecimal fcramt, Date deltm, Date pudt, Date putm,
	// String hazCode, int cmpyNo, BigDecimal esoamt, String esodivCode,
	// String esopro, String brkdivCode, String brkpro, String altref,
	// String mbdivCode, String mbpro, BigDecimal cost, BigDecimal rebate,
	// BigDecimal actcost, Date avaltm, String cmdyref, String altediCode,
	// Date porttm, String lotloc, String tpolpCode, String tponame,
	// String tpocity, String tpostCode, int tpoctyNo, String tptlpCode,
	// String tptname, String tptcity, String tptstCode, int tptctyNo,
	// int shdays, int cndays, String portflag, String avalflag,
	// String lfdflag, Date perdlfd, String perdflag, String ratequide,
	// String ratever, Date rbrdydt, Date rbrdytm, String rbrdyflag,
	// String rbsend, Date rbsenddt, Date rbsendtm, String hotflag,
	// String reftemp, int custfscmiles, String origcountryCode,
	// String perdbtCode, String perdbtref, String divisionId,
	// String customerBilltoId, String altShipperBilltoId,
	// String chassisDpEqmastId, String chassisEqmastId,
	// String trailerDpEqmastId, String trailerEqmastId,
	// String chassisDpOrigLocprofId, String chassisDpTermLocprofId,
	// String chassisOrigLocprofId, String chassisTermLocprofId,
	// String consigneeLocprofId, String shipperLocprofId,
	// String trailerOrigLocprofId, String trailerTermLocprofId,
	// String tripOrigLocprofId, String tripTermLocprofId,
	// String billtlCode, String billtlChkdig, String billtlRelnum,
	// String billtlSize, String billtlEqocode, String billchCode,
	// String billchChkdig, String billchRelnum, String billchSize,
	// String billchEqocode, String chorigLpCode, String chorigName,
	// String chorigCity, String chorigStCode, int chorigCtyNo,
	// BigDecimal chorigGpslong, BigDecimal chorigGpslat,
	// String chtermLpCode, String chtermName, String chtermCity,
	// String chtermStCode, int chtermCtyNo, BigDecimal chtermGpslong,
	// BigDecimal chtermGpslat, String dptlCode, String dptlChkdig,
	// String dptlRelnum, String dptlSize, String dptlEqocode,
	// String dpchCode, String dpchChkdig, String dpchRelnum,
	// String dpchSize, String dpchEqocode, BigDecimal tpoggpslong,
	// BigDecimal tpoggpslat, BigDecimal tptgpslong, BigDecimal tptgpslat,
	// String chorigRef, String tlorigRef, String tltermRef,
	// String chtermRef, String tporef, String tptref, String dmtype,
	// String chzsupply, String chzchoice, String chzdefeqocode,
	// String chzdefupceqocode, String billchUpceqocode, int ratetblno,
	// BigDecimal t100fscamt, BigDecimal t100fscpercent,
	// BigDecimal t100accchg, BigDecimal t100totchg, BigDecimal chzamt,
	// BigDecimal t100chzamt, BigDecimal chztotvn, String routeGuide,
	// String routeVer, String routeMethod, String routeMiletype,
	// String t100routeGuide, String t100routeVer, String t100routeMethod,
	// String t100routeMiletype, String hazCodeMty, Date chzstartdt,
	// Date chzstopdt, int chzusagedays, BigDecimal chzprofit,
	// BigDecimal profitchz, BigDecimal marginchz, Date chzvnstartdt,
	// Date chzvnstopdt, int chzvnusagedays, String chzflags,
	// BigDecimal chzvnamt, String custprodCode, String isbrokerage,
	// String billtlType, String billtlIsvalid, String billchType,
	// String billchIsvalid, String dptlType, String dptlIsvalid,
	// String dpchType, String dpchIsvalid, int chzpassdays,
	// String revtype, Set<Move> moves) {
	// this.no = no;
	// this.divCode = divCode;
	// this.pro = pro;
	// this.type = type;
	// this.status = status;
	// this.droppick = droppick;
	// this.dsptype = dsptype;
	// this.shlpCode = shlpCode;
	// this.shname = shname;
	// this.shaddr1 = shaddr1;
	// this.shcity = shcity;
	// this.shstCode = shstCode;
	// this.shzip = shzip;
	// this.shctyNo = shctyNo;
	// this.shphone = shphone;
	// this.shext = shext;
	// this.shref = shref;
	// this.shdate = shdate;
	// this.shtime1 = shtime1;
	// this.shtime2 = shtime2;
	// this.cnlpCode = cnlpCode;
	// this.cnname = cnname;
	// this.cnaddr1 = cnaddr1;
	// this.cncity = cncity;
	// this.cnstCode = cnstCode;
	// this.cnzip = cnzip;
	// this.cnctyNo = cnctyNo;
	// this.cnphone = cnphone;
	// this.cnext = cnext;
	// this.cnref = cnref;
	// this.cndate = cndate;
	// this.cntime1 = cntime1;
	// this.cntime2 = cntime2;
	// this.btCode = btCode;
	// this.cref = cref;
	// this.altbtCode = altbtCode;
	// this.ratetbl = ratetbl;
	// this.spq = spq;
	// this.units = units;
	// this.frtchg = frtchg;
	// this.accchg = accchg;
	// this.totchg = totchg;
	// this.origby = origby;
	// this.origdt = origdt;
	// this.origtm = origtm;
	// this.fwupdt = fwupdt;
	// this.portdt = portdt;
	// this.avaldt = avaldt;
	// this.freedt = freedt;
	// this.reldt = reldt;
	// this.reltm = reltm;
	// this.rellogin = rellogin;
	// this.defdt = defdt;
	// this.deftm = deftm;
	// this.deflogin = deflogin;
	// this.noa = noa;
	// this.cmdyCode = cmdyCode;
	// this.pieces = pieces;
	// this.weight = weight;
	// this.seal = seal;
	// this.booking = booking;
	// this.vessel = vessel;
	// this.oversea = oversea;
	// this.codt = codt;
	// this.cotm = cotm;
	// this.broker = broker;
	// this.brokerref = brokerref;
	// this.oceanbol = oceanbol;
	// this.tlolpCode = tlolpCode;
	// this.tloname = tloname;
	// this.tlocity = tlocity;
	// this.tlostCode = tlostCode;
	// this.tloctyNo = tloctyNo;
	// this.tltlpCode = tltlpCode;
	// this.tltname = tltname;
	// this.tltcity = tltcity;
	// this.tltstCode = tltstCode;
	// this.tltctyNo = tltctyNo;
	// this.ldmty = ldmty;
	// this.ok2inv = ok2inv;
	// this.rgnCode = rgnCode;
	// this.adate = adate;
	// this.atime = atime;
	// this.alogin = alogin;
	// this.udate = udate;
	// this.utime = utime;
	// this.ulogin = ulogin;
	// this.cmdyhaz = cmdyhaz;
	// this.cmdydesc = cmdydesc;
	// this.done = done;
	// this.donedt = donedt;
	// this.donetm = donetm;
	// this.donelogin = donelogin;
	// this.defprev = defprev;
	// this.tltype = tltype;
	// this.tl2type = tl2type;
	// this.chtype = chtype;
	// this.ch2type = ch2type;
	// this.csr = csr;
	// this.oneway = oneway;
	// this.invdt = invdt;
	// this.ok2pay = ok2pay;
	// this.paydt = paydt;
	// this.vnCode1 = vnCode1;
	// this.vnCode2 = vnCode2;
	// this.vnCode3 = vnCode3;
	// this.vnamt1 = vnamt1;
	// this.vnamt2 = vnamt2;
	// this.vnamt3 = vnamt3;
	// this.tarfamt = tarfamt;
	// this.fscpercent = fscpercent;
	// this.fscamt = fscamt;
	// this.totvn = totvn;
	// this.totdr = totdr;
	// this.totacrud = totacrud;
	// this.profit = profit;
	// this.margin = margin;
	// this.qty = qty;
	// this.pdate = pdate;
	// this.ptime = ptime;
	// this.vnflag1 = vnflag1;
	// this.vnflag2 = vnflag2;
	// this.vnflag3 = vnflag3;
	// this.e204No = e204No;
	// this.deldt = deldt;
	// this.fcramt = fcramt;
	// this.deltm = deltm;
	// this.pudt = pudt;
	// this.putm = putm;
	// this.hazCode = hazCode;
	// this.cmpyNo = cmpyNo;
	// this.esoamt = esoamt;
	// this.esodivCode = esodivCode;
	// this.esopro = esopro;
	// this.brkdivCode = brkdivCode;
	// this.brkpro = brkpro;
	// this.altref = altref;
	// this.mbdivCode = mbdivCode;
	// this.mbpro = mbpro;
	// this.cost = cost;
	// this.rebate = rebate;
	// this.actcost = actcost;
	// this.avaltm = avaltm;
	// this.cmdyref = cmdyref;
	// this.altediCode = altediCode;
	// this.porttm = porttm;
	// this.lotloc = lotloc;
	// this.tpolpCode = tpolpCode;
	// this.tponame = tponame;
	// this.tpocity = tpocity;
	// this.tpostCode = tpostCode;
	// this.tpoctyNo = tpoctyNo;
	// this.tptlpCode = tptlpCode;
	// this.tptname = tptname;
	// this.tptcity = tptcity;
	// this.tptstCode = tptstCode;
	// this.tptctyNo = tptctyNo;
	// this.shdays = shdays;
	// this.cndays = cndays;
	// this.portflag = portflag;
	// this.avalflag = avalflag;
	// this.lfdflag = lfdflag;
	// this.perdlfd = perdlfd;
	// this.perdflag = perdflag;
	// this.ratequide = ratequide;
	// this.ratever = ratever;
	// this.rbrdydt = rbrdydt;
	// this.rbrdytm = rbrdytm;
	// this.rbrdyflag = rbrdyflag;
	// this.rbsend = rbsend;
	// this.rbsenddt = rbsenddt;
	// this.rbsendtm = rbsendtm;
	// this.hotflag = hotflag;
	// this.reftemp = reftemp;
	// this.custfscmiles = custfscmiles;
	// this.origcountryCode = origcountryCode;
	// this.perdbtCode = perdbtCode;
	// this.perdbtref = perdbtref;
	// this.divisionId = divisionId;
	// this.customerBilltoId = customerBilltoId;
	// this.altShipperBilltoId = altShipperBilltoId;
	// this.chassisDpEqmastId = chassisDpEqmastId;
	// this.chassisEqmastId = chassisEqmastId;
	// this.trailerDpEqmastId = trailerDpEqmastId;
	// this.trailerEqmastId = trailerEqmastId;
	// this.chassisDpOrigLocprofId = chassisDpOrigLocprofId;
	// this.chassisDpTermLocprofId = chassisDpTermLocprofId;
	// this.chassisOrigLocprofId = chassisOrigLocprofId;
	// this.chassisTermLocprofId = chassisTermLocprofId;
	// this.consigneeLocprofId = consigneeLocprofId;
	// this.shipperLocprofId = shipperLocprofId;
	// this.trailerOrigLocprofId = trailerOrigLocprofId;
	// this.trailerTermLocprofId = trailerTermLocprofId;
	// this.tripOrigLocprofId = tripOrigLocprofId;
	// this.tripTermLocprofId = tripTermLocprofId;
	// this.billtlCode = billtlCode;
	// this.billtlChkdig = billtlChkdig;
	// this.billtlRelnum = billtlRelnum;
	// this.billtlSize = billtlSize;
	// this.billtlEqocode = billtlEqocode;
	// this.billchCode = billchCode;
	// this.billchChkdig = billchChkdig;
	// this.billchRelnum = billchRelnum;
	// this.billchSize = billchSize;
	// this.billchEqocode = billchEqocode;
	// this.chorigLpCode = chorigLpCode;
	// this.chorigName = chorigName;
	// this.chorigCity = chorigCity;
	// this.chorigStCode = chorigStCode;
	// this.chorigCtyNo = chorigCtyNo;
	// this.chorigGpslong = chorigGpslong;
	// this.chorigGpslat = chorigGpslat;
	// this.chtermLpCode = chtermLpCode;
	// this.chtermName = chtermName;
	// this.chtermCity = chtermCity;
	// this.chtermStCode = chtermStCode;
	// this.chtermCtyNo = chtermCtyNo;
	// this.chtermGpslong = chtermGpslong;
	// this.chtermGpslat = chtermGpslat;
	// this.dptlCode = dptlCode;
	// this.dptlChkdig = dptlChkdig;
	// this.dptlRelnum = dptlRelnum;
	// this.dptlSize = dptlSize;
	// this.dptlEqocode = dptlEqocode;
	// this.dpchCode = dpchCode;
	// this.dpchChkdig = dpchChkdig;
	// this.dpchRelnum = dpchRelnum;
	// this.dpchSize = dpchSize;
	// this.dpchEqocode = dpchEqocode;
	// this.tpoggpslong = tpoggpslong;
	// this.tpoggpslat = tpoggpslat;
	// this.tptgpslong = tptgpslong;
	// this.tptgpslat = tptgpslat;
	// this.chorigRef = chorigRef;
	// this.tlorigRef = tlorigRef;
	// this.tltermRef = tltermRef;
	// this.chtermRef = chtermRef;
	// this.tporef = tporef;
	// this.tptref = tptref;
	// this.dmtype = dmtype;
	// this.chzsupply = chzsupply;
	// this.chzchoice = chzchoice;
	// this.chzdefeqocode = chzdefeqocode;
	// this.chzdefupceqocode = chzdefupceqocode;
	// this.billchUpceqocode = billchUpceqocode;
	// this.ratetblno = ratetblno;
	// this.t100fscamt = t100fscamt;
	// this.t100fscpercent = t100fscpercent;
	// this.t100accchg = t100accchg;
	// this.t100totchg = t100totchg;
	// this.chzamt = chzamt;
	// this.t100chzamt = t100chzamt;
	// this.chztotvn = chztotvn;
	// this.routeGuide = routeGuide;
	// this.routeVer = routeVer;
	// this.routeMethod = routeMethod;
	// this.routeMiletype = routeMiletype;
	// this.t100routeGuide = t100routeGuide;
	// this.t100routeVer = t100routeVer;
	// this.t100routeMethod = t100routeMethod;
	// this.t100routeMiletype = t100routeMiletype;
	// this.hazCodeMty = hazCodeMty;
	// this.chzstartdt = chzstartdt;
	// this.chzstopdt = chzstopdt;
	// this.chzusagedays = chzusagedays;
	// this.chzprofit = chzprofit;
	// this.profitchz = profitchz;
	// this.marginchz = marginchz;
	// this.chzvnstartdt = chzvnstartdt;
	// this.chzvnstopdt = chzvnstopdt;
	// this.chzvnusagedays = chzvnusagedays;
	// this.chzflags = chzflags;
	// this.chzvnamt = chzvnamt;
	// this.custprodCode = custprodCode;
	// this.isbrokerage = isbrokerage;
	// this.billtlType = billtlType;
	// this.billtlIsvalid = billtlIsvalid;
	// this.billchType = billchType;
	// this.billchIsvalid = billchIsvalid;
	// this.dptlType = dptlType;
	// this.dptlIsvalid = dptlIsvalid;
	// this.dpchType = dpchType;
	// this.dpchIsvalid = dpchIsvalid;
	// this.chzpassdays = chzpassdays;
	// this.revtype = revtype;
	// this.moves = moves;
	// }

	@Id
	@Column(name = "no", unique = true, nullable = false)
	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	// @Version
	@Column(name = "version", nullable = false, length = 1)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "div_code", nullable = false, length = 2)
	public String getDivCode() {
		return this.divCode;
	}

	public void setDivCode(String divCode) {
		this.divCode = divCode;
	}

	@Column(name = "pro", nullable = false, length = 9)
	public String getPro() {
		return this.pro;
	}

	public void setPro(String pro) {
		this.pro = pro;
	}

	@Column(name = "type", nullable = false, length = 1)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "droppick", nullable = false, length = 2)
	public String getDroppick() {
		return this.droppick;
	}

	public void setDroppick(String droppick) {
		this.droppick = droppick;
	}

	@Column(name = "dsptype", nullable = false, length = 1)
	public String getDsptype() {
		return this.dsptype;
	}

	public void setDsptype(String dsptype) {
		this.dsptype = dsptype;
	}

	@Column(name = "shlp_code", nullable = false, length = 6)
	public String getShlpCode() {
		return this.shlpCode;
	}

	public void setShlpCode(String shlpCode) {
		this.shlpCode = shlpCode;
	}

	@Column(name = "shname", nullable = false, length = 30)
	public String getShname() {
		return this.shname;
	}

	public void setShname(String shname) {
		this.shname = shname;
	}

	@Column(name = "shaddr1", nullable = false, length = 30)
	public String getShaddr1() {
		return this.shaddr1;
	}

	public void setShaddr1(String shaddr1) {
		this.shaddr1 = shaddr1;
	}

	@Column(name = "shcity", nullable = false, length = 20)
	public String getShcity() {
		return this.shcity;
	}

	public void setShcity(String shcity) {
		this.shcity = shcity;
	}

	@Column(name = "shst_code", nullable = false, length = 2)
	public String getShstCode() {
		return this.shstCode;
	}

	public void setShstCode(String shstCode) {
		this.shstCode = shstCode;
	}

	@Column(name = "shzip", nullable = false, length = 10)
	public String getShzip() {
		return this.shzip;
	}

	public void setShzip(String shzip) {
		this.shzip = shzip;
	}

	@Column(name = "shcty_no", nullable = false)
	public int getShctyNo() {
		return this.shctyNo;
	}

	public void setShctyNo(int shctyNo) {
		this.shctyNo = shctyNo;
	}

	@Column(name = "shphone", nullable = false, length = 10)
	public String getShphone() {
		return this.shphone;
	}

	public void setShphone(String shphone) {
		this.shphone = shphone;
	}

	@Column(name = "shext", nullable = false, length = 5)
	public String getShext() {
		return this.shext;
	}

	public void setShext(String shext) {
		this.shext = shext;
	}

	@Column(name = "shref", nullable = false, length = 25)
	public String getShref() {
		return this.shref;
	}

	public void setShref(String shref) {
		this.shref = shref;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "shdate", length = 13)
	public Date getShdate() {
		return this.shdate;
	}

	public void setShdate(Date shdate) {
		this.shdate = shdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "shtime1", length = 15)
	public Date getShtime1() {
		return this.shtime1;
	}

	public void setShtime1(Date shtime1) {
		this.shtime1 = shtime1;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "shtime2", length = 15)
	public Date getShtime2() {
		return this.shtime2;
	}

	public void setShtime2(Date shtime2) {
		this.shtime2 = shtime2;
	}

	@Column(name = "cnlp_code", nullable = false, length = 6)
	public String getCnlpCode() {
		return this.cnlpCode;
	}

	public void setCnlpCode(String cnlpCode) {
		this.cnlpCode = cnlpCode;
	}

	@Column(name = "cnname", nullable = false, length = 30)
	public String getCnname() {
		return this.cnname;
	}

	public void setCnname(String cnname) {
		this.cnname = cnname;
	}

	@Column(name = "cnaddr1", nullable = false, length = 30)
	public String getCnaddr1() {
		return this.cnaddr1;
	}

	public void setCnaddr1(String cnaddr1) {
		this.cnaddr1 = cnaddr1;
	}

	@Column(name = "cncity", nullable = false, length = 20)
	public String getCncity() {
		return this.cncity;
	}

	public void setCncity(String cncity) {
		this.cncity = cncity;
	}

	@Column(name = "cnst_code", nullable = false, length = 2)
	public String getCnstCode() {
		return this.cnstCode;
	}

	public void setCnstCode(String cnstCode) {
		this.cnstCode = cnstCode;
	}

	@Column(name = "cnzip", nullable = false, length = 10)
	public String getCnzip() {
		return this.cnzip;
	}

	public void setCnzip(String cnzip) {
		this.cnzip = cnzip;
	}

	@Column(name = "cncty_no", nullable = false)
	public int getCnctyNo() {
		return this.cnctyNo;
	}

	public void setCnctyNo(int cnctyNo) {
		this.cnctyNo = cnctyNo;
	}

	@Column(name = "cnphone", nullable = false, length = 10)
	public String getCnphone() {
		return this.cnphone;
	}

	public void setCnphone(String cnphone) {
		this.cnphone = cnphone;
	}

	@Column(name = "cnext", nullable = false, length = 5)
	public String getCnext() {
		return this.cnext;
	}

	public void setCnext(String cnext) {
		this.cnext = cnext;
	}

	@Column(name = "cnref", nullable = false, length = 25)
	public String getCnref() {
		return this.cnref;
	}

	public void setCnref(String cnref) {
		this.cnref = cnref;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cndate", length = 13)
	public Date getCndate() {
		return this.cndate;
	}

	public void setCndate(Date cndate) {
		this.cndate = cndate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "cntime1", length = 15)
	public Date getCntime1() {
		return this.cntime1;
	}

	public void setCntime1(Date cntime1) {
		this.cntime1 = cntime1;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "cntime2", length = 15)
	public Date getCntime2() {
		return this.cntime2;
	}

	public void setCntime2(Date cntime2) {
		this.cntime2 = cntime2;
	}

	@Column(name = "bt_code", nullable = false, length = 6)
	public String getBtCode() {
		return this.btCode;
	}

	public void setBtCode(String btCode) {
		this.btCode = btCode;
	}

	@Column(name = "cref", nullable = false, length = 25)
	public String getCref() {
		return this.cref;
	}

	public void setCref(String cref) {
		this.cref = cref;
	}

	@Column(name = "altbt_code", nullable = false, length = 6)
	public String getAltbtCode() {
		return this.altbtCode;
	}

	public void setAltbtCode(String altbtCode) {
		this.altbtCode = altbtCode;
	}

	@Column(name = "ratetbl", nullable = false, length = 4)
	public String getRatetbl() {
		return this.ratetbl;
	}

	public void setRatetbl(String ratetbl) {
		this.ratetbl = ratetbl;
	}

	@Column(name = "spq", nullable = false, length = 1)
	public String getSpq() {
		return this.spq;
	}

	public void setSpq(String spq) {
		this.spq = spq;
	}

	@Column(name = "units", nullable = false)
	public int getUnits() {
		return this.units;
	}

	public void setUnits(int units) {
		this.units = units;
	}

	@Column(name = "frtchg", nullable = false, precision = 16)
	public BigDecimal getFrtchg() {
		return this.frtchg;
	}

	public void setFrtchg(BigDecimal frtchg) {
		this.frtchg = frtchg;
	}

	@Column(name = "accchg", nullable = false, precision = 16)
	public BigDecimal getAccchg() {
		return this.accchg;
	}

	public void setAccchg(BigDecimal accchg) {
		this.accchg = accchg;
	}

	@Column(name = "totchg", nullable = false, precision = 16)
	public BigDecimal getTotchg() {
		return this.totchg;
	}

	public void setTotchg(BigDecimal totchg) {
		this.totchg = totchg;
	}

	@Column(name = "origby", nullable = false, length = 20)
	public String getOrigby() {
		return this.origby;
	}

	public void setOrigby(String origby) {
		this.origby = origby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "origdt", length = 13)
	public Date getOrigdt() {
		return this.origdt;
	}

	public void setOrigdt(Date origdt) {
		this.origdt = origdt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "origtm", length = 15)
	public Date getOrigtm() {
		return this.origtm;
	}

	public void setOrigtm(Date origtm) {
		this.origtm = origtm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fwupdt", length = 13)
	public Date getFwupdt() {
		return this.fwupdt;
	}

	public void setFwupdt(Date fwupdt) {
		this.fwupdt = fwupdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "portdt", length = 13)
	public Date getPortdt() {
		return this.portdt;
	}

	public void setPortdt(Date portdt) {
		this.portdt = portdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "avaldt", length = 13)
	public Date getAvaldt() {
		return this.avaldt;
	}

	public void setAvaldt(Date avaldt) {
		this.avaldt = avaldt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "freedt", length = 13)
	public Date getFreedt() {
		return this.freedt;
	}

	public void setFreedt(Date freedt) {
		this.freedt = freedt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reldt", length = 13)
	public Date getReldt() {
		return this.reldt;
	}

	public void setReldt(Date reldt) {
		this.reldt = reldt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "reltm", length = 15)
	public Date getReltm() {
		return this.reltm;
	}

	public void setReltm(Date reltm) {
		this.reltm = reltm;
	}

	@Column(name = "rellogin", nullable = false, length = 8)
	public String getRellogin() {
		return this.rellogin;
	}

	public void setRellogin(String rellogin) {
		this.rellogin = rellogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "defdt", length = 13)
	public Date getDefdt() {
		return this.defdt;
	}

	public void setDefdt(Date defdt) {
		this.defdt = defdt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "deftm", length = 15)
	public Date getDeftm() {
		return this.deftm;
	}

	public void setDeftm(Date deftm) {
		this.deftm = deftm;
	}

	@Column(name = "deflogin", nullable = false, length = 8)
	public String getDeflogin() {
		return this.deflogin;
	}

	public void setDeflogin(String deflogin) {
		this.deflogin = deflogin;
	}

	@Column(name = "noa", nullable = false, length = 1)
	public String getNoa() {
		return this.noa;
	}

	public void setNoa(String noa) {
		this.noa = noa;
	}

	@Column(name = "cmdy_code", nullable = false, length = 9)
	public String getCmdyCode() {
		return this.cmdyCode;
	}

	public void setCmdyCode(String cmdyCode) {
		this.cmdyCode = cmdyCode;
	}

	@Column(name = "pieces", nullable = false)
	public int getPieces() {
		return this.pieces;
	}

	public void setPieces(int pieces) {
		this.pieces = pieces;
	}

	@Column(name = "weight", nullable = false)
	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	@Column(name = "seal", nullable = false, length = 20)
	public String getSeal() {
		return this.seal;
	}

	public void setSeal(String seal) {
		this.seal = seal;
	}

	@Column(name = "booking", nullable = false, length = 20)
	public String getBooking() {
		return this.booking;
	}

	public void setBooking(String booking) {
		this.booking = booking;
	}

	@Column(name = "vessel", nullable = false, length = 20)
	public String getVessel() {
		return this.vessel;
	}

	public void setVessel(String vessel) {
		this.vessel = vessel;
	}

	@Column(name = "oversea", nullable = false, length = 20)
	public String getOversea() {
		return this.oversea;
	}

	public void setOversea(String oversea) {
		this.oversea = oversea;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "codt", length = 13)
	public Date getCodt() {
		return this.codt;
	}

	public void setCodt(Date codt) {
		this.codt = codt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "cotm", length = 15)
	public Date getCotm() {
		return this.cotm;
	}

	public void setCotm(Date cotm) {
		this.cotm = cotm;
	}

	@Column(name = "broker", nullable = false, length = 20)
	public String getBroker() {
		return this.broker;
	}

	public void setBroker(String broker) {
		this.broker = broker;
	}

	@Column(name = "brokerref", nullable = false, length = 20)
	public String getBrokerref() {
		return this.brokerref;
	}

	public void setBrokerref(String brokerref) {
		this.brokerref = brokerref;
	}

	@Column(name = "oceanbol", nullable = false, length = 80)
	public String getOceanbol() {
		return this.oceanbol;
	}

	public void setOceanbol(String oceanbol) {
		this.oceanbol = oceanbol;
	}

	@Column(name = "tlolp_code", nullable = false, length = 6)
	public String getTlolpCode() {
		return this.tlolpCode;
	}

	public void setTlolpCode(String tlolpCode) {
		this.tlolpCode = tlolpCode;
	}

	@Column(name = "tloname", nullable = false, length = 30)
	public String getTloname() {
		return this.tloname;
	}

	public void setTloname(String tloname) {
		this.tloname = tloname;
	}

	@Column(name = "tlocity", nullable = false, length = 20)
	public String getTlocity() {
		return this.tlocity;
	}

	public void setTlocity(String tlocity) {
		this.tlocity = tlocity;
	}

	@Column(name = "tlost_code", nullable = false, length = 2)
	public String getTlostCode() {
		return this.tlostCode;
	}

	public void setTlostCode(String tlostCode) {
		this.tlostCode = tlostCode;
	}

	@Column(name = "tlocty_no", nullable = false)
	public int getTloctyNo() {
		return this.tloctyNo;
	}

	public void setTloctyNo(int tloctyNo) {
		this.tloctyNo = tloctyNo;
	}

	@Column(name = "tltlp_code", nullable = false, length = 6)
	public String getTltlpCode() {
		return this.tltlpCode;
	}

	public void setTltlpCode(String tltlpCode) {
		this.tltlpCode = tltlpCode;
	}

	@Column(name = "tltname", nullable = false, length = 30)
	public String getTltname() {
		return this.tltname;
	}

	public void setTltname(String tltname) {
		this.tltname = tltname;
	}

	@Column(name = "tltcity", nullable = false, length = 20)
	public String getTltcity() {
		return this.tltcity;
	}

	public void setTltcity(String tltcity) {
		this.tltcity = tltcity;
	}

	@Column(name = "tltst_code", nullable = false, length = 2)
	public String getTltstCode() {
		return this.tltstCode;
	}

	public void setTltstCode(String tltstCode) {
		this.tltstCode = tltstCode;
	}

	@Column(name = "tltcty_no", nullable = false)
	public int getTltctyNo() {
		return this.tltctyNo;
	}

	public void setTltctyNo(int tltctyNo) {
		this.tltctyNo = tltctyNo;
	}

	@Column(name = "ldmty", nullable = false, length = 1)
	public String getLdmty() {
		return this.ldmty;
	}

	public void setLdmty(String ldmty) {
		this.ldmty = ldmty;
	}

	@Column(name = "ok2inv", nullable = false, length = 1)
	public String getOk2inv() {
		return this.ok2inv;
	}

	public void setOk2inv(String ok2inv) {
		this.ok2inv = ok2inv;
	}

	@Column(name = "rgn_code", nullable = false, length = 3)
	public String getRgnCode() {
		return this.rgnCode;
	}

	public void setRgnCode(String rgnCode) {
		this.rgnCode = rgnCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adate", length = 13)
	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "atime", length = 15)
	public Date getAtime() {
		return this.atime;
	}

	public void setAtime(Date atime) {
		this.atime = atime;
	}

	@Column(name = "alogin", nullable = false, length = 8)
	public String getAlogin() {
		return this.alogin;
	}

	public void setAlogin(String alogin) {
		this.alogin = alogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "udate", length = 13)
	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "utime", length = 15)
	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	@Column(name = "ulogin", nullable = false, length = 8)
	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	@Column(name = "cmdyhaz", nullable = false, length = 1)
	public String getCmdyhaz() {
		return this.cmdyhaz;
	}

	public void setCmdyhaz(String cmdyhaz) {
		this.cmdyhaz = cmdyhaz;
	}

	@Column(name = "cmdydesc", nullable = false, length = 25)
	public String getCmdydesc() {
		return this.cmdydesc;
	}

	public void setCmdydesc(String cmdydesc) {
		this.cmdydesc = cmdydesc;
	}

	@Column(name = "done", nullable = false, length = 1)
	public String getDone() {
		return this.done;
	}

	public void setDone(String done) {
		this.done = done;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "donedt", length = 13)
	public Date getDonedt() {
		return this.donedt;
	}

	public void setDonedt(Date donedt) {
		this.donedt = donedt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "donetm", length = 15)
	public Date getDonetm() {
		return this.donetm;
	}

	public void setDonetm(Date donetm) {
		this.donetm = donetm;
	}

	@Column(name = "donelogin", nullable = false, length = 8)
	public String getDonelogin() {
		return this.donelogin;
	}

	public void setDonelogin(String donelogin) {
		this.donelogin = donelogin;
	}

	@Column(name = "defprev", nullable = false, length = 1)
	public String getDefprev() {
		return this.defprev;
	}

	public void setDefprev(String defprev) {
		this.defprev = defprev;
	}

	@Column(name = "tltype", nullable = false, length = 1)
	public String getTltype() {
		return this.tltype;
	}

	public void setTltype(String tltype) {
		this.tltype = tltype;
	}

	@Column(name = "tl2type", nullable = false, length = 1)
	public String getTl2type() {
		return this.tl2type;
	}

	public void setTl2type(String tl2type) {
		this.tl2type = tl2type;
	}

	@Column(name = "chtype", nullable = false, length = 1)
	public String getChtype() {
		return this.chtype;
	}

	public void setChtype(String chtype) {
		this.chtype = chtype;
	}

	@Column(name = "ch2type", nullable = false, length = 2)
	public String getCh2type() {
		return this.ch2type;
	}

	public void setCh2type(String ch2type) {
		this.ch2type = ch2type;
	}

	@Column(name = "csr", nullable = false, length = 8)
	public String getCsr() {
		return this.csr;
	}

	public void setCsr(String csr) {
		this.csr = csr;
	}

	@Column(name = "oneway", nullable = false, length = 1)
	public String getOneway() {
		return this.oneway;
	}

	public void setOneway(String oneway) {
		this.oneway = oneway;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "invdt", length = 13)
	public Date getInvdt() {
		return this.invdt;
	}

	public void setInvdt(Date invdt) {
		this.invdt = invdt;
	}

	@Column(name = "ok2pay", nullable = false, length = 1)
	public String getOk2pay() {
		return this.ok2pay;
	}

	public void setOk2pay(String ok2pay) {
		this.ok2pay = ok2pay;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "paydt", length = 13)
	public Date getPaydt() {
		return this.paydt;
	}

	public void setPaydt(Date paydt) {
		this.paydt = paydt;
	}

	@Column(name = "vn_code1", nullable = false, length = 6)
	public String getVnCode1() {
		return this.vnCode1;
	}

	public void setVnCode1(String vnCode1) {
		this.vnCode1 = vnCode1;
	}

	@Column(name = "vn_code2", nullable = false, length = 6)
	public String getVnCode2() {
		return this.vnCode2;
	}

	public void setVnCode2(String vnCode2) {
		this.vnCode2 = vnCode2;
	}

	@Column(name = "vn_code3", nullable = false, length = 6)
	public String getVnCode3() {
		return this.vnCode3;
	}

	public void setVnCode3(String vnCode3) {
		this.vnCode3 = vnCode3;
	}

	@Column(name = "vnamt1", nullable = false, precision = 16)
	public BigDecimal getVnamt1() {
		return this.vnamt1;
	}

	public void setVnamt1(BigDecimal vnamt1) {
		this.vnamt1 = vnamt1;
	}

	@Column(name = "vnamt2", nullable = false, precision = 16)
	public BigDecimal getVnamt2() {
		return this.vnamt2;
	}

	public void setVnamt2(BigDecimal vnamt2) {
		this.vnamt2 = vnamt2;
	}

	@Column(name = "vnamt3", nullable = false, precision = 16)
	public BigDecimal getVnamt3() {
		return this.vnamt3;
	}

	public void setVnamt3(BigDecimal vnamt3) {
		this.vnamt3 = vnamt3;
	}

	@Column(name = "tarfamt", nullable = false, precision = 16)
	public BigDecimal getTarfamt() {
		return this.tarfamt;
	}

	public void setTarfamt(BigDecimal tarfamt) {
		this.tarfamt = tarfamt;
	}

	@Column(name = "fscpercent", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getFscpercent() {
		return this.fscpercent;
	}

	public void setFscpercent(BigDecimal fscpercent) {
		this.fscpercent = fscpercent;
	}

	@Column(name = "fscamt", nullable = false, precision = 16)
	public BigDecimal getFscamt() {
		return this.fscamt;
	}

	public void setFscamt(BigDecimal fscamt) {
		this.fscamt = fscamt;
	}

	@Column(name = "totvn", nullable = false, precision = 16)
	public BigDecimal getTotvn() {
		return this.totvn;
	}

	public void setTotvn(BigDecimal totvn) {
		this.totvn = totvn;
	}

	@Column(name = "totdr", nullable = false, precision = 16)
	public BigDecimal getTotdr() {
		return this.totdr;
	}

	public void setTotdr(BigDecimal totdr) {
		this.totdr = totdr;
	}

	@Column(name = "totacrud", nullable = false, precision = 16)
	public BigDecimal getTotacrud() {
		return this.totacrud;
	}

	public void setTotacrud(BigDecimal totacrud) {
		this.totacrud = totacrud;
	}

	@Column(name = "profit", nullable = false, precision = 16)
	public BigDecimal getProfit() {
		return this.profit;
	}

	public void setProfit(BigDecimal profit) {
		this.profit = profit;
	}

	@Column(name = "margin", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getMargin() {
		return this.margin;
	}

	public void setMargin(BigDecimal margin) {
		this.margin = margin;
	}

	@Column(name = "qty", nullable = false)
	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pdate", length = 13)
	public Date getPdate() {
		return this.pdate;
	}

	public void setPdate(Date pdate) {
		this.pdate = pdate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "ptime", length = 15)
	public Date getPtime() {
		return this.ptime;
	}

	public void setPtime(Date ptime) {
		this.ptime = ptime;
	}

	@Column(name = "vnflag1", nullable = false, length = 1)
	public String getVnflag1() {
		return this.vnflag1;
	}

	public void setVnflag1(String vnflag1) {
		this.vnflag1 = vnflag1;
	}

	@Column(name = "vnflag2", nullable = false, length = 1)
	public String getVnflag2() {
		return this.vnflag2;
	}

	public void setVnflag2(String vnflag2) {
		this.vnflag2 = vnflag2;
	}

	@Column(name = "vnflag3", nullable = false, length = 1)
	public String getVnflag3() {
		return this.vnflag3;
	}

	public void setVnflag3(String vnflag3) {
		this.vnflag3 = vnflag3;
	}

	@Column(name = "e204_no", nullable = false)
	public int getE204No() {
		return this.e204No;
	}

	public void setE204No(int e204No) {
		this.e204No = e204No;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deldt", length = 13)
	public Date getDeldt() {
		return this.deldt;
	}

	public void setDeldt(Date deldt) {
		this.deldt = deldt;
	}

	@Column(name = "fcramt", nullable = false, precision = 16)
	public BigDecimal getFcramt() {
		return this.fcramt;
	}

	public void setFcramt(BigDecimal fcramt) {
		this.fcramt = fcramt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "deltm", length = 15)
	public Date getDeltm() {
		return this.deltm;
	}

	public void setDeltm(Date deltm) {
		this.deltm = deltm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pudt", length = 13)
	public Date getPudt() {
		return this.pudt;
	}

	public void setPudt(Date pudt) {
		this.pudt = pudt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "putm", length = 15)
	public Date getPutm() {
		return this.putm;
	}

	public void setPutm(Date putm) {
		this.putm = putm;
	}

	@Column(name = "haz_code", nullable = false, length = 10)
	public String getHazCode() {
		return this.hazCode;
	}

	public void setHazCode(String hazCode) {
		this.hazCode = hazCode;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "esoamt", nullable = false, precision = 16)
	public BigDecimal getEsoamt() {
		return this.esoamt;
	}

	public void setEsoamt(BigDecimal esoamt) {
		this.esoamt = esoamt;
	}

	@Column(name = "esodiv_code", nullable = false, length = 2)
	public String getEsodivCode() {
		return this.esodivCode;
	}

	public void setEsodivCode(String esodivCode) {
		this.esodivCode = esodivCode;
	}

	@Column(name = "esopro", nullable = false, length = 9)
	public String getEsopro() {
		return this.esopro;
	}

	public void setEsopro(String esopro) {
		this.esopro = esopro;
	}

	@Column(name = "brkdiv_code", nullable = false, length = 2)
	public String getBrkdivCode() {
		return this.brkdivCode;
	}

	public void setBrkdivCode(String brkdivCode) {
		this.brkdivCode = brkdivCode;
	}

	@Column(name = "brkpro", nullable = false, length = 9)
	public String getBrkpro() {
		return this.brkpro;
	}

	public void setBrkpro(String brkpro) {
		this.brkpro = brkpro;
	}

	@Column(name = "altref", nullable = false, length = 25)
	public String getAltref() {
		return this.altref;
	}

	public void setAltref(String altref) {
		this.altref = altref;
	}

	@Column(name = "mbdiv_code", nullable = false, length = 2)
	public String getMbdivCode() {
		return this.mbdivCode;
	}

	public void setMbdivCode(String mbdivCode) {
		this.mbdivCode = mbdivCode;
	}

	@Column(name = "mbpro", nullable = false, length = 9)
	public String getMbpro() {
		return this.mbpro;
	}

	public void setMbpro(String mbpro) {
		this.mbpro = mbpro;
	}

	@Column(name = "cost", nullable = false, precision = 16)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "rebate", nullable = false, precision = 16)
	public BigDecimal getRebate() {
		return this.rebate;
	}

	public void setRebate(BigDecimal rebate) {
		this.rebate = rebate;
	}

	@Column(name = "actcost", nullable = false, precision = 16)
	public BigDecimal getActcost() {
		return this.actcost;
	}

	public void setActcost(BigDecimal actcost) {
		this.actcost = actcost;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "avaltm", length = 15)
	public Date getAvaltm() {
		return this.avaltm;
	}

	public void setAvaltm(Date avaltm) {
		this.avaltm = avaltm;
	}

	@Column(name = "cmdyref", nullable = false, length = 1)
	public String getCmdyref() {
		return this.cmdyref;
	}

	public void setCmdyref(String cmdyref) {
		this.cmdyref = cmdyref;
	}

	@Column(name = "altedi_code", nullable = false, length = 6)
	public String getAltediCode() {
		return this.altediCode;
	}

	public void setAltediCode(String altediCode) {
		this.altediCode = altediCode;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "porttm", length = 15)
	public Date getPorttm() {
		return this.porttm;
	}

	public void setPorttm(Date porttm) {
		this.porttm = porttm;
	}

	@Column(name = "lotloc", nullable = false, length = 10)
	public String getLotloc() {
		return this.lotloc;
	}

	public void setLotloc(String lotloc) {
		this.lotloc = lotloc;
	}

	@Column(name = "tpolp_code", nullable = false, length = 6)
	public String getTpolpCode() {
		return this.tpolpCode;
	}

	public void setTpolpCode(String tpolpCode) {
		this.tpolpCode = tpolpCode;
	}

	@Column(name = "tponame", nullable = false, length = 30)
	public String getTponame() {
		return this.tponame;
	}

	public void setTponame(String tponame) {
		this.tponame = tponame;
	}

	@Column(name = "tpocity", nullable = false, length = 20)
	public String getTpocity() {
		return this.tpocity;
	}

	public void setTpocity(String tpocity) {
		this.tpocity = tpocity;
	}

	@Column(name = "tpost_code", nullable = false, length = 2)
	public String getTpostCode() {
		return this.tpostCode;
	}

	public void setTpostCode(String tpostCode) {
		this.tpostCode = tpostCode;
	}

	@Column(name = "tpocty_no", nullable = false)
	public int getTpoctyNo() {
		return this.tpoctyNo;
	}

	public void setTpoctyNo(int tpoctyNo) {
		this.tpoctyNo = tpoctyNo;
	}

	@Column(name = "tptlp_code", nullable = false, length = 6)
	public String getTptlpCode() {
		return this.tptlpCode;
	}

	public void setTptlpCode(String tptlpCode) {
		this.tptlpCode = tptlpCode;
	}

	@Column(name = "tptname", nullable = false, length = 30)
	public String getTptname() {
		return this.tptname;
	}

	public void setTptname(String tptname) {
		this.tptname = tptname;
	}

	@Column(name = "tptcity", nullable = false, length = 20)
	public String getTptcity() {
		return this.tptcity;
	}

	public void setTptcity(String tptcity) {
		this.tptcity = tptcity;
	}

	@Column(name = "tptst_code", nullable = false, length = 2)
	public String getTptstCode() {
		return this.tptstCode;
	}

	public void setTptstCode(String tptstCode) {
		this.tptstCode = tptstCode;
	}

	@Column(name = "tptcty_no", nullable = false)
	public int getTptctyNo() {
		return this.tptctyNo;
	}

	public void setTptctyNo(int tptctyNo) {
		this.tptctyNo = tptctyNo;
	}

	@Column(name = "shdays", nullable = false)
	public int getShdays() {
		return this.shdays;
	}

	public void setShdays(int shdays) {
		this.shdays = shdays;
	}

	@Column(name = "cndays", nullable = false)
	public int getCndays() {
		return this.cndays;
	}

	public void setCndays(int cndays) {
		this.cndays = cndays;
	}

	@Column(name = "portflag", nullable = false, length = 1)
	public String getPortflag() {
		return this.portflag;
	}

	public void setPortflag(String portflag) {
		this.portflag = portflag;
	}

	@Column(name = "avalflag", nullable = false, length = 1)
	public String getAvalflag() {
		return this.avalflag;
	}

	public void setAvalflag(String avalflag) {
		this.avalflag = avalflag;
	}

	@Column(name = "lfdflag", nullable = false, length = 1)
	public String getLfdflag() {
		return this.lfdflag;
	}

	public void setLfdflag(String lfdflag) {
		this.lfdflag = lfdflag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "perdlfd", length = 13)
	public Date getPerdlfd() {
		return this.perdlfd;
	}

	public void setPerdlfd(Date perdlfd) {
		this.perdlfd = perdlfd;
	}

	@Column(name = "perdflag", nullable = false, length = 1)
	public String getPerdflag() {
		return this.perdflag;
	}

	public void setPerdflag(String perdflag) {
		this.perdflag = perdflag;
	}

	@Column(name = "ratequide", nullable = false, length = 3)
	public String getRatequide() {
		return this.ratequide;
	}

	public void setRatequide(String ratequide) {
		this.ratequide = ratequide;
	}

	@Column(name = "ratever", nullable = false, length = 5)
	public String getRatever() {
		return this.ratever;
	}

	public void setRatever(String ratever) {
		this.ratever = ratever;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rbrdydt", length = 13)
	public Date getRbrdydt() {
		return this.rbrdydt;
	}

	public void setRbrdydt(Date rbrdydt) {
		this.rbrdydt = rbrdydt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "rbrdytm", length = 15)
	public Date getRbrdytm() {
		return this.rbrdytm;
	}

	public void setRbrdytm(Date rbrdytm) {
		this.rbrdytm = rbrdytm;
	}

	@Column(name = "rbrdyflag", nullable = false, length = 1)
	public String getRbrdyflag() {
		return this.rbrdyflag;
	}

	public void setRbrdyflag(String rbrdyflag) {
		this.rbrdyflag = rbrdyflag;
	}

	@Column(name = "rbsend", nullable = false, length = 30)
	public String getRbsend() {
		return this.rbsend;
	}

	public void setRbsend(String rbsend) {
		this.rbsend = rbsend;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rbsenddt", length = 13)
	public Date getRbsenddt() {
		return this.rbsenddt;
	}

	public void setRbsenddt(Date rbsenddt) {
		this.rbsenddt = rbsenddt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "rbsendtm", length = 15)
	public Date getRbsendtm() {
		return this.rbsendtm;
	}

	public void setRbsendtm(Date rbsendtm) {
		this.rbsendtm = rbsendtm;
	}

	@Column(name = "hotflag", nullable = false, length = 1)
	public String getHotflag() {
		return this.hotflag;
	}

	public void setHotflag(String hotflag) {
		this.hotflag = hotflag;
	}

	@Column(name = "reftemp", nullable = false, length = 10)
	public String getReftemp() {
		return this.reftemp;
	}

	public void setReftemp(String reftemp) {
		this.reftemp = reftemp;
	}

	@Column(name = "custfscmiles", nullable = false)
	public int getCustfscmiles() {
		return this.custfscmiles;
	}

	public void setCustfscmiles(int custfscmiles) {
		this.custfscmiles = custfscmiles;
	}

	@Column(name = "origcountry_code", nullable = false, length = 3)
	public String getOrigcountryCode() {
		return this.origcountryCode;
	}

	public void setOrigcountryCode(String origcountryCode) {
		this.origcountryCode = origcountryCode;
	}

	@Column(name = "perdbt_code", nullable = false, length = 6)
	public String getPerdbtCode() {
		return this.perdbtCode;
	}

	public void setPerdbtCode(String perdbtCode) {
		this.perdbtCode = perdbtCode;
	}

	@Column(name = "perdbtref", nullable = false, length = 25)
	public String getPerdbtref() {
		return this.perdbtref;
	}

	public void setPerdbtref(String perdbtref) {
		this.perdbtref = perdbtref;
	}

	@Column(name = "division_id", length = 16)
	public String getDivisionId() {
		return this.divisionId;
	}

	public void setDivisionId(String divisionId) {
		this.divisionId = divisionId;
	}

	@Column(name = "customer_billto_id", length = 16)
	public String getCustomerBilltoId() {
		return this.customerBilltoId;
	}

	public void setCustomerBilltoId(String customerBilltoId) {
		this.customerBilltoId = customerBilltoId;
	}

	@Column(name = "alt_shipper_billto_id", length = 16)
	public String getAltShipperBilltoId() {
		return this.altShipperBilltoId;
	}

	public void setAltShipperBilltoId(String altShipperBilltoId) {
		this.altShipperBilltoId = altShipperBilltoId;
	}

	@Column(name = "chassis_dp_eqmast_id", length = 16)
	public String getChassisDpEqmastId() {
		return this.chassisDpEqmastId;
	}

	public void setChassisDpEqmastId(String chassisDpEqmastId) {
		this.chassisDpEqmastId = chassisDpEqmastId;
	}

	@Column(name = "chassis_eqmast_id", length = 16)
	public String getChassisEqmastId() {
		return this.chassisEqmastId;
	}

	public void setChassisEqmastId(String chassisEqmastId) {
		this.chassisEqmastId = chassisEqmastId;
	}

	@Column(name = "trailer_dp_eqmast_id", length = 16)
	public String getTrailerDpEqmastId() {
		return this.trailerDpEqmastId;
	}

	public void setTrailerDpEqmastId(String trailerDpEqmastId) {
		this.trailerDpEqmastId = trailerDpEqmastId;
	}

	@Column(name = "trailer_eqmast_id", length = 16)
	public String getTrailerEqmastId() {
		return this.trailerEqmastId;
	}

	public void setTrailerEqmastId(String trailerEqmastId) {
		this.trailerEqmastId = trailerEqmastId;
	}

	@Column(name = "chassis_dp_orig_locprof_id", length = 16)
	public String getChassisDpOrigLocprofId() {
		return this.chassisDpOrigLocprofId;
	}

	public void setChassisDpOrigLocprofId(String chassisDpOrigLocprofId) {
		this.chassisDpOrigLocprofId = chassisDpOrigLocprofId;
	}

	@Column(name = "chassis_dp_term_locprof_id", length = 16)
	public String getChassisDpTermLocprofId() {
		return this.chassisDpTermLocprofId;
	}

	public void setChassisDpTermLocprofId(String chassisDpTermLocprofId) {
		this.chassisDpTermLocprofId = chassisDpTermLocprofId;
	}

	@Column(name = "chassis_orig_locprof_id", length = 16)
	public String getChassisOrigLocprofId() {
		return this.chassisOrigLocprofId;
	}

	public void setChassisOrigLocprofId(String chassisOrigLocprofId) {
		this.chassisOrigLocprofId = chassisOrigLocprofId;
	}

	@Column(name = "chassis_term_locprof_id", length = 16)
	public String getChassisTermLocprofId() {
		return this.chassisTermLocprofId;
	}

	public void setChassisTermLocprofId(String chassisTermLocprofId) {
		this.chassisTermLocprofId = chassisTermLocprofId;
	}

	@Column(name = "consignee_locprof_id", length = 16)
	public String getConsigneeLocprofId() {
		return this.consigneeLocprofId;
	}

	public void setConsigneeLocprofId(String consigneeLocprofId) {
		this.consigneeLocprofId = consigneeLocprofId;
	}

	@Column(name = "shipper_locprof_id", length = 16)
	public String getShipperLocprofId() {
		return this.shipperLocprofId;
	}

	public void setShipperLocprofId(String shipperLocprofId) {
		this.shipperLocprofId = shipperLocprofId;
	}

	@Column(name = "trailer_orig_locprof_id", length = 16)
	public String getTrailerOrigLocprofId() {
		return this.trailerOrigLocprofId;
	}

	public void setTrailerOrigLocprofId(String trailerOrigLocprofId) {
		this.trailerOrigLocprofId = trailerOrigLocprofId;
	}

	@Column(name = "trailer_term_locprof_id", length = 16)
	public String getTrailerTermLocprofId() {
		return this.trailerTermLocprofId;
	}

	public void setTrailerTermLocprofId(String trailerTermLocprofId) {
		this.trailerTermLocprofId = trailerTermLocprofId;
	}

	@Column(name = "trip_orig_locprof_id", length = 16)
	public String getTripOrigLocprofId() {
		return this.tripOrigLocprofId;
	}

	public void setTripOrigLocprofId(String tripOrigLocprofId) {
		this.tripOrigLocprofId = tripOrigLocprofId;
	}

	@Column(name = "trip_term_locprof_id", length = 16)
	public String getTripTermLocprofId() {
		return this.tripTermLocprofId;
	}

	public void setTripTermLocprofId(String tripTermLocprofId) {
		this.tripTermLocprofId = tripTermLocprofId;
	}

	@Column(name = "billtl_code", nullable = false, length = 10)
	public String getBilltlCode() {
		return this.billtlCode;
	}

	public void setBilltlCode(String billtlCode) {
		this.billtlCode = billtlCode;
	}

	@Column(name = "billtl_chkdig", nullable = false, length = 1)
	public String getBilltlChkdig() {
		return this.billtlChkdig;
	}

	public void setBilltlChkdig(String billtlChkdig) {
		this.billtlChkdig = billtlChkdig;
	}

	@Column(name = "billtl_relnum", nullable = false, length = 20)
	public String getBilltlRelnum() {
		return this.billtlRelnum;
	}

	public void setBilltlRelnum(String billtlRelnum) {
		this.billtlRelnum = billtlRelnum;
	}

	@Column(name = "billtl_size", nullable = false, length = 5)
	public String getBilltlSize() {
		return this.billtlSize;
	}

	public void setBilltlSize(String billtlSize) {
		this.billtlSize = billtlSize;
	}

	@Column(name = "billtl_eqocode", nullable = false, length = 6)
	public String getBilltlEqocode() {
		return this.billtlEqocode;
	}

	public void setBilltlEqocode(String billtlEqocode) {
		this.billtlEqocode = billtlEqocode;
	}

	@Column(name = "billch_code", nullable = false, length = 10)
	public String getBillchCode() {
		return this.billchCode;
	}

	public void setBillchCode(String billchCode) {
		this.billchCode = billchCode;
	}

	@Column(name = "billch_chkdig", nullable = false, length = 1)
	public String getBillchChkdig() {
		return this.billchChkdig;
	}

	public void setBillchChkdig(String billchChkdig) {
		this.billchChkdig = billchChkdig;
	}

	@Column(name = "billch_relnum", nullable = false, length = 20)
	public String getBillchRelnum() {
		return this.billchRelnum;
	}

	public void setBillchRelnum(String billchRelnum) {
		this.billchRelnum = billchRelnum;
	}

	@Column(name = "billch_size", nullable = false, length = 5)
	public String getBillchSize() {
		return this.billchSize;
	}

	public void setBillchSize(String billchSize) {
		this.billchSize = billchSize;
	}

	@Column(name = "billch_eqocode", nullable = false, length = 6)
	public String getBillchEqocode() {
		return this.billchEqocode;
	}

	public void setBillchEqocode(String billchEqocode) {
		this.billchEqocode = billchEqocode;
	}

	@Column(name = "chorig_lp_code", nullable = false, length = 6)
	public String getChorigLpCode() {
		return this.chorigLpCode;
	}

	public void setChorigLpCode(String chorigLpCode) {
		this.chorigLpCode = chorigLpCode;
	}

	@Column(name = "chorig_name", nullable = false, length = 30)
	public String getChorigName() {
		return this.chorigName;
	}

	public void setChorigName(String chorigName) {
		this.chorigName = chorigName;
	}

	@Column(name = "chorig_city", nullable = false, length = 20)
	public String getChorigCity() {
		return this.chorigCity;
	}

	public void setChorigCity(String chorigCity) {
		this.chorigCity = chorigCity;
	}

	@Column(name = "chorig_st_code", nullable = false, length = 2)
	public String getChorigStCode() {
		return this.chorigStCode;
	}

	public void setChorigStCode(String chorigStCode) {
		this.chorigStCode = chorigStCode;
	}

	@Column(name = "chorig_cty_no", nullable = false)
	public int getChorigCtyNo() {
		return this.chorigCtyNo;
	}

	public void setChorigCtyNo(int chorigCtyNo) {
		this.chorigCtyNo = chorigCtyNo;
	}

	@Column(name = "chorig_gpslong", nullable = false, precision = 7, scale = 4)
	public BigDecimal getChorigGpslong() {
		return this.chorigGpslong;
	}

	public void setChorigGpslong(BigDecimal chorigGpslong) {
		this.chorigGpslong = chorigGpslong;
	}

	@Column(name = "chorig_gpslat", nullable = false, precision = 6, scale = 4)
	public BigDecimal getChorigGpslat() {
		return this.chorigGpslat;
	}

	public void setChorigGpslat(BigDecimal chorigGpslat) {
		this.chorigGpslat = chorigGpslat;
	}

	@Column(name = "chterm_lp_code", nullable = false, length = 6)
	public String getChtermLpCode() {
		return this.chtermLpCode;
	}

	public void setChtermLpCode(String chtermLpCode) {
		this.chtermLpCode = chtermLpCode;
	}

	@Column(name = "chterm_name", nullable = false, length = 30)
	public String getChtermName() {
		return this.chtermName;
	}

	public void setChtermName(String chtermName) {
		this.chtermName = chtermName;
	}

	@Column(name = "chterm_city", nullable = false, length = 20)
	public String getChtermCity() {
		return this.chtermCity;
	}

	public void setChtermCity(String chtermCity) {
		this.chtermCity = chtermCity;
	}

	@Column(name = "chterm_st_code", nullable = false, length = 2)
	public String getChtermStCode() {
		return this.chtermStCode;
	}

	public void setChtermStCode(String chtermStCode) {
		this.chtermStCode = chtermStCode;
	}

	@Column(name = "chterm_cty_no", nullable = false)
	public int getChtermCtyNo() {
		return this.chtermCtyNo;
	}

	public void setChtermCtyNo(int chtermCtyNo) {
		this.chtermCtyNo = chtermCtyNo;
	}

	@Column(name = "chterm_gpslong", nullable = false, precision = 7, scale = 4)
	public BigDecimal getChtermGpslong() {
		return this.chtermGpslong;
	}

	public void setChtermGpslong(BigDecimal chtermGpslong) {
		this.chtermGpslong = chtermGpslong;
	}

	@Column(name = "chterm_gpslat", nullable = false, precision = 6, scale = 4)
	public BigDecimal getChtermGpslat() {
		return this.chtermGpslat;
	}

	public void setChtermGpslat(BigDecimal chtermGpslat) {
		this.chtermGpslat = chtermGpslat;
	}

	@Column(name = "dptl_code", nullable = false, length = 10)
	public String getDptlCode() {
		return this.dptlCode;
	}

	public void setDptlCode(String dptlCode) {
		this.dptlCode = dptlCode;
	}

	@Column(name = "dptl_chkdig", nullable = false, length = 1)
	public String getDptlChkdig() {
		return this.dptlChkdig;
	}

	public void setDptlChkdig(String dptlChkdig) {
		this.dptlChkdig = dptlChkdig;
	}

	@Column(name = "dptl_relnum", nullable = false, length = 20)
	public String getDptlRelnum() {
		return this.dptlRelnum;
	}

	public void setDptlRelnum(String dptlRelnum) {
		this.dptlRelnum = dptlRelnum;
	}

	@Column(name = "dptl_size", nullable = false, length = 5)
	public String getDptlSize() {
		return this.dptlSize;
	}

	public void setDptlSize(String dptlSize) {
		this.dptlSize = dptlSize;
	}

	@Column(name = "dptl_eqocode", nullable = false, length = 6)
	public String getDptlEqocode() {
		return this.dptlEqocode;
	}

	public void setDptlEqocode(String dptlEqocode) {
		this.dptlEqocode = dptlEqocode;
	}

	@Column(name = "dpch_code", nullable = false, length = 10)
	public String getDpchCode() {
		return this.dpchCode;
	}

	public void setDpchCode(String dpchCode) {
		this.dpchCode = dpchCode;
	}

	@Column(name = "dpch_chkdig", nullable = false, length = 1)
	public String getDpchChkdig() {
		return this.dpchChkdig;
	}

	public void setDpchChkdig(String dpchChkdig) {
		this.dpchChkdig = dpchChkdig;
	}

	@Column(name = "dpch_relnum", nullable = false, length = 20)
	public String getDpchRelnum() {
		return this.dpchRelnum;
	}

	public void setDpchRelnum(String dpchRelnum) {
		this.dpchRelnum = dpchRelnum;
	}

	@Column(name = "dpch_size", nullable = false, length = 5)
	public String getDpchSize() {
		return this.dpchSize;
	}

	public void setDpchSize(String dpchSize) {
		this.dpchSize = dpchSize;
	}

	@Column(name = "dpch_eqocode", nullable = false, length = 6)
	public String getDpchEqocode() {
		return this.dpchEqocode;
	}

	public void setDpchEqocode(String dpchEqocode) {
		this.dpchEqocode = dpchEqocode;
	}

	@Column(name = "tpoggpslong", nullable = false, precision = 7, scale = 4)
	public BigDecimal getTpoggpslong() {
		return this.tpoggpslong;
	}

	public void setTpoggpslong(BigDecimal tpoggpslong) {
		this.tpoggpslong = tpoggpslong;
	}

	@Column(name = "tpoggpslat", nullable = false, precision = 6, scale = 4)
	public BigDecimal getTpoggpslat() {
		return this.tpoggpslat;
	}

	public void setTpoggpslat(BigDecimal tpoggpslat) {
		this.tpoggpslat = tpoggpslat;
	}

	@Column(name = "tptgpslong", nullable = false, precision = 7, scale = 4)
	public BigDecimal getTptgpslong() {
		return this.tptgpslong;
	}

	public void setTptgpslong(BigDecimal tptgpslong) {
		this.tptgpslong = tptgpslong;
	}

	@Column(name = "tptgpslat", nullable = false, precision = 6, scale = 4)
	public BigDecimal getTptgpslat() {
		return this.tptgpslat;
	}

	public void setTptgpslat(BigDecimal tptgpslat) {
		this.tptgpslat = tptgpslat;
	}

	@Column(name = "chorig_ref", nullable = false, length = 21)
	public String getChorigRef() {
		return this.chorigRef;
	}

	public void setChorigRef(String chorigRef) {
		this.chorigRef = chorigRef;
	}

	@Column(name = "tlorig_ref", nullable = false, length = 21)
	public String getTlorigRef() {
		return this.tlorigRef;
	}

	public void setTlorigRef(String tlorigRef) {
		this.tlorigRef = tlorigRef;
	}

	@Column(name = "tlterm_ref", nullable = false, length = 21)
	public String getTltermRef() {
		return this.tltermRef;
	}

	public void setTltermRef(String tltermRef) {
		this.tltermRef = tltermRef;
	}

	@Column(name = "chterm_ref", nullable = false, length = 21)
	public String getChtermRef() {
		return this.chtermRef;
	}

	public void setChtermRef(String chtermRef) {
		this.chtermRef = chtermRef;
	}

	@Column(name = "tporef", nullable = false, length = 21)
	public String getTporef() {
		return this.tporef;
	}

	public void setTporef(String tporef) {
		this.tporef = tporef;
	}

	@Column(name = "tptref", nullable = false, length = 21)
	public String getTptref() {
		return this.tptref;
	}

	public void setTptref(String tptref) {
		this.tptref = tptref;
	}

	@Column(name = "dmtype", nullable = false, length = 1)
	public String getDmtype() {
		return this.dmtype;
	}

	public void setDmtype(String dmtype) {
		this.dmtype = dmtype;
	}

	@Column(name = "chzsupply", nullable = false, length = 1)
	public String getChzsupply() {
		return this.chzsupply;
	}

	public void setChzsupply(String chzsupply) {
		this.chzsupply = chzsupply;
	}

	@Column(name = "chzchoice", nullable = false, length = 1)
	public String getChzchoice() {
		return this.chzchoice;
	}

	public void setChzchoice(String chzchoice) {
		this.chzchoice = chzchoice;
	}

	@Column(name = "chzdefeqocode", nullable = false, length = 6)
	public String getChzdefeqocode() {
		return this.chzdefeqocode;
	}

	public void setChzdefeqocode(String chzdefeqocode) {
		this.chzdefeqocode = chzdefeqocode;
	}

	@Column(name = "chzdefupceqocode", nullable = false, length = 6)
	public String getChzdefupceqocode() {
		return this.chzdefupceqocode;
	}

	public void setChzdefupceqocode(String chzdefupceqocode) {
		this.chzdefupceqocode = chzdefupceqocode;
	}

	@Column(name = "billch_upceqocode", nullable = false, length = 6)
	public String getBillchUpceqocode() {
		return this.billchUpceqocode;
	}

	public void setBillchUpceqocode(String billchUpceqocode) {
		this.billchUpceqocode = billchUpceqocode;
	}

	@Column(name = "ratetblno", nullable = false)
	public int getRatetblno() {
		return this.ratetblno;
	}

	public void setRatetblno(int ratetblno) {
		this.ratetblno = ratetblno;
	}

	@Column(name = "t100fscamt", nullable = false, precision = 16)
	public BigDecimal getT100fscamt() {
		return this.t100fscamt;
	}

	public void setT100fscamt(BigDecimal t100fscamt) {
		this.t100fscamt = t100fscamt;
	}

	@Column(name = "t100fscpercent", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getT100fscpercent() {
		return this.t100fscpercent;
	}

	public void setT100fscpercent(BigDecimal t100fscpercent) {
		this.t100fscpercent = t100fscpercent;
	}

	@Column(name = "t100accchg", nullable = false, precision = 16)
	public BigDecimal getT100accchg() {
		return this.t100accchg;
	}

	public void setT100accchg(BigDecimal t100accchg) {
		this.t100accchg = t100accchg;
	}

	@Column(name = "t100totchg", nullable = false, precision = 16)
	public BigDecimal getT100totchg() {
		return this.t100totchg;
	}

	public void setT100totchg(BigDecimal t100totchg) {
		this.t100totchg = t100totchg;
	}

	@Column(name = "chzamt", nullable = false, precision = 16)
	public BigDecimal getChzamt() {
		return this.chzamt;
	}

	public void setChzamt(BigDecimal chzamt) {
		this.chzamt = chzamt;
	}

	@Column(name = "t100chzamt", nullable = false, precision = 16)
	public BigDecimal getT100chzamt() {
		return this.t100chzamt;
	}

	public void setT100chzamt(BigDecimal t100chzamt) {
		this.t100chzamt = t100chzamt;
	}

	@Column(name = "chztotvn", nullable = false, precision = 16)
	public BigDecimal getChztotvn() {
		return this.chztotvn;
	}

	public void setChztotvn(BigDecimal chztotvn) {
		this.chztotvn = chztotvn;
	}

	@Column(name = "route_guide", nullable = false, length = 7)
	public String getRouteGuide() {
		return this.routeGuide;
	}

	public void setRouteGuide(String routeGuide) {
		this.routeGuide = routeGuide;
	}

	@Column(name = "route_ver", nullable = false, length = 5)
	public String getRouteVer() {
		return this.routeVer;
	}

	public void setRouteVer(String routeVer) {
		this.routeVer = routeVer;
	}

	@Column(name = "route_method", nullable = false, length = 1)
	public String getRouteMethod() {
		return this.routeMethod;
	}

	public void setRouteMethod(String routeMethod) {
		this.routeMethod = routeMethod;
	}

	@Column(name = "route_miletype", nullable = false, length = 1)
	public String getRouteMiletype() {
		return this.routeMiletype;
	}

	public void setRouteMiletype(String routeMiletype) {
		this.routeMiletype = routeMiletype;
	}

	@Column(name = "t100route_guide", nullable = false, length = 7)
	public String getT100routeGuide() {
		return this.t100routeGuide;
	}

	public void setT100routeGuide(String t100routeGuide) {
		this.t100routeGuide = t100routeGuide;
	}

	@Column(name = "t100route_ver", nullable = false, length = 5)
	public String getT100routeVer() {
		return this.t100routeVer;
	}

	public void setT100routeVer(String t100routeVer) {
		this.t100routeVer = t100routeVer;
	}

	@Column(name = "t100route_method", nullable = false, length = 1)
	public String getT100routeMethod() {
		return this.t100routeMethod;
	}

	public void setT100routeMethod(String t100routeMethod) {
		this.t100routeMethod = t100routeMethod;
	}

	@Column(name = "t100route_miletype", nullable = false, length = 1)
	public String getT100routeMiletype() {
		return this.t100routeMiletype;
	}

	public void setT100routeMiletype(String t100routeMiletype) {
		this.t100routeMiletype = t100routeMiletype;
	}

	@Column(name = "haz_code_mty", length = 10)
	public String getHazCodeMty() {
		return this.hazCodeMty;
	}

	public void setHazCodeMty(String hazCodeMty) {
		this.hazCodeMty = hazCodeMty;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "chzstartdt", length = 13)
	public Date getChzstartdt() {
		return this.chzstartdt;
	}

	public void setChzstartdt(Date chzstartdt) {
		this.chzstartdt = chzstartdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "chzstopdt", length = 13)
	public Date getChzstopdt() {
		return this.chzstopdt;
	}

	public void setChzstopdt(Date chzstopdt) {
		this.chzstopdt = chzstopdt;
	}

	@Column(name = "chzusagedays", nullable = false)
	public int getChzusagedays() {
		return this.chzusagedays;
	}

	public void setChzusagedays(int chzusagedays) {
		this.chzusagedays = chzusagedays;
	}

	@Column(name = "chzprofit", nullable = false, precision = 16)
	public BigDecimal getChzprofit() {
		return this.chzprofit;
	}

	public void setChzprofit(BigDecimal chzprofit) {
		this.chzprofit = chzprofit;
	}

	@Column(name = "profitchz", nullable = false, precision = 16)
	public BigDecimal getProfitchz() {
		return this.profitchz;
	}

	public void setProfitchz(BigDecimal profitchz) {
		this.profitchz = profitchz;
	}

	@Column(name = "marginchz", nullable = false, precision = 131089, scale = 0)
	public BigDecimal getMarginchz() {
		return this.marginchz;
	}

	public void setMarginchz(BigDecimal marginchz) {
		this.marginchz = marginchz;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "chzvnstartdt", length = 13)
	public Date getChzvnstartdt() {
		return this.chzvnstartdt;
	}

	public void setChzvnstartdt(Date chzvnstartdt) {
		this.chzvnstartdt = chzvnstartdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "chzvnstopdt", length = 13)
	public Date getChzvnstopdt() {
		return this.chzvnstopdt;
	}

	public void setChzvnstopdt(Date chzvnstopdt) {
		this.chzvnstopdt = chzvnstopdt;
	}

	@Column(name = "chzvnusagedays", nullable = false)
	public int getChzvnusagedays() {
		return this.chzvnusagedays;
	}

	public void setChzvnusagedays(int chzvnusagedays) {
		this.chzvnusagedays = chzvnusagedays;
	}

	@Column(name = "chzflags", nullable = false, length = 10)
	public String getChzflags() {
		return this.chzflags;
	}

	public void setChzflags(String chzflags) {
		this.chzflags = chzflags;
	}

	@Column(name = "chzvnamt", nullable = false, precision = 16)
	public BigDecimal getChzvnamt() {
		return this.chzvnamt;
	}

	public void setChzvnamt(BigDecimal chzvnamt) {
		this.chzvnamt = chzvnamt;
	}

	@Column(name = "custprod_code", length = 6)
	public String getCustprodCode() {
		return this.custprodCode;
	}

	public void setCustprodCode(String custprodCode) {
		this.custprodCode = custprodCode;
	}

	@Column(name = "isbrokerage", nullable = false, length = 1)
	public String getIsbrokerage() {
		return this.isbrokerage;
	}

	public void setIsbrokerage(String isbrokerage) {
		this.isbrokerage = isbrokerage;
	}

	@Column(name = "billtl_type", nullable = false, length = 1)
	public String getBilltlType() {
		return this.billtlType;
	}

	public void setBilltlType(String billtlType) {
		this.billtlType = billtlType;
	}

	@Column(name = "billtl_isvalid", nullable = false, length = 1)
	public String getBilltlIsvalid() {
		return this.billtlIsvalid;
	}

	public void setBilltlIsvalid(String billtlIsvalid) {
		this.billtlIsvalid = billtlIsvalid;
	}

	@Column(name = "billch_type", nullable = false, length = 1)
	public String getBillchType() {
		return this.billchType;
	}

	public void setBillchType(String billchType) {
		this.billchType = billchType;
	}

	@Column(name = "billch_isvalid", nullable = false, length = 1)
	public String getBillchIsvalid() {
		return this.billchIsvalid;
	}

	public void setBillchIsvalid(String billchIsvalid) {
		this.billchIsvalid = billchIsvalid;
	}

	@Column(name = "dptl_type", nullable = false, length = 1)
	public String getDptlType() {
		return this.dptlType;
	}

	public void setDptlType(String dptlType) {
		this.dptlType = dptlType;
	}

	@Column(name = "dptl_isvalid", nullable = false, length = 1)
	public String getDptlIsvalid() {
		return this.dptlIsvalid;
	}

	public void setDptlIsvalid(String dptlIsvalid) {
		this.dptlIsvalid = dptlIsvalid;
	}

	@Column(name = "dpch_type", nullable = false, length = 1)
	public String getDpchType() {
		return this.dpchType;
	}

	public void setDpchType(String dpchType) {
		this.dpchType = dpchType;
	}

	@Column(name = "dpch_isvalid", nullable = false, length = 1)
	public String getDpchIsvalid() {
		return this.dpchIsvalid;
	}

	public void setDpchIsvalid(String dpchIsvalid) {
		this.dpchIsvalid = dpchIsvalid;
	}

	@Column(name = "chzpassdays", nullable = false)
	public int getChzpassdays() {
		return this.chzpassdays;
	}

	public void setChzpassdays(int chzpassdays) {
		this.chzpassdays = chzpassdays;
	}

	@Column(name = "revtype", nullable = false, length = 1)
	public String getRevtype() {
		return this.revtype;
	}

	public void setRevtype(String revtype) {
		this.revtype = revtype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Move> getMoves() {
		return this.moves;
	}

	public void setMoves(Set<Move> moves) {
		this.moves = moves;
	}

}
