package com.imc.driver.wait.service.entities;

// Generated May 21, 2015 5:06:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userid generated by hbm2java
 */
@Entity
@Table(name = "userid")
public class Userid implements java.io.Serializable {

	private String code;
	private String name;
	private String email;
	private String divCode;
	private String dmsite;
	private Date adate;
	private Date atime;
	private String alogin;
	private Date udate;
	private Date utime;
	private String ulogin;
	private String mrcmpyCode;
	private String mrsiteCode;
	private String startpgm;
	private String position;
	private int cmpyNo;
	private String status;
	private Date verifiedDate;
	private Date lastActivityDate;
	private char extranet;
	private String serversCode;
	private String useemail;
	private String groupemail;
	private String tmpServersCode;

	public Userid() {
	}

	public Userid(String code, String name, String email, String divCode,
			String dmsite, String alogin, String ulogin, String mrcmpyCode,
			String mrsiteCode, String startpgm, String position, int cmpyNo,
			String status, char extranet, String serversCode, String useemail,
			String groupemail, String tmpServersCode) {
		this.code = code;
		this.name = name;
		this.email = email;
		this.divCode = divCode;
		this.dmsite = dmsite;
		this.alogin = alogin;
		this.ulogin = ulogin;
		this.mrcmpyCode = mrcmpyCode;
		this.mrsiteCode = mrsiteCode;
		this.startpgm = startpgm;
		this.position = position;
		this.cmpyNo = cmpyNo;
		this.status = status;
		this.extranet = extranet;
		this.serversCode = serversCode;
		this.useemail = useemail;
		this.groupemail = groupemail;
		this.tmpServersCode = tmpServersCode;
	}

	public Userid(String code, String name, String email, String divCode,
			String dmsite, Date adate, Date atime, String alogin, Date udate,
			Date utime, String ulogin, String mrcmpyCode, String mrsiteCode,
			String startpgm, String position, int cmpyNo, String status,
			Date verifiedDate, Date lastActivityDate, char extranet,
			String serversCode, String useemail, String groupemail,
			String tmpServersCode) {
		this.code = code;
		this.name = name;
		this.email = email;
		this.divCode = divCode;
		this.dmsite = dmsite;
		this.adate = adate;
		this.atime = atime;
		this.alogin = alogin;
		this.udate = udate;
		this.utime = utime;
		this.ulogin = ulogin;
		this.mrcmpyCode = mrcmpyCode;
		this.mrsiteCode = mrsiteCode;
		this.startpgm = startpgm;
		this.position = position;
		this.cmpyNo = cmpyNo;
		this.status = status;
		this.verifiedDate = verifiedDate;
		this.lastActivityDate = lastActivityDate;
		this.extranet = extranet;
		this.serversCode = serversCode;
		this.useemail = useemail;
		this.groupemail = groupemail;
		this.tmpServersCode = tmpServersCode;
	}

	@Id
	@Column(name = "code", unique = true, nullable = false, length = 8)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 128)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "div_code", nullable = false, length = 2)
	public String getDivCode() {
		return this.divCode;
	}

	public void setDivCode(String divCode) {
		this.divCode = divCode;
	}

	@Column(name = "dmsite", nullable = false, length = 6)
	public String getDmsite() {
		return this.dmsite;
	}

	public void setDmsite(String dmsite) {
		this.dmsite = dmsite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adate", length = 13)
	public Date getAdate() {
		return this.adate;
	}

	public void setAdate(Date adate) {
		this.adate = adate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "atime", length = 15)
	public Date getAtime() {
		return this.atime;
	}

	public void setAtime(Date atime) {
		this.atime = atime;
	}

	@Column(name = "alogin", nullable = false, length = 8)
	public String getAlogin() {
		return this.alogin;
	}

	public void setAlogin(String alogin) {
		this.alogin = alogin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "udate", length = 13)
	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "utime", length = 15)
	public Date getUtime() {
		return this.utime;
	}

	public void setUtime(Date utime) {
		this.utime = utime;
	}

	@Column(name = "ulogin", nullable = false, length = 8)
	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	@Column(name = "mrcmpy_code", nullable = false, length = 2)
	public String getMrcmpyCode() {
		return this.mrcmpyCode;
	}

	public void setMrcmpyCode(String mrcmpyCode) {
		this.mrcmpyCode = mrcmpyCode;
	}

	@Column(name = "mrsite_code", nullable = false, length = 10)
	public String getMrsiteCode() {
		return this.mrsiteCode;
	}

	public void setMrsiteCode(String mrsiteCode) {
		this.mrsiteCode = mrsiteCode;
	}

	@Column(name = "startpgm", nullable = false, length = 10)
	public String getStartpgm() {
		return this.startpgm;
	}

	public void setStartpgm(String startpgm) {
		this.startpgm = startpgm;
	}

	@Column(name = "position", nullable = false, length = 1)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "cmpy_no", nullable = false)
	public int getCmpyNo() {
		return this.cmpyNo;
	}

	public void setCmpyNo(int cmpyNo) {
		this.cmpyNo = cmpyNo;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "verified_date", length = 13)
	public Date getVerifiedDate() {
		return this.verifiedDate;
	}

	public void setVerifiedDate(Date verifiedDate) {
		this.verifiedDate = verifiedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_activity_date", length = 13)
	public Date getLastActivityDate() {
		return this.lastActivityDate;
	}

	public void setLastActivityDate(Date lastActivityDate) {
		this.lastActivityDate = lastActivityDate;
	}

	@Column(name = "extranet", nullable = false, length = 1)
	public char getExtranet() {
		return this.extranet;
	}

	public void setExtranet(char extranet) {
		this.extranet = extranet;
	}

	@Column(name = "servers_code", nullable = false, length = 16)
	public String getServersCode() {
		return this.serversCode;
	}

	public void setServersCode(String serversCode) {
		this.serversCode = serversCode;
	}

	@Column(name = "useemail", nullable = false, length = 1)
	public String getUseemail() {
		return this.useemail;
	}

	public void setUseemail(String useemail) {
		this.useemail = useemail;
	}

	@Column(name = "groupemail", nullable = false, length = 8)
	public String getGroupemail() {
		return this.groupemail;
	}

	public void setGroupemail(String groupemail) {
		this.groupemail = groupemail;
	}

	@Column(name = "tmp_servers_code", nullable = false, length = 16)
	public String getTmpServersCode() {
		return this.tmpServersCode;
	}

	public void setTmpServersCode(String tmpServersCode) {
		this.tmpServersCode = tmpServersCode;
	}

}
