
package com.imc.data.access.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EfsAutomationDataAccessWS", targetNamespace = "http://impl.ws.access.data.automation.efs.imc.com/", wsdlLocation = "file:/C:/Users/bshipman/AppData/Local/Temp/tempdir4617200345304639151.tmp/EfsAutomationDataAccessWS_1.wsdl")
public class EfsAutomationDataAccessWS
    extends Service
{

    private final static URL EFSAUTOMATIONDATAACCESSWS_WSDL_LOCATION;
    private final static WebServiceException EFSAUTOMATIONDATAACCESSWS_EXCEPTION;
    private final static QName EFSAUTOMATIONDATAACCESSWS_QNAME = new QName("http://impl.ws.access.data.automation.efs.imc.com/", "EfsAutomationDataAccessWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/bshipman/AppData/Local/Temp/tempdir4617200345304639151.tmp/EfsAutomationDataAccessWS_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EFSAUTOMATIONDATAACCESSWS_WSDL_LOCATION = url;
        EFSAUTOMATIONDATAACCESSWS_EXCEPTION = e;
    }

    public EfsAutomationDataAccessWS() {
        super(__getWsdlLocation(), EFSAUTOMATIONDATAACCESSWS_QNAME);
    }

    public EfsAutomationDataAccessWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), EFSAUTOMATIONDATAACCESSWS_QNAME, features);
    }

    public EfsAutomationDataAccessWS(URL wsdlLocation) {
        super(wsdlLocation, EFSAUTOMATIONDATAACCESSWS_QNAME);
    }

    public EfsAutomationDataAccessWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EFSAUTOMATIONDATAACCESSWS_QNAME, features);
    }

    public EfsAutomationDataAccessWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EfsAutomationDataAccessWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EfsAutomationDataAccessService
     */
    @WebEndpoint(name = "EfsAutomationDataAccessWS")
    public EfsAutomationDataAccessService getEfsAutomationDataAccessWS() {
        return super.getPort(new QName("http://impl.ws.access.data.automation.efs.imc.com/", "EfsAutomationDataAccessWS"), EfsAutomationDataAccessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EfsAutomationDataAccessService
     */
    @WebEndpoint(name = "EfsAutomationDataAccessWS")
    public EfsAutomationDataAccessService getEfsAutomationDataAccessWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.access.data.automation.efs.imc.com/", "EfsAutomationDataAccessWS"), EfsAutomationDataAccessService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EFSAUTOMATIONDATAACCESSWS_EXCEPTION!= null) {
            throw EFSAUTOMATIONDATAACCESSWS_EXCEPTION;
        }
        return EFSAUTOMATIONDATAACCESSWS_WSDL_LOCATION;
    }

}
