
package com.imc.data.access.service;

import java.math.BigDecimal;
import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.imc.efs.automation.dto.CredentialsDTO;
import com.imc.efs.automation.dto.GpIntegrationDTO;
import com.imc.efs.automation.entities.Requests;
import com.imc.efs.automation.entities.Requesttypes;
import com.imc.efs.automation.entities.Status;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EfsAutomationDataAccessService", targetNamespace = "http://ws.access.data.automation.efs.imc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EfsAutomationDataAccessService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.data.access.service.Requests
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnRequestWithReference", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.ReturnRequestWithReference")
    @ResponseWrapper(localName = "returnRequestWithReferenceResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.ReturnRequestWithReferenceResponse")
    public Requests returnRequestWithReference(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkIfQualifiedVendor", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.CheckIfQualifiedVendor")
    @ResponseWrapper(localName = "checkIfQualifiedVendorResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.CheckIfQualifiedVendorResponse")
    public boolean checkIfQualifiedVendor(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.data.access.service.CredentialsDTO
     */
    @WebMethod(operationName = "GetEncryptedCredentials")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetEncryptedCredentials", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetEncryptedCredentials")
    @ResponseWrapper(localName = "GetEncryptedCredentialsResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetEncryptedCredentialsResponse")
    public CredentialsDTO getEncryptedCredentials(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEfsGpVendorIdByCompany", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetEfsGpVendorIdByCompany")
    @ResponseWrapper(localName = "getEfsGpVendorIdByCompanyResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetEfsGpVendorIdByCompanyResponse")
    public String getEfsGpVendorIdByCompany(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentFilePathsByRequestId", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetDocumentFilePathsByRequestId")
    @ResponseWrapper(localName = "getDocumentFilePathsByRequestIdResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetDocumentFilePathsByRequestIdResponse")
    public List<String> getDocumentFilePathsByRequestId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateRequest", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.UpdateRequest")
    @ResponseWrapper(localName = "updateRequestResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.UpdateRequestResponse")
    public int updateRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.data.access.service.Requests
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRequestsById", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetRequestsById")
    @ResponseWrapper(localName = "getRequestsByIdResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetRequestsByIdResponse")
    public Requests getRequestsById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDivisionByDriverId", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetDivisionByDriverId")
    @ResponseWrapper(localName = "getDivisionByDriverIdResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetDivisionByDriverIdResponse")
    public String getDivisionByDriverId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "integrateIssuance", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.IntegrateIssuance")
    @ResponseWrapper(localName = "integrateIssuanceResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.IntegrateIssuanceResponse")
    public void integrateIssuance(
        @WebParam(name = "arg0", targetNamespace = "")
        GpIntegrationDTO arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.imc.data.access.service.Requests>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRequestsOfStatusIssued", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetRequestsOfStatusIssued")
    @ResponseWrapper(localName = "getRequestsOfStatusIssuedResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetRequestsOfStatusIssuedResponse")
    public List<Requests> getRequestsOfStatusIssued()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "releaseAPHold", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.ReleaseAPHold")
    @ResponseWrapper(localName = "releaseAPHoldResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.ReleaseAPHoldResponse")
    public int releaseAPHold(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "executeRecievedIntegrations", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.ExecuteRecievedIntegrations")
    @ResponseWrapper(localName = "executeRecievedIntegrationsResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.ExecuteRecievedIntegrationsResponse")
    public void executeRecievedIntegrations(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.data.access.service.Requests
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAndReturnRequestWithReference", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.UpdateAndReturnRequestWithReference")
    @ResponseWrapper(localName = "updateAndReturnRequestWithReferenceResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.UpdateAndReturnRequestWithReferenceResponse")
    public Requests updateAndReturnRequestWithReference(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRequest", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.AddRequest")
    @ResponseWrapper(localName = "addRequestResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.AddRequestResponse")
    public int addRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEfsCheckLimitByUser", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetEfsCheckLimitByUser")
    @ResponseWrapper(localName = "getEfsCheckLimitByUserResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetEfsCheckLimitByUserResponse")
    public BigDecimal getEfsCheckLimitByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsersEfsCheckLimit", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetUsersEfsCheckLimit")
    @ResponseWrapper(localName = "getUsersEfsCheckLimitResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetUsersEfsCheckLimitResponse")
    public BigDecimal getUsersEfsCheckLimit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveDocument", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.SaveDocument")
    @ResponseWrapper(localName = "saveDocumentResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.SaveDocumentResponse")
    public void saveDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkIfFirstTimeVendor", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.CheckIfFirstTimeVendor")
    @ResponseWrapper(localName = "checkIfFirstTimeVendorResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.CheckIfFirstTimeVendorResponse")
    public boolean checkIfFirstTimeVendor(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.data.access.service.RequestTypes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRequestTypeById", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetRequestTypeById")
    @ResponseWrapper(localName = "getRequestTypeByIdResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetRequestTypeByIdResponse")
    public Requesttypes getRequestTypeById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.data.access.service.Requests
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAndReturnRequestWithReferences", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.AddAndReturnRequestWithReferences")
    @ResponseWrapper(localName = "addAndReturnRequestWithReferencesResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.AddAndReturnRequestWithReferencesResponse")
    public Requests addAndReturnRequestWithReferences(
        @WebParam(name = "arg0", targetNamespace = "")
        Requests arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.imc.data.access.service.Status
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.GetStatusResponse")
    public Status getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkIfDuplicateRequest", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.CheckIfDuplicateRequest")
    @ResponseWrapper(localName = "checkIfDuplicateRequestResponse", targetNamespace = "http://ws.access.data.automation.efs.imc.com/", className = "com.imc.data.access.service.CheckIfDuplicateRequestResponse")
    public boolean checkIfDuplicateRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
