
package com.imc.email.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmailService", targetNamespace = "http://email.service.imc.com", wsdlLocation = "file:/C:/Users/bshipman/AppData/Local/Temp/tempdir9202907122937186878.tmp/EmailService_1.wsdl")
public class EmailService
    extends Service
{

    private final static URL EMAILSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMAILSERVICE_EXCEPTION;
    private final static QName EMAILSERVICE_QNAME = new QName("http://email.service.imc.com", "EmailService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/bshipman/AppData/Local/Temp/tempdir9202907122937186878.tmp/EmailService_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMAILSERVICE_WSDL_LOCATION = url;
        EMAILSERVICE_EXCEPTION = e;
    }

    public EmailService() {
        super(__getWsdlLocation(), EMAILSERVICE_QNAME);
    }

    public EmailService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMAILSERVICE_QNAME, features);
    }

    public EmailService(URL wsdlLocation) {
        super(wsdlLocation, EMAILSERVICE_QNAME);
    }

    public EmailService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMAILSERVICE_QNAME, features);
    }

    public EmailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmailService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmailServicePortType
     */
    @WebEndpoint(name = "emailServicePort")
    public EmailServicePortType getEmailServicePort() {
        return super.getPort(new QName("http://email.service.imc.com", "emailServicePort"), EmailServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmailServicePortType
     */
    @WebEndpoint(name = "emailServicePort")
    public EmailServicePortType getEmailServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://email.service.imc.com", "emailServicePort"), EmailServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMAILSERVICE_EXCEPTION!= null) {
            throw EMAILSERVICE_EXCEPTION;
        }
        return EMAILSERVICE_WSDL_LOCATION;
    }

}
