
package com.imc.driver.wait.data.access.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DriverWaitDataAccessWS", targetNamespace = "http://impl.ws.access.data.wait.driver.imc.com/", wsdlLocation = "http://localhost:8080/imc-driver-wait-service-data-access-war/DriverWaitDataAccessWS?wsdl")
public class DriverWaitDataAccessWS
    extends Service
{

    private final static URL DRIVERWAITDATAACCESSWS_WSDL_LOCATION;
    private final static WebServiceException DRIVERWAITDATAACCESSWS_EXCEPTION;
    private final static QName DRIVERWAITDATAACCESSWS_QNAME = new QName("http://impl.ws.access.data.wait.driver.imc.com/", "DriverWaitDataAccessWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/imc-driver-wait-service-data-access-war/DriverWaitDataAccessWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRIVERWAITDATAACCESSWS_WSDL_LOCATION = url;
        DRIVERWAITDATAACCESSWS_EXCEPTION = e;
    }

    public DriverWaitDataAccessWS() {
        super(__getWsdlLocation(), DRIVERWAITDATAACCESSWS_QNAME);
    }

    public DriverWaitDataAccessWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRIVERWAITDATAACCESSWS_QNAME, features);
    }

    public DriverWaitDataAccessWS(URL wsdlLocation) {
        super(wsdlLocation, DRIVERWAITDATAACCESSWS_QNAME);
    }

    public DriverWaitDataAccessWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRIVERWAITDATAACCESSWS_QNAME, features);
    }

    public DriverWaitDataAccessWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DriverWaitDataAccessWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DriverWaitDataAccessService
     */
    @WebEndpoint(name = "DriverWaitDataAccessWS")
    public DriverWaitDataAccessService getDriverWaitDataAccessWS() {
        return super.getPort(new QName("http://impl.ws.access.data.wait.driver.imc.com/", "DriverWaitDataAccessWS"), DriverWaitDataAccessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DriverWaitDataAccessService
     */
    @WebEndpoint(name = "DriverWaitDataAccessWS")
    public DriverWaitDataAccessService getDriverWaitDataAccessWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.access.data.wait.driver.imc.com/", "DriverWaitDataAccessWS"), DriverWaitDataAccessService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRIVERWAITDATAACCESSWS_EXCEPTION!= null) {
            throw DRIVERWAITDATAACCESSWS_EXCEPTION;
        }
        return DRIVERWAITDATAACCESSWS_WSDL_LOCATION;
    }

}
