
package com.imc.driver.wait.data.access.ws;

import java.util.Date;
import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.imc.driver.wait.service.data.UserDetailsDTO;
import com.imc.driver.wait.service.entities.Driver;
import com.imc.driver.wait.service.entities.Drwait;
import com.imc.driver.wait.service.entities.DrwaitEventQueue;
import com.imc.driver.wait.service.entities.Locprof;
import com.imc.driver.wait.service.entities.Mcgps;
import com.imc.driver.wait.service.entities.Move;
import com.imc.driver.wait.service.entities.Orchrg;
import com.imc.driver.wait.service.entities.Order;
import com.imc.driver.wait.service.entities.Userid;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DriverWaitDataAccessService", targetNamespace = "http://ws.access.data.wait.driver.imc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DriverWaitDataAccessService {


    /**
     * 
     * @param userCode
     * @return
     *     returns com.imc.driver.wait.data.access.ws.Userid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetUserResponse")
    public Userid getUser(
        @WebParam(name = "userCode", targetNamespace = "")
        String userCode);

    /**
     * 
     * @param userCode
     * @return
     *     returns com.imc.driver.wait.data.access.ws.UserDetailsDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetUserDetails")
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetUserDetailsResponse")
    public UserDetailsDTO getUserDetails(
        @WebParam(name = "userCode", targetNamespace = "")
        String userCode);

    /**
     * 
     * @param includeProcessed
     * @param usrCode
     * @return
     *     returns java.util.List<com.imc.driver.wait.data.access.ws.DrwaitEventQueue>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDrwaitEvents", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetAllDrwaitEvents")
    @ResponseWrapper(localName = "getAllDrwaitEventsResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetAllDrwaitEventsResponse")
    public List<DrwaitEventQueue> getAllDrwaitEvents(
        @WebParam(name = "usrCode", targetNamespace = "")
        String usrCode,
        @WebParam(name = "includeProcessed", targetNamespace = "")
        boolean includeProcessed);

    /**
     * 
     * @param orNo
     * @param cmpyNo
     * @return
     *     returns com.imc.driver.wait.data.access.ws.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrder", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetOrder")
    @ResponseWrapper(localName = "getOrderResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetOrderResponse")
    public Order getOrder(
        @WebParam(name = "orNo", targetNamespace = "")
        int orNo,
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo);

    /**
     * 
     * @param targetDatetime
     * @param drCode
     * @param cmpyNo
     * @param toleranceInMinutes
     * @return
     *     returns java.util.List<com.imc.driver.wait.data.access.ws.Mcgps>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBreadcrumbs2", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetBreadcrumbs2")
    @ResponseWrapper(localName = "getBreadcrumbs2Response", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetBreadcrumbs2Response")
    public List<Mcgps> getBreadcrumbs2(
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo,
        @WebParam(name = "targetDatetime", targetNamespace = "")
        Date targetDatetime,
        @WebParam(name = "toleranceInMinutes", targetNamespace = "")
        int toleranceInMinutes,
        @WebParam(name = "drCode", targetNamespace = "")
        String drCode);

    /**
     * 
     * @param targetDatetime
     * @param cmpyNo
     * @param toleranceInMinutes
     * @return
     *     returns java.util.List<com.imc.driver.wait.data.access.ws.Mcgps>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBreadcrumbs3", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetBreadcrumbs3")
    @ResponseWrapper(localName = "getBreadcrumbs3Response", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetBreadcrumbs3Response")
    public List<Mcgps> getBreadcrumbs3(
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo,
        @WebParam(name = "targetDatetime", targetNamespace = "")
        Date targetDatetime,
        @WebParam(name = "toleranceInMinutes", targetNamespace = "")
        int toleranceInMinutes);

    /**
     * 
     * @param moveNo
     * @param cmpyNo
     * @return
     *     returns com.imc.driver.wait.data.access.ws.Move
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMove", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetMove")
    @ResponseWrapper(localName = "getMoveResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetMoveResponse")
    public Move getMove(
        @WebParam(name = "moveNo", targetNamespace = "")
        int moveNo,
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo);

    /**
     * 
     * @param move
     */
    @WebMethod
    @RequestWrapper(localName = "updateMove", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.UpdateMove")
    @ResponseWrapper(localName = "updateMoveResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.UpdateMoveResponse")
    public void updateMove(
        @WebParam(name = "move", targetNamespace = "")
        Move move);

    /**
     * 
     * @param drwaitEvent
     */
    @WebMethod
    @RequestWrapper(localName = "updateDrwaitEvent", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.UpdateDrwaitEvent")
    @ResponseWrapper(localName = "updateDrwaitEventResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.UpdateDrwaitEventResponse")
    public void updateDrwaitEvent(
        @WebParam(name = "drwaitEvent", targetNamespace = "")
        DrwaitEventQueue drwaitEvent);

    /**
     * 
     * @param importMoveNo
     * @param cmpyNo
     * @return
     *     returns com.imc.driver.wait.data.access.ws.Drwait
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByImportMoveNo", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetByImportMoveNo")
    @ResponseWrapper(localName = "getByImportMoveNoResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetByImportMoveNoResponse")
    public Drwait getByImportMoveNo(
        @WebParam(name = "importMoveNo", targetNamespace = "")
        int importMoveNo,
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo);

    /**
     * 
     * @param includeProcessed
     * @return
     *     returns java.util.List<com.imc.driver.wait.data.access.ws.DrwaitEventQueue>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDrwaitEventsAllUsers", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetAllDrwaitEventsAllUsers")
    @ResponseWrapper(localName = "getAllDrwaitEventsAllUsersResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetAllDrwaitEventsAllUsersResponse")
    public List<DrwaitEventQueue> getAllDrwaitEventsAllUsers(
        @WebParam(name = "includeProcessed", targetNamespace = "")
        boolean includeProcessed);

    /**
     * 
     * @param drCode
     * @param cmpyNo
     * @param endDatetime
     * @param startDatetime
     * @return
     *     returns java.util.List<com.imc.driver.wait.data.access.ws.Mcgps>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBreadcrumbs", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetBreadcrumbs")
    @ResponseWrapper(localName = "getBreadcrumbsResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetBreadcrumbsResponse")
    public List<Mcgps> getBreadcrumbs(
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo,
        @WebParam(name = "startDatetime", targetNamespace = "")
        Date startDatetime,
        @WebParam(name = "endDatetime", targetNamespace = "")
        Date endDatetime,
        @WebParam(name = "drCode", targetNamespace = "")
        String drCode);

    /**
     * 
     * @param drCode
     * @param cmpyNo
     * @return
     *     returns com.imc.driver.wait.data.access.ws.Driver
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDriverByCodeAndCmpyNo", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetDriverByCodeAndCmpyNo")
    @ResponseWrapper(localName = "getDriverByCodeAndCmpyNoResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetDriverByCodeAndCmpyNoResponse")
    public Driver getDriverByCodeAndCmpyNo(
        @WebParam(name = "drCode", targetNamespace = "")
        String drCode,
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo);

    /**
     * 
     * @param userCode
     * @param includeComplete
     * @return
     *     returns java.util.List<com.imc.driver.wait.data.access.ws.Drwait>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDrwaits", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetAllDrwaits")
    @ResponseWrapper(localName = "getAllDrwaitsResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetAllDrwaitsResponse")
    public List<Drwait> getAllDrwaits(
        @WebParam(name = "userCode", targetNamespace = "")
        String userCode,
        @WebParam(name = "includeComplete", targetNamespace = "")
        boolean includeComplete);

    /**
     * 
     * @param drwaitEvent
     */
    @WebMethod
    @RequestWrapper(localName = "insertDrwaitEvent", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.InsertDrwaitEvent")
    @ResponseWrapper(localName = "insertDrwaitEventResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.InsertDrwaitEventResponse")
    public void insertDrwaitEvent(
        @WebParam(name = "drwaitEvent", targetNamespace = "")
        DrwaitEventQueue drwaitEvent);

    /**
     * 
     * @param cmpyNo
     * @param exportMoveNo
     * @return
     *     returns com.imc.driver.wait.data.access.ws.Drwait
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByExportMoveNo", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetByExportMoveNo")
    @ResponseWrapper(localName = "getByExportMoveNoResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetByExportMoveNoResponse")
    public Drwait getByExportMoveNo(
        @WebParam(name = "exportMoveNo", targetNamespace = "")
        int exportMoveNo,
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo);

    /**
     * 
     * @param orchrg
     */
    @WebMethod
    @RequestWrapper(localName = "insertOrchrg", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.InsertOrchrg")
    @ResponseWrapper(localName = "insertOrchrgResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.InsertOrchrgResponse")
    public void insertOrchrg(
        @WebParam(name = "orchrg", targetNamespace = "")
        Orchrg orchrg);

    /**
     * 
     * @param cmpyNo
     * @param endDatetime
     * @param startDatetime
     * @return
     *     returns java.util.List<com.imc.driver.wait.data.access.ws.Mcgps>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBreadcrumbs4", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetBreadcrumbs4")
    @ResponseWrapper(localName = "getBreadcrumbs4Response", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetBreadcrumbs4Response")
    public List<Mcgps> getBreadcrumbs4(
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo,
        @WebParam(name = "startDatetime", targetNamespace = "")
        Date startDatetime,
        @WebParam(name = "endDatetime", targetNamespace = "")
        Date endDatetime);

    /**
     * 
     * @param driverWait
     */
    @WebMethod
    @RequestWrapper(localName = "insertDrwait", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.InsertDrwait")
    @ResponseWrapper(localName = "insertDrwaitResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.InsertDrwaitResponse")
    public void insertDrwait(
        @WebParam(name = "driverWait", targetNamespace = "")
        Drwait driverWait);

    /**
     * 
     * @param cmpyNo
     * @param lpCode
     * @return
     *     returns com.imc.driver.wait.data.access.ws.Locprof
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLocprof", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetLocprof")
    @ResponseWrapper(localName = "getLocprofResponse", targetNamespace = "http://ws.access.data.wait.driver.imc.com/", className = "com.imc.driver.wait.data.access.ws.GetLocprofResponse")
    public Locprof getLocprof(
        @WebParam(name = "lpCode", targetNamespace = "")
        String lpCode,
        @WebParam(name = "cmpyNo", targetNamespace = "")
        int cmpyNo);

}
