package com.imc.efs.automation.entities;

// Generated Apr 6, 2015 4:37:07 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Requesters generated by hbm2java
 */
//A list of dispatchers and their respective limit they may request
@Entity
@Table(name = "requesters", schema = "dbo")
public class Requesters implements java.io.Serializable {

	//unique ID
	private int id;
	//Request Type
	private Requesttypes requesttypes;
	//Requesters Name
	private String name;
	//Requesters Limit
	private BigDecimal limit;

	public Requesters() {
	}

	public Requesters(int id, Requesttypes requesttypes, BigDecimal limit) {
		this.id = id;
		this.requesttypes = requesttypes;
		this.limit = limit;
	}

	public Requesters(int id, Requesttypes requesttypes, String name,
			BigDecimal limit) {
		this.id = id;
		this.requesttypes = requesttypes;
		this.name = name;
		this.limit = limit;
	}

	@Id
	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RequestTypeId", nullable = false)
	public Requesttypes getRequesttypes() {
		return this.requesttypes;
	}

	public void setRequesttypes(Requesttypes requesttypes) {
		this.requesttypes = requesttypes;
	}

	@Column(name = "Name", length = 99)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Limit", nullable = false, precision = 18)
	public BigDecimal getLimit() {
		return this.limit;
	}

	public void setLimit(BigDecimal limit) {
		this.limit = limit;
	}

}
