package com.imc.efs.automation.entities;

// Generated Apr 6, 2015 4:37:07 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Requesttypes generated by hbm2java
 */
@Entity
@Table(name = "requesttypes", schema = "dbo")
public class Requesttypes implements java.io.Serializable {

	private int requestTypeId;
	private boolean isOpsPortalType;
	private boolean isDriverPay;
	private boolean requiresManagementApproval;
	private boolean requiresAuthorizedVendor;
	private boolean requiresInvoice;
	private boolean preventDuplicates;
	private String name;
	private short driverId;
	private short vendorId;
	private short serviceCharge;
	private short proNumber;
	private short poWoNumber;
	private short truckId;
	private short chassisNumber;
	private short containerNumber;
	private short claimNumber;
	private short claimType;
	private short tagEquipment;
	private short tagPurchType;
	private short isChargedToCustomer;
	private String issuanceDebit;
	private String issuanceCredit;
//	private List<Requesters> requesterses;
//	private List<Requesttypecomments> requesttypecommentses;
//	private List<Requests> requestses;

	public Requesttypes() {
	}

	public Requesttypes(int requestTypeId, boolean isOpsPortalType,
			boolean isDriverPay, boolean requiresManagementApproval,
			boolean requiresAuthorizedVendor, boolean requiresInvoice,
			boolean preventDuplicates, String name, short driverId,
			short vendorId, short serviceCharge, short proNumber,
			short poWoNumber, short truckId, short chassisNumber,
			short containerNumber, short claimNumber, short claimType,
			short tagEquipment, short tagPurchType, short isChargedToCustomer,
			String issuanceDebit) {
		this.requestTypeId = requestTypeId;
		this.isOpsPortalType = isOpsPortalType;
		this.isDriverPay = isDriverPay;
		this.requiresManagementApproval = requiresManagementApproval;
		this.requiresAuthorizedVendor = requiresAuthorizedVendor;
		this.requiresInvoice = requiresInvoice;
		this.preventDuplicates = preventDuplicates;
		this.name = name;
		this.driverId = driverId;
		this.vendorId = vendorId;
		this.serviceCharge = serviceCharge;
		this.proNumber = proNumber;
		this.poWoNumber = poWoNumber;
		this.truckId = truckId;
		this.chassisNumber = chassisNumber;
		this.containerNumber = containerNumber;
		this.claimNumber = claimNumber;
		this.claimType = claimType;
		this.tagEquipment = tagEquipment;
		this.tagPurchType = tagPurchType;
		this.isChargedToCustomer = isChargedToCustomer;
		this.issuanceDebit = issuanceDebit;
	}

//	public Requesttypes(int requestTypeId, boolean isOpsPortalType,
//			boolean isDriverPay, boolean requiresManagementApproval,
//			boolean requiresAuthorizedVendor, boolean requiresInvoice,
//			boolean preventDuplicates, String name, short driverId,
//			short vendorId, short serviceCharge, short proNumber,
//			short poWoNumber, short truckId, short chassisNumber,
//			short containerNumber, short claimNumber, short claimType,
//			short tagEquipment, short tagPurchType, short isChargedToCustomer,
//			String issuanceDebit, String issuanceCredit,
//			List<Requesters> requesterses,
//			List<Requesttypecomments> requesttypecommentses,
//			List<Requests> requestses) {
//		this.requestTypeId = requestTypeId;
//		this.isOpsPortalType = isOpsPortalType;
//		this.isDriverPay = isDriverPay;
//		this.requiresManagementApproval = requiresManagementApproval;
//		this.requiresAuthorizedVendor = requiresAuthorizedVendor;
//		this.requiresInvoice = requiresInvoice;
//		this.preventDuplicates = preventDuplicates;
//		this.name = name;
//		this.driverId = driverId;
//		this.vendorId = vendorId;
//		this.serviceCharge = serviceCharge;
//		this.proNumber = proNumber;
//		this.poWoNumber = poWoNumber;
//		this.truckId = truckId;
//		this.chassisNumber = chassisNumber;
//		this.containerNumber = containerNumber;
//		this.claimNumber = claimNumber;
//		this.claimType = claimType;
//		this.tagEquipment = tagEquipment;
//		this.tagPurchType = tagPurchType;
//		this.isChargedToCustomer = isChargedToCustomer;
//		this.issuanceDebit = issuanceDebit;
//		this.issuanceCredit = issuanceCredit;
//		this.requesterses = requesterses;
//		this.requesttypecommentses = requesttypecommentses;
//		this.requestses = requestses;
//	}

	@Id
	@Column(name = "RequestTypeId", nullable = false)
	public int getRequestTypeId() {
		return this.requestTypeId;
	}

	public void setRequestTypeId(int requestTypeId) {
		this.requestTypeId = requestTypeId;
	}

	@Column(name = "IsOpsPortalType", nullable = false)
	public boolean isIsOpsPortalType() {
		return this.isOpsPortalType;
	}

	public void setIsOpsPortalType(boolean isOpsPortalType) {
		this.isOpsPortalType = isOpsPortalType;
	}

	@Column(name = "IsDriverPay", nullable = false)
	public boolean isIsDriverPay() {
		return this.isDriverPay;
	}

	public void setIsDriverPay(boolean isDriverPay) {
		this.isDriverPay = isDriverPay;
	}

	@Column(name = "RequiresManagementApproval", nullable = false)
	public boolean isRequiresManagementApproval() {
		return this.requiresManagementApproval;
	}

	public void setRequiresManagementApproval(boolean requiresManagementApproval) {
		this.requiresManagementApproval = requiresManagementApproval;
	}

	@Column(name = "RequiresAuthorizedVendor", nullable = false)
	public boolean isRequiresAuthorizedVendor() {
		return this.requiresAuthorizedVendor;
	}

	public void setRequiresAuthorizedVendor(boolean requiresAuthorizedVendor) {
		this.requiresAuthorizedVendor = requiresAuthorizedVendor;
	}

	@Column(name = "RequiresInvoice", nullable = false)
	public boolean isRequiresInvoice() {
		return this.requiresInvoice;
	}

	public void setRequiresInvoice(boolean requiresInvoice) {
		this.requiresInvoice = requiresInvoice;
	}

	@Column(name = "PreventDuplicates", nullable = false)
	public boolean isPreventDuplicates() {
		return this.preventDuplicates;
	}

	public void setPreventDuplicates(boolean preventDuplicates) {
		this.preventDuplicates = preventDuplicates;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DriverId", nullable = false)
	public short getDriverId() {
		return this.driverId;
	}

	public void setDriverId(short driverId) {
		this.driverId = driverId;
	}

	@Column(name = "VendorId", nullable = false)
	public short getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(short vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "ServiceCharge", nullable = false)
	public short getServiceCharge() {
		return this.serviceCharge;
	}

	public void setServiceCharge(short serviceCharge) {
		this.serviceCharge = serviceCharge;
	}

	@Column(name = "ProNumber", nullable = false)
	public short getProNumber() {
		return this.proNumber;
	}

	public void setProNumber(short proNumber) {
		this.proNumber = proNumber;
	}

	@Column(name = "PoWoNumber", nullable = false)
	public short getPoWoNumber() {
		return this.poWoNumber;
	}

	public void setPoWoNumber(short poWoNumber) {
		this.poWoNumber = poWoNumber;
	}

	@Column(name = "TruckId", nullable = false)
	public short getTruckId() {
		return this.truckId;
	}

	public void setTruckId(short truckId) {
		this.truckId = truckId;
	}

	@Column(name = "ChassisNumber", nullable = false)
	public short getChassisNumber() {
		return this.chassisNumber;
	}

	public void setChassisNumber(short chassisNumber) {
		this.chassisNumber = chassisNumber;
	}

	@Column(name = "ContainerNumber", nullable = false)
	public short getContainerNumber() {
		return this.containerNumber;
	}

	public void setContainerNumber(short containerNumber) {
		this.containerNumber = containerNumber;
	}

	@Column(name = "ClaimNumber", nullable = false)
	public short getClaimNumber() {
		return this.claimNumber;
	}

	public void setClaimNumber(short claimNumber) {
		this.claimNumber = claimNumber;
	}

	@Column(name = "ClaimType", nullable = false)
	public short getClaimType() {
		return this.claimType;
	}

	public void setClaimType(short claimType) {
		this.claimType = claimType;
	}

	@Column(name = "TagEquipment", nullable = false)
	public short getTagEquipment() {
		return this.tagEquipment;
	}

	public void setTagEquipment(short tagEquipment) {
		this.tagEquipment = tagEquipment;
	}

	@Column(name = "TagPurchType", nullable = false)
	public short getTagPurchType() {
		return this.tagPurchType;
	}

	public void setTagPurchType(short tagPurchType) {
		this.tagPurchType = tagPurchType;
	}

	@Column(name = "IsChargedToCustomer", nullable = false)
	public short getIsChargedToCustomer() {
		return this.isChargedToCustomer;
	}

	public void setIsChargedToCustomer(short isChargedToCustomer) {
		this.isChargedToCustomer = isChargedToCustomer;
	}

	@Column(name = "IssuanceDebit", nullable = false, length = 9)
	public String getIssuanceDebit() {
		return this.issuanceDebit;
	}

	public void setIssuanceDebit(String issuanceDebit) {
		this.issuanceDebit = issuanceDebit;
	}

	@Column(name = "IssuanceCredit", length = 9)
	public String getIssuanceCredit() {
		return this.issuanceCredit;
	}

	public void setIssuanceCredit(String issuanceCredit) {
		this.issuanceCredit = issuanceCredit;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requesttypes")
//	public List<Requesters> getRequesterses() {
//		return this.requesterses;
//	}
//
//	public void setRequesterses(List<Requesters> requesterses) {
//		this.requesterses = requesterses;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requesttypes")
//	public List<Requesttypecomments> getRequesttypecommentses() {
//		return this.requesttypecommentses;
//	}
//
//	public void setRequesttypecommentses(
//			List<Requesttypecomments> requesttypecommentses) {
//		this.requesttypecommentses = requesttypecommentses;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requesttypes")
//	public List<Requests> getRequestses() {
//		return this.requestses;
//	}
//
//	public void setRequestses(List<Requests> requestses) {
//		this.requestses = requestses;
//	}

}
