package com.imc.efs.automation.entities;

// Generated Mar 16, 2015 4:02:11 PM by Hibernate Tools 4.0.0


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Requests generated by hbm2java
 */
@Entity
@Table(name = "requests", schema = "dbo")
public class Requests implements java.io.Serializable {

	private int requestId;
	private Status status;
	private Requesttypes requesttypes;
	private String company;
	private String requester;
	private String approver;
	private String issuer;
	private Integer contractId;
	private Date requestDate;
	private Date issueDate;
	private Date postDate;
	private Integer vendorId;
	private String vendorName;
	private String driverId;
	private BigDecimal efsAmount;
	private BigDecimal serviceCharge;
	private String glAccount;
	private String glDescription;
	private String proNumber;
	private String poWoNumber;
	private String truckId;
	private String chassisNumber;
	private String containerNumber;
	private String claimNumber;
	private String claimType;
	private String tagEquipment;
	private String tagPurchType;
	private String description;
	private Integer moneyCodeReferenceNumber;
	private String moneyCode;
	private String rejectionReason;
	private Short isChargedToCustomer;
	private String driverName;
//	private String pathToInvoice;
	private int requestTypeId;
	private int statusId;

	public Requests() {
	}

	public Requests(int requestId, Status status, Requesttypes requestTypes,
			String company, String requester, int contractId,
			Date requestDate, BigDecimal efsAmount) {
		this.requestId = requestId;
		this.status = status;
		this.requesttypes = requestTypes;
		this.company = company;
		this.requester = requester;
		this.contractId = contractId;
		this.requestDate = requestDate;
		this.efsAmount = efsAmount;
	}

	public Requests(int requestId, Status status, Requesttypes requestTypes,
			String company, String requester,
			String approver, String issuer, int contractId,
			Date requestDate, Date issueDate, Date postDate, Integer vendorId,
			String vendorName, String driverId,
			BigDecimal efsAmount, BigDecimal serviceCharge,
			String glAccount, String glDescription,
			String proNumber, String poWoNumber,
			String truckId, String chassisNumber,
			String containerNumber, String claimNumber,
			String claimType, String tagEquipment,
			String tagPurchType, String description,
			Integer moneyCodeReferenceNumber, String moneyCode,
			String rejectionReason, short isChargedToCustomer) {
		this.requestId = requestId;
		this.status = status;
		this.requesttypes = requestTypes;
		this.company = company;
		this.requester = requester;
		this.approver = approver;
		this.issuer = issuer;
		this.contractId = contractId;
		this.requestDate = requestDate;
		this.issueDate = issueDate;
		this.postDate = postDate;
		this.vendorId = vendorId;
		this.vendorName = vendorName;
		this.driverId = driverId;
		this.efsAmount = efsAmount;
		this.serviceCharge = serviceCharge;
		this.glAccount = glAccount;
		this.glDescription = glDescription;
		this.proNumber = proNumber;
		this.poWoNumber = poWoNumber;
		this.truckId = truckId;
		this.chassisNumber = chassisNumber;
		this.containerNumber = containerNumber;
		this.claimNumber = claimNumber;
		this.claimType = claimType;
		this.tagEquipment = tagEquipment;
		this.tagPurchType = tagPurchType;
		this.description = description;
		this.moneyCodeReferenceNumber = moneyCodeReferenceNumber;
		this.moneyCode = moneyCode;
		this.rejectionReason = rejectionReason;
		this.isChargedToCustomer = isChargedToCustomer;
	}

	@Id
    @SequenceGenerator(name="dbo.\"Requests_RequestId_seq\"",
                       sequenceName="dbo.\"Requests_RequestId_seq\"",
                       allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
                    generator="dbo.\"Requests_RequestId_seq\"")
	@Column(name = "RequestId", nullable = false)
	public int getRequestId() {
		return this.requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "StatusId", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RequestTypeId", nullable = false)
	public Requesttypes getRequesttypes() {
		return this.requesttypes;
	}

	public void setRequesttypes(Requesttypes requesttypes) {
		this.requesttypes = requesttypes;
	}

	@Column(name = "Company", nullable = false, length = 5)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "Requester", nullable = false, length = 50)
	public String getRequester() {
		return this.requester;
	}

	public void setRequester(String requester) {
		this.requester = requester;
	}

	@Column(name = "Approver", length = 50)
	public String getApprover() {
		return this.approver;
	}

	public void setApprover(String approver) {
		this.approver = approver;
	}

	@Column(name = "Issuer", length = 50)
	public String getIssuer() {
		return this.issuer;
	}

	public void setIssuer(String issuer) {
		this.issuer = issuer;
	}

	@Column(name = "ContractId")
	public Integer getContractId() {
		return this.contractId;
	}

	public void setContractId(Integer contractId) {
		this.contractId = contractId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RequestDate", nullable = false, length = 29)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IssueDate", length = 29)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostDate", length = 29)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Column(name = "VendorId")
	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "VendorName", length = 50)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "DriverId", length = 12)
	public String getDriverId() {
		return this.driverId;
	}

	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}

	@Column(name = "EfsAmount", nullable = false, precision = 18)
	public BigDecimal getEfsAmount() {
		return this.efsAmount;
	}

	public void setEfsAmount(BigDecimal efsAmount) {
		this.efsAmount = efsAmount;
	}

	@Column(name = "ServiceCharge", precision = 18)
	public BigDecimal getServiceCharge() {
		return this.serviceCharge;
	}

	public void setServiceCharge(BigDecimal serviceCharge) {
		this.serviceCharge = serviceCharge;
	}

	@Column(name = "GlAccount", length = 12)
	public String getGlAccount() {
		return this.glAccount;
	}

	public void setGlAccount(String glAccount) {
		this.glAccount = glAccount;
	}

	@Column(name = "GlDescription", length = 50)
	public String getGlDescription() {
		return this.glDescription;
	}

	public void setGlDescription(String glDescription) {
		this.glDescription = glDescription;
	}

	@Column(name = "ProNumber", length = 12)
	public String getProNumber() {
		return this.proNumber;
	}

	public void setProNumber(String proNumber) {
		this.proNumber = proNumber;
	}

	@Column(name = "PoWoNumber", length = 12)
	public String getPoWoNumber() {
		return this.poWoNumber;
	}

	public void setPoWoNumber(String poWoNumber) {
		this.poWoNumber = poWoNumber;
	}

	@Column(name = "TruckId", length = 12)
	public String getTruckId() {
		return this.truckId;
	}

	public void setTruckId(String truckId) {
		this.truckId = truckId;
	}

	@Column(name = "ChassisNumber", length = 12)
	public String getChassisNumber() {
		return this.chassisNumber;
	}

	public void setChassisNumber(String chassisNumber) {
		this.chassisNumber = chassisNumber;
	}

	@Column(name = "ContainerNumber", length = 12)
	public String getContainerNumber() {
		return this.containerNumber;
	}

	public void setContainerNumber(String containerNumber) {
		this.containerNumber = containerNumber;
	}

	@Column(name = "ClaimNumber", length = 25)
	public String getClaimNumber() {
		return this.claimNumber;
	}

	public void setClaimNumber(String claimNumber) {
		this.claimNumber = claimNumber;
	}

	@Column(name = "ClaimType", length = 15)
	public String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(String claimType) {
		this.claimType = claimType;
	}

	@Column(name = "TagEquipment", length = 20)
	public String getTagEquipment() {
		return this.tagEquipment;
	}

	public void setTagEquipment(String tagEquipment) {
		this.tagEquipment = tagEquipment;
	}

	@Column(name = "TagPurchType", length = 15)
	public String getTagPurchType() {
		return this.tagPurchType;
	}

	public void setTagPurchType(String tagPurchType) {
		this.tagPurchType = tagPurchType;
	}

	@Column(name = "Description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "MoneyCodeReferenceNumber")
	public Integer getMoneyCodeReferenceNumber() {
		return this.moneyCodeReferenceNumber;
	}

	public void setMoneyCodeReferenceNumber(Integer moneyCodeReferenceNumber) {
		this.moneyCodeReferenceNumber = moneyCodeReferenceNumber;
	}

	@Column(name = "MoneyCode", length = 25)
	public String getMoneyCode() {
		return this.moneyCode;
	}

	public void setMoneyCode(String moneyCode) {
		this.moneyCode = moneyCode;
	}

	@Column(name = "RejectionReason", length = 250)
	public String getRejectionReason() {
		return this.rejectionReason;
	}

	public void setRejectionReason(String rejectionReason) {
		this.rejectionReason = rejectionReason;
	}

	@Column(name = "IsChargedToCustomer")
	public Short getIsChargedToCustomer() {
		return this.isChargedToCustomer;
	}

	public void setIsChargedToCustomer(Short isChargedToCustomer) {
		this.isChargedToCustomer = isChargedToCustomer;
	}

	@Transient
	public String getDriverName() {
		return driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}
	
	@Transient
	public int getRequestTypeId() {
		return requestTypeId;
	}

	public void setRequestTypeId(int requestTypeId) {
		this.requestTypeId = requestTypeId;
	}

	@Override
	public String toString() {
		return "Requests [requestId=" + requestId + ", requestTypeId="
				+ requestTypeId + ", status=" + status + ", requestTypes="
				+ requesttypes + ", company=" + company + ", requester="
				+ requester + ", approver=" + approver + ", issuer=" + issuer
				+ ", contractId=" + contractId + ", requestDate=" + requestDate
				+ ", issueDate=" + issueDate + ", postDate=" + postDate
				+ ", vendorId=" + vendorId + ", vendorName=" + vendorName
				+ ", driverId=" + driverId + ", efsAmount=" + efsAmount
				+ ", serviceCharge=" + serviceCharge + ", glAccount="
				+ glAccount + ", glDescription=" + glDescription
				+ ", proNumber=" + proNumber + ", poWoNumber=" + poWoNumber
				+ ", truckId=" + truckId + ", chassisNumber=" + chassisNumber
				+ ", containerNumber=" + containerNumber + ", claimNumber="
				+ claimNumber + ", claimType=" + claimType + ", tagEquipment="
				+ tagEquipment + ", tagPurchType=" + tagPurchType
				+ ", description=" + description
				+ ", moneyCodeReferenceNumber=" + moneyCodeReferenceNumber
				+ ", moneyCode=" + moneyCode + ", rejectionReason="
				+ rejectionReason + ", isChargedToCustomer="
				+ isChargedToCustomer + ", driverName=" + driverName + "]";
	}

	@Transient
	public int getStatusId() {
		return statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}
//	@Transient
//	public String getPathToInvoice() {
//		return pathToInvoice;
//	}
//
//	public void setPathToInvoice(String pathToInvoice) {
//		this.pathToInvoice = pathToInvoice;
//	}

}
