package com.imc.efs.automation.entities;

// Generated Apr 6, 2015 4:37:07 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Requesttypecomments generated by hbm2java
 */
@Entity
@Table(name = "requesttypecomments", schema = "dbo")
public class Requesttypecomments implements java.io.Serializable {

	private int id;
	private Date timestamp;
	private Requesttypes requesttypes;
	private String note;
	private Character user;

	public Requesttypecomments() {
	}

	public Requesttypecomments(int id, Requesttypes requesttypes) {
		this.id = id;
		this.requesttypes = requesttypes;
	}

	public Requesttypecomments(int id, Requesttypes requesttypes, String note,
			Character user) {
		this.id = id;
		this.requesttypes = requesttypes;
		this.note = note;
		this.user = user;
	}

	@Id
	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Timestamp", nullable = false, length = 29)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RequestTypeId", nullable = false)
	public Requesttypes getRequesttypes() {
		return this.requesttypes;
	}

	public void setRequesttypes(Requesttypes requesttypes) {
		this.requesttypes = requesttypes;
	}

	@Column(name = "Note", length = 99)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "User", length = 1)
	public Character getUser() {
		return this.user;
	}

	public void setUser(Character user) {
		this.user = user;
	}

}
