package com.imc.efs.automation.entities;

// Generated Apr 6, 2015 4:37:07 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", schema = "dbo")
public class Status implements java.io.Serializable {

	private int statusId;
	private String description;

	public Status() {
	}

	public Status(int statusId) {
		this.statusId = statusId;
	}

	public Status(int statusId, String description) {
		this.statusId = statusId;
		this.description = description;
	}

	@Id
	@Column(name = "StatusId", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "Description", length = 35)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


}
